// Note :

// Place JOining_Party_Select in a BG1 / BG2 or EET game folder

// - Complete the empty fields with relevant NPC ressources.
	// - leave blank if none available.
// - Select 1 or 0 depending of NPC being for BG1, BG2 or Continuous.

// Place JOining_Party_Select in a BG1 / BG2 or EET game folder
	// - Uncomment the third component in JOining_Party_Select.tp2.
// - Install component "Next Traveler" only.
	// - Comment out the third component in JOining_Party_Select.tp2.


// Rename Next_Traveler_cpmvars.tpa with your NPC name and place it in JOining_Party_Select/Traveler/Done.
	// Provide your JOining_Party_Select version one way or another.
// To contribute on Github, please try to propose one commit with modified files for easier review.

// Exemple of Next_Traveler_cpmvars are located in JOining_Party_Select/Traveler/Done if needed..

////////////////////////////////////////////////////////////////////////////
////////  TRAVELER TYPE
////////////////////////////////////////////////////////////////////////////


// Choose = 1 if NPC is for BG1 / SoD and 0 if NPC is for BG2 or Continuous
	OUTER_SET Traveler_BG1 = 1


// Choose = 1 if NPC is for BG2 and 0 if NPC is for BG1 / SoD or Continuous
	OUTER_SET Traveler_BG2 = 0

/* Not implemented for the moment
// Choose = 1 if NPC is for SoD only and 0 if NPC is for BG1 / SoD, BG2 or Continuous
	OUTER_SET Traveler_SoD =0
*/

// Choose = 1 if NPC is for BG2 and 0 if NPC is for BG1 / SoD or BG2
	OUTER_SET Traveler_Continuous = 0

////////////////////////////////////////////////////////////////////////////
////////  NAME
////////////////////////////////////////////////////////////////////////////

// Use mod name (ex : Ajantis BG2 or Kivan and Deheriana)
	OUTER_SPRINT "NEW_TRAVELER_MOD_NAME" "Aerie in BG:EE"


// Use NPC name :
	// (If another NPC already have a similar name use name_BG2 or name_BG1. ex : Alora_BG2 or Drizzt_Terror)
		// (If Traveler is Continuous use name_Continuous. ex : Alora_Continuous)
	OUTER_SPRINT "NEW_TRAVELER_NAME" "Aerie_BG1"


// Use the DeathVar / Script Name of the NPC :
	// Info in PDIALOG.2DA or on the NPC
	OUTER_SPRINT "NEW_TRAVELER_DeathVar" "B2#Aeri"


////////////////////////////////////////////////////////////////////////////
////////  OVERRIDE_SCRIPT
////////////////////////////////////////////////////////////////////////////

// Override_script for BG1.
	// Info in PDIALOG.2DA or BGDIALOG.2DA
	OUTER_SPRINT "NEW_TRAVELER_OVERRIDE_SCRIPT_NAME_BG1" "B2#Aeri2"


// Override_script for SoD if any.
	// Info in BDDIALOG.2DA
	OUTER_SPRINT "NEW_TRAVELER_OVERRIDE_SCRIPT_NAME_SoD" ""


// Override_script for BG2.
	// Info in PDIALOG.2DA
	OUTER_SPRINT "NEW_TRAVELER_OVERRIDE_SCRIPT_NAME_BG2" ""


// Override_script for ToB if any.
	// Info in PDIALOG.2DA or 25DIALOG.2DA
	OUTER_SPRINT "NEW_TRAVELER_OVERRIDE_SCRIPT_NAME_ToB" ""
// SPECIAL : Check if override ToB script is associated to an cre, if not JOining_Party_Joined.tph and Switch_Timer.tph need an addition


////////////////////////////////////////////////////////////////////////////
////////  JOINING_DIALOG
////////////////////////////////////////////////////////////////////////////

// Joining_dialog for BG1.
	// Info in PDIALOG.2DA or BGDIALOG.2DA
	OUTER_SPRINT "NEW_TRAVELER_JOINING_DIALOG_NAME_BG1" "B2#AeriJ"

// Joining_dialog for SoD if any.
	// Info in BDDIALOG.2DA
	OUTER_SPRINT "NEW_TRAVELER_JOINING_DIALOG_NAME_SoD" ""

// Joining_dialog for BG2.
	// Info in PDIALOG.2DA
	OUTER_SPRINT "NEW_TRAVELER_JOINING_DIALOG_NAME_BG2" ""

// Joining_dialog for ToB if any.
	// Info in PDIALOG.2DA or 25DIALOG.2DA
	OUTER_SPRINT "NEW_TRAVELER_JOINING_DIALOG_NAME_ToB" ""


////////////////////////////////////////////////////////////////////////////
////////  DREAM_BANTER
////////////////////////////////////////////////////////////////////////////

// Dream_banter for BG1.
	// Info in PDIALOG.2DA or BGDIALOG.2DA
	OUTER_SPRINT "NEW_TRAVELER_DREAM_BANTER_NAME_BG1" ""

// Dream_banter for SoD if any.
	// Info in BDDIALOG.2DA
	OUTER_SPRINT "NEW_TRAVELER_DREAM_BANTER_NAME_SoD" ""

// Dream_banter for BG2.
	// Info in PDIALOG.2DA
	OUTER_SPRINT "NEW_TRAVELER_DREAM_BANTER_NAME_BG2" ""

// Dream_banter for ToB if any.
	// Info in PDIALOG.2DA or 25DIALOG.2DA
	OUTER_SPRINT "NEW_TRAVELER_DREAM_BANTER_NAME_TOB" ""


////////////////////////////////////////////////////////////////////////////
////////  REGULAR_BANTER
////////////////////////////////////////////////////////////////////////////

// Regular_banter for BG1.
	// Info in INTERDIA.2DA or BGBANTER.2DA
	OUTER_SPRINT "NEW_TRAVELER_REGULAR_BANTER_NAME_BG1" ""

// Regular_banter for SoD if any.
	// Info in BDBANTER.2DA
	OUTER_SPRINT "NEW_TRAVELER_REGULAR_BANTER_NAME_SoD" ""

// Regular_banter for BG2.
	// Info in INTERDIA.2DA
	OUTER_SPRINT "NEW_TRAVELER_REGULAR_BANTER_NAME_BG2" ""

// Regular_banter for ToB if any.
	// Info in INTERDIA.2DA or 25BANTER.2DA
	OUTER_SPRINT "NEW_TRAVELER_REGULAR_BANTER_NAME_TOB" ""


////////////////////////////////////////////////////////////////////////////
////////  MOD INSTALLATION
////////////////////////////////////////////////////////////////////////////

// Use mod.tp2 name (ex : ajantisbg2 or setup-kivan).
	// Visible in Weidu.log ex : for (~BRANWEN/BRANWEN.TP2~ #2 #0) use BRANWEN.
		// ex : for (~ZDBAE/SETUP-ZDBAE.TP2~ #0 #0) use SETUP-ZDBAE.
	OUTER_SPRINT "NEW_TRAVELER_MOD_TP2" "BG1Aerie"


// Use the DESIGNATED number of the main componant mentionned in .tp2.
	// (Visible in Weidu.log ex : for (~BRANWEN/BRANWEN.TP2~ #2 #0) use 0.
		// ex : for (~KIVAN/SETUP-KIVAN.TP2~ #0 #100) use 100.
	OUTER_SPRINT "NEW_TRAVELER_MOD_COMPONANT" "5000"


/////////////////////////////////////////////////////////////////////
