	ACTION_IF (GAME_IS ~bgee~ OR GAME_INCLUDES ~SoD~) BEGIN

ACTION_IF GAME_IS ~eet~ BEGIN
	
	ACTION_BASH_FOR ~weidu_external/JOining_Party_Select/JOining_Party_BCS~ ~AR.*\.BCS$~ BEGIN
			COPY - ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~ ~weidu_external/JOining_Party_Select/JOining_Party_BCS_BG2~
			DELETE ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~
	END

	ACTION_BASH_FOR ~weidu_external/JOining_Party_Select/JOining_Party_BCS~ ~OH4.*\.BCS$~ BEGIN
			COPY - ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~ ~weidu_external/JOining_Party_Select/JOining_Party_BCS_BG2~
			DELETE ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~
	END

	ACTION_BASH_FOR ~weidu_external/JOining_Party_Select/JOining_Party_BCS~ ~OH5.*\.BCS$~ BEGIN
			COPY - ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~ ~weidu_external/JOining_Party_Select/JOining_Party_BCS_BG2~
			DELETE ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~
	END

	ACTION_BASH_FOR ~weidu_external/JOining_Party_Select/JOining_Party_BCS~ ~OH6.*\.BCS$~ BEGIN
			COPY - ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~ ~weidu_external/JOining_Party_Select/JOining_Party_BCS_BG2~
			DELETE ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~
	END

	ACTION_BASH_FOR ~weidu_external/JOining_Party_Select/JOining_Party_BCS~ ~OH7.*\.BCS$~ BEGIN
			COPY - ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~ ~weidu_external/JOining_Party_Select/JOining_Party_BCS_BG2~
			DELETE ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~
	END

	ACTION_BASH_FOR ~weidu_external/JOining_Party_Select/JOining_Party_BCS~ ~OH8.*\.BCS$~ BEGIN
			COPY - ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~ ~weidu_external/JOining_Party_Select/JOining_Party_BCS_BG2~
			DELETE ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~
	END

	ACTION_BASH_FOR ~weidu_external/JOining_Party_Select/JOining_Party_BCS~ ~OH90.*\.BCS$~ BEGIN
			COPY - ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~ ~weidu_external/JOining_Party_Select/JOining_Party_BCS_BG2~
			DELETE ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~
	END

	ACTION_BASH_FOR ~weidu_external/JOining_Party_Select/JOining_Party_BCS~ ~OH91.*\.BCS$~ BEGIN
			COPY - ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~ ~weidu_external/JOining_Party_Select/JOining_Party_BCS_BG2~
			DELETE ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~
	END

	ACTION_BASH_FOR ~weidu_external/JOining_Party_Select/JOining_Party_BCS~ ~NW.*\.BCS$~ BEGIN
			COPY - ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~ ~weidu_external/JOining_Party_Select/JOining_Party_BCS_BG2~
			DELETE ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~
	END

	ACTION_BASH_FOR ~weidu_external/JOining_Party_Select/JOining_Party_BCS~ ~XG.*\.BCS$~ BEGIN
			COPY - ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~ ~weidu_external/JOining_Party_Select/JOining_Party_BCS_BG2~
			DELETE ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~
	END

END

ACTION_FOR_EACH Death_var IN

// Original Imoen ~%IMOEN_DV%~ // ~ttimoen~ ~Imoen~  // Imoen
// Original Edwin ~Edwin~                            // Edwin
// Original Jaheira ~Jaheira~ // ~ttjaheir~             // Jaheira
// Original Minsc ~Minsc~ // ~ttminsc~                  // Minsc
// Original Viconia ~Viconia~                        // Viconia
// Original Dorn ~Dorn~                              // Dorn
// Original Neera ~Neera~                            // Neera
// Original Rasaad ~Rasaad~                          // Rasaad

/////////////////////////// bg1 ///////////////////////////

// Original Ajantis ~Ajantis~                          // Ajantis
// Original Alora ~Alora~                              // Alora
// Original Branwen ~Branwen~ // ~ttbran~              // Branwen
// Original Coran ~Coran~                              // Coran
// Original Dynaheir ~Dynaheir~                        // Dynaheir

// Original Eldoth ~Eldoth~                            // Eldoth
// Original Faldorn ~Faldorn~                          // Faldorn
// Original Garrick ~Garrick~                          // Garrick

// Original Kagain ~Kagain~                            // Kagain
// Original Khalid ~Khalid~                            // Khalid
// Original Kivan ~Kivan~                              // Kivan

// Original Montaron ~Montaron~                        // Montaron
// Original Quayle ~Quayle~                            // Quayle
// Original Safana ~Safana~                            // Safana
// Original Sharteel ~Sharteel~ // ~Shar-teel~         // Sharteel
// Original Skie ~Skie~                                // Skie
// Original Tiax ~Tiax~                                // Tiax

// Original Xan ~Xan~ // ttxan~                        // Xan
// Original Xzar ~Xzar~                                // Xzar
// Original Yeslick ~Yeslick~                          // Yeslick

// Original Baeloth ~Baeloth~                          // Baeloth


/////////////////////////// SoD ///////////////////////////


// Original Voghiln ~Voghiln~                         // Voghiln
// Original Corwin ~Corwin~                           // Corwin
// Original Mkhiin ~Mkhiin~                           // Mkhiin
// Original Glint ~Glint~                             // Glint

/////////////////////////// Mods BG1 ///////////////////////////


// Mod Ishlilka ~#Ishy~                                                // Ishlilka_The-Wizard-Slayer

// ChaosKnight-kit
// Mod Jacob ~ZYJCOB~

// Askaria-Quest
// Mod Askaria ~ZYASKA~

// Isra BG1
// Mod Isra_BG1 ~rh#isra~

// Finch
// Mod Finch ~SUFINCH~

// Drizzt Saga
// Mod Jarlaxle_Saga ~F_JARLAXE~
// Mod Artemis_Enteri_Saga ~F_ARTEMIS~
// Mod Catti-Brie_Saga ~F_CATTIBR~
// Mod Bruenor_Saga ~F_BRUENOR~
// Mod Regis_Saga ~F_REGIS~
// Mod Drizzt_Saga ~F_DRIZZT~
// Mod Wulfgar_Saga ~F_WULFGAR~

// Dark Horizons
// Mod Nikita_BG1 ~cmnikita~
// Mod Thorin ~CMTTHOR~
// Mod Morwen ~CMTMORW~

// DSotSC
// Mod Bardo ~DSBARDO~
// Mod Bub_Snikt ~DSBUB~
// Mod Conchobhair ~Conchobhair~
// Mod CuChoinneach ~CuChoinneach~
// Mod Ferthgil_Trollslayer ~Ferthgil~
// Mod Jet'laya ~JETLAYA~
// Mod Keiria_Silverstring ~KEIRIA~
// Mod Skeezer_Lumpkin_VI ~SKEEZER~
// Mod Thorfinn_Hauskluniff ~Thorfinn~

// NTotSC
// Mod Will_Scarlet ~WILL~

// Next_Traveler BG1


BEGIN

		INCLUDE ~JOining_Party_Select/Lib/JOining_Party_Select_BCS.tph~

		INCLUDE ~JOining_Party_Select/Lib/JOining_Party_Select_DLG.tph~

END

	END

	ACTION_IF GAME_IS ~bg2ee eet~ BEGIN

ACTION_IF GAME_IS ~eet~ BEGIN

	COPY ~weidu_external/JOining_Party_Select/JOining_Party_BCS_BG2~ ~weidu_external/JOining_Party_Select/JOining_Party_BCS~
	
	ACTION_BASH_FOR ~weidu_external/JOining_Party_Select/JOining_Party_BCS~ ~BG.*\.BCS$~ BEGIN
			COPY - ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~ ~weidu_external/JOining_Party_Select/JOining_Party_BCS_BG1~
			DELETE ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~
	END

	ACTION_BASH_FOR ~weidu_external/JOining_Party_Select/JOining_Party_BCS~ ~BD.*\.BCS$~ BEGIN
			COPY - ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~ ~weidu_external/JOining_Party_Select/JOining_Party_BCS_BG2~
			DELETE ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~
	END

	ACTION_BASH_FOR ~weidu_external/JOining_Party_Select/JOining_Party_BCS~ ~OH1.*\.BCS$~ BEGIN
			COPY - ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~ ~weidu_external/JOining_Party_Select/JOining_Party_BCS_BG2~
			DELETE ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~
	END

	ACTION_BASH_FOR ~weidu_external/JOining_Party_Select/JOining_Party_BCS~ ~OH2.*\.BCS$~ BEGIN
			COPY - ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~ ~weidu_external/JOining_Party_Select/JOining_Party_BCS_BG2~
			DELETE ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~
	END

	ACTION_BASH_FOR ~weidu_external/JOining_Party_Select/JOining_Party_BCS~ ~OH3.*\.BCS$~ BEGIN
			COPY - ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~ ~weidu_external/JOining_Party_Select/JOining_Party_BCS_BG2~
			DELETE ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~
	END

	ACTION_BASH_FOR ~weidu_external/JOining_Party_Select/JOining_Party_BCS~ ~OH93.*\.BCS$~ BEGIN
			COPY - ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~ ~weidu_external/JOining_Party_Select/JOining_Party_BCS_BG2~
			DELETE ~weidu_external/JOining_Party_Select/JOining_Party_BCS/%BASH_FOR_FILE%~
	END
END

ACTION_FOR_EACH Death_var IN

// Original Imoen ~%IMOEN_DV%~ // ~ttimoen~ ~Imoen~  // Imoen
// Original Edwin ~Edwin~                            // Edwin
// Original Jaheira ~Jaheira~ // ~ttjaheir~             // Jaheira
// Original Minsc ~Minsc~ // ~ttminsc~                  // Minsc
// Original Viconia ~Viconia~                        // Viconia
// Original Dorn ~Dorn~                              // Dorn
// Original Neera ~Neera~                            // Neera
// Original Rasaad ~Rasaad~                          // Rasaad


/////////////////////////// bg2 ///////////////////////////


// Original Aerie ~Aerie~                               // Aerie
// Original Anomen ~Anomen~                             // Anomen
// Original Cernd ~Cernd~                               // Cernd
// Original Haerdalis ~Haerdalis~                       // Haerdalis
// Original Hexxat ~Hexxat~                             // Hexxat
// Original Jan ~Jan~                                   // Jan
// Original Keldorn ~Keldorn~                           // Keldorn
// Original Korgan ~Korgan~                             // Korgan
// Original Mazzy ~Mazzy~                               // Mazzy
// Original Nalia ~Nalia~                               // Nalia
// Original Sarevok ~Sarevok~                           // Sarevok
// Original Valygar ~Valygar~                           // Valygar
// Original Wilson ~Wilson~                             // Wilson
// Original Yoshimo ~Yoshimo~                           // Yoshimo

/////////////////////////// Mods BG2 ///////////////////////////

// Alora BG2
// Mod Alora BG2 ~CMALORA~

// Yeslick BG2
// Mod Yeslick BG2 ~LK#YESLK~

// The Undying
// Mod Undying ~cmninaf~ ~callisto~

// Summon Bhaalspawn
// Mod Sandra ~BHAALSPW~

// NikitaRedux
// Mod NikitaRedux ~cmnikita~

// VampireTales
// Mod Miriam ~cmgmiriam~

// Kim
// Mod Kim ~Kim~

// Severian
// Mod Severian ~#Severian~

// Frennedan
// Mod Frennedan ~Frennedan~

// Branwen BG2
// Mod Branwen_BG2 ~O#Bran~
// Tiax BG2
// Mod Tiax_BG2 ~O#Tiax~
// Xan BG2
// Mod Xan_BG2 ~O#XAN~
// Coran BG2
// Mod Coran_BG2 ~O#Coran~

// Auren Aseph
// Mod Auren ~K#AUREN~

// Isra BG2
// Mod Isra_BG2 ~rh#Isra2~

// Nephele
// Mod Nephele_Samios ~Nephele~

// Sheena
// Mod Sheena ~K#SHEENA~

// Kiara / Zaiya
// Mod Kiara ~Kiara~
// Mod Zaiya ~Zaiya~

// The Beaurin Legacy
// Mod Minyae ~QI#MI~
// Mod Elaryn ~QI#ELA~

// Tyris Flare
// Mod Tyris ~g#Tyris~

// Region of Terror
// Mod Wulfgar_Terror ~Wulfg2~
// Mod Regis_Terror ~Reg2~
// Mod Drizzt_Terror ~Driz2~
// Mod Bruenor_Terror ~Brue2~
// Mod Catti-Brie_Terror ~Catt2~
// Mod Artemis_Entreri_Terror ~Enter2~
// Mod Jarlaxle_Terror ~Jarlax2~
// Mod Tapio_Perkiomaki_Terror ~Tapio~
// Mod Randall_Terror ~Randall~
// Mod Alissa_Terror ~ALISSA1~
// Mod Mordragon_Terror ~Mordrg~

//Shadow over Soubar
// Mod Selence_Hillstar_Soubar ~SELENCE~
// Mod Charlotte_Soubar ~CHARLOTT~
// Mod Bolivar_Soubar ~BOLIVAR~
// Mod Tomas_Tomalson_Soubar ~TOMASTM~

// ajantisbg2
// Mod Ajantis_BG2 ~C#Ajantis~

// Next_Traveler BG2

BEGIN

		INCLUDE ~JOining_Party_Select/Lib/JOining_Party_Select_BCS.tph~

		INCLUDE ~JOining_Party_Select/Lib/JOining_Party_Select_DLG.tph~

END

	END

ACTION_IF GAME_IS ~eet~ BEGIN

	COPY ~weidu_external/JOining_Party_Select/JOining_Party_BCS_BG1~ ~weidu_external/JOining_Party_Select/JOining_Party_BCS~
END
