IF
	Clicked([ANYONE])
	NearLocation(LastTrigger,790,1660,12)
	!InMyArea("imoen2")
	OR(2)
		Dead("bdkorlas")  // Korlasz
		Global("BD_KORLASZ_SURRENDER","GLOBAL",1)
	GlobalGT("bd_plot","global",25)
THEN
	RESPONSE #100
		CreateVisualEffect("JOBG402",[748.1601])
		Wait(2)
		MoveGlobal("BD0120","%IMOEN_DV%",[748.1601])
		ActionOverride("%IMOEN_DV%",SetDialog("BDIMOEN"))
		Wait(2)
		ActionOverride("%IMOEN_DV%",StartDialogueNoSet(Player1))
END

IF
	Clicked([ANYONE])
	NearLocation(LastTrigger,790,1660,12)
	!InMyArea("imoen2")
	Global("BD_KORLASZ_SURRENDER","GLOBAL",1)
	!Global("bd_plot","global",26)
THEN
	RESPONSE #100
		SetGlobal("bd_plot","global",26)
		CreateVisualEffect("JOBG402",[748.1601])
		Wait(2)
		MoveGlobal("BD0120","%IMOEN_DV%",[748.1601])
		ActionOverride("%IMOEN_DV%",SetDialog("BDIMOEN"))
		Wait(2)
		ActionOverride("%IMOEN_DV%",StartDialogueNoSet(Player1))
END

IF
	Clicked([ANYONE])
	NearLocation(LastTrigger,790,1660,12)
	!InMyArea("imoen2")
	Dead("bdkorlas")  // Korlasz
	!Global("bd_plot","global",27)
THEN
	RESPONSE #100
		SetGlobal("bd_plot","global",27)
		CreateVisualEffect("JOBG402",[748.1601])
		Wait(2)
		MoveGlobal("BD0120","%IMOEN_DV%",[748.1601])
		ActionOverride("%IMOEN_DV%",SetDialog("BDIMOEN"))
		Wait(2)
		ActionOverride("%IMOEN_DV%",StartDialogueNoSet(Player1))
END
