
///////////////////////////////////////////////////////////////////////////
 // BDSODTRN cutscene to MoveToCampaign("SoD")
///////////////////////////////////////////////////////////////////////////

ACTION_IF MOD_IS_INSTALLED ~C#ENDLESSBG1.TP2~ ~0~ BEGIN

	// MoveToCampaign bg2 c#ebg122.bcs
	COPY_EXISTING ~c#ebg122.BCS~ ~weidu_external/JOining_Party_Select/Compat/JOebg122.Baf~
		DECOMPILE_BCS_TO_BAF

	COMPILE ~JOining_Party_Select/Campaign_Transition/c#ebg122.BAF~

	COMPILE ~weidu_external/JOining_Party_Select/Compat/JOebg122.Baf~

// For JO_JOINP.baf
			OUTER_SPRINT "Cut_c#ebg122" ~~~~~

IF
	Global("JO_JOIN_JUMP_JO2608","LOCALS",4)
	Global("JO_JOIN_c#ebg122","GLOBAL",1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		DisplayStringHead(Myself,~Allons-y !~)
		Wait(1)
		SetGlobal("JO_JOIN_c#ebg122","GLOBAL",2)
		FadeFromColor([30.0],0)
		ActionOverride(Player1,LeaveAreaLUA("BG0200","",[1925.2877],1))
		ActionOverride(Player2,LeaveAreaLUA("BG0200","",[2027.2670],1))
		ActionOverride(Player3,LeaveAreaLUA("BG0200","",[1868.2792],1))
		ActionOverride(Player4,LeaveAreaLUA("BG0200","",[2011.2825],1))
		ActionOverride(Player5,LeaveAreaLUA("BG0200","",[1978.2728],1))
		ActionOverride(Player6,LeaveAreaLUA("BG0200","",[1947.2777],1))
		LeaveAreaLUAPanic("BG0200","",[1925.2877],1)
		LeaveAreaLUA("BG0200","",[1925.2877],1)
		MultiPlayerSync()
		SetInterrupt(TRUE)
END

IF
	AreaCheck("%NBaldursGate%")
	Global("JO_JOIN_JUMP_JO2608","LOCALS",4)
	Global("JO_JOIN_c#ebg122","GLOBAL",2)
THEN
	RESPONSE #100
		Wait(1)
		StartCutSceneMode()
		StartCutSceneEx("JOebg122",TRUE)
END

~~~~~

// To END_OF_WATCH.tph for All_in.baf
			OUTER_SPRINT ~c#ebg122_END_OF_WATCH~ ~~~~~

IF
	Global("JO_JOIN_c#ebg122","GLOBAL",1)
//
	Global("JO_JOIN_CUTSCENE","GLOBAL",0)
	Global("JO_JOIN_LOADING_SWITCH","GLOBAL",0) // Loading switch inactive
	Global("JO_JOIN_CUTSCENE","GLOBAL",0) // No cuscene
	Global("JO_NOJOIN","GLOBAL",0) // No join stop
	Global("JO_JOIN_RETURN_SLOT","GLOBAL",0) // Not implemented
//
//	Global("JO_Myself_LeaveParty","LOCALS",0)
	Global("JO_JOIN_END_OF_WATCH","LOCALS",1)
	Switch("JO_JOIN_TALK_TRANSITION","LOCALS") // Only one traveler say something (Set in JO_JOINI.baf)
THEN
	RESPONSE #0
		SetInterrupt(FALSE)
		MakeGlobalOverride()
		SetGlobal("K#PartySoD","LOCALS",1)
		SetGlobal("JO_JOIN_END_OF_WATCH","LOCALS",2)
		SetGlobal("JO_JOIN_END_OF_SOD","LOCALS",1)
		CreateVisualEffectObject("JOBG402",Myself)
		SetInterrupt(TRUE)
		DestroySelf()
	RESPONSE #1
		SetInterrupt(FALSE)
		MakeGlobalOverride()
		DisplayStringHead(Myself,~It was a great... We will meet again !~)
		SetGlobal("K#PartySoD","LOCALS",1)
		SetGlobal("JO_JOIN_END_OF_WATCH","LOCALS",2)
		SetGlobal("JO_JOIN_END_OF_SOD","LOCALS",1)
		SetCutSceneLite(FALSE)
		CreateVisualEffectObject("JOBG402",Myself)
		SetInterrupt(TRUE)
		DestroySelf()
END

~~~~~


END ELSE BEGIN

	OUTER_SPRINT ~Cut_c#ebg122~ ~~

	OUTER_SPRINT ~c#ebg122_CAMPAIGN_TRANSITION~ ~~

	OUTER_SPRINT "c#ebg122_END_OF_WATCH" ~~

END
