// Prevent some BG1 or SoD traveler to vanish in EET (Only for traveler with no content in SoD or BG2)
	// Global("JO_JOIN_END_OF_BG1","LOCALS",0) will be at 1 for NPC without SoD content
		// Global("JO_JOIN_END_OF_SOD","LOCALS",0) will be at 1 for NPC without BG2 content

ACTION_IF MOD_IS_INSTALLED ~IWD_EET_END.TP2~ ~0~ BEGIN

<<<<<<<<override_DestroySelf_add.baf
IF
	!AreaType(IWDAREA)
	Global("JO_Myself_AllowDead","LOCALS",0)
	GlobalGT("CHAPTER","GLOBAL",13)
THEN
	RESPONSE #100
		DestroySelf()
END
>>>>>>>>

<<<<<<<<override_DestroySelf_rep.baf
IF
	!AreaType(IWDAREA)
	Global("JO_Myself_AllowDead","LOCALS",0)
	GlobalGT("CHAPTER","GLOBAL",13)
	Global("JO_JOIN_END_OF_SOD","LOCALS",0)
THEN
	RESPONSE #100
		DestroySelf()
END
>>>>>>>>
COPY_EXISTING ~%bcs%.bcs~ ~override~
  REPLACE_BCS_BLOCK ~override_DestroySelf_add.baf~ ~override_DestroySelf_rep.baf~  ON_MISMATCH PATCH_PRINT ~%SOURCE_FILE% : DestroySelf() block don't exists in %SOURCE_FILE%... No need patching~ END

END ELSE BEGIN

<<<<<<<<override_DestroySelf_add.baf
IF
	Global("JO_Myself_AllowDead","LOCALS",0)
	GlobalGT("CHAPTER","GLOBAL",13)
THEN
	RESPONSE #100
		DestroySelf()
END
>>>>>>>>

<<<<<<<<override_DestroySelf_rep.baf
IF
	Global("JO_Myself_AllowDead","LOCALS",0)
	GlobalGT("CHAPTER","GLOBAL",13)
	Global("JO_JOIN_END_OF_SOD","LOCALS",0)
THEN
	RESPONSE #100
		DestroySelf()
END
>>>>>>>>
COPY_EXISTING ~%bcs%.bcs~ ~override~
  REPLACE_BCS_BLOCK ~override_DestroySelf_add.baf~ ~override_DestroySelf_rep.baf~ ON_MISMATCH PATCH_PRINT ~%SOURCE_FILE% : DestroySelf() block don't exists in %SOURCE_FILE%... No need patching~ END

END

ACTION_IF MOD_IS_INSTALLED ~IWD_EET_END.TP2~ ~0~ BEGIN

<<<<<<<<override_DestroySelf_add.baf
IF
	!AreaType(IWDAREA)
	GlobalGT("ENDOFBG1","GLOBAL",0)
THEN
	RESPONSE #100
		DestroySelf()
END
>>>>>>>>

<<<<<<<<override_DestroySelf_rep.baf
IF
	!AreaType(IWDAREA)
	GlobalGT("ENDOFBG1","GLOBAL",0)
	Global("JO_JOIN_END_OF_BG1","LOCALS",0)
THEN
	RESPONSE #100
		DestroySelf()
END
>>>>>>>>
COPY_EXISTING ~%bcs%.bcs~ ~override~
  REPLACE_BCS_BLOCK ~override_DestroySelf_add.baf~ ~override_DestroySelf_rep.baf~  ON_MISMATCH PATCH_PRINT ~%SOURCE_FILE% : DestroySelf() block don't exists in %SOURCE_FILE%... No need patching~ END

END ELSE BEGIN

<<<<<<<<override_DestroySelf_add.baf
IF
	GlobalGT("ENDOFBG1","GLOBAL",0)
THEN
	RESPONSE #100
		DestroySelf()
END
>>>>>>>>

<<<<<<<<override_DestroySelf_rep.baf
IF
	GlobalGT("ENDOFBG1","GLOBAL",0)
	Global("JO_JOIN_END_OF_BG1","LOCALS",0)
THEN
	RESPONSE #100
		DestroySelf()
END
>>>>>>>>
COPY_EXISTING ~%bcs%.bcs~ ~override~
  REPLACE_BCS_BLOCK ~override_DestroySelf_add.baf~ ~override_DestroySelf_rep.baf~
	ON_MISMATCH PATCH_PRINT ~%SOURCE_FILE% : DestroySelf() block don't exists in %SOURCE_FILE%... No need patching~ 
		/*INNER_ACTION BEGIN
			EXTEND_BOTTOM ~%bcs%.bcs~ ~override_DestroySelf_rep.baf~
				PATCH_PRINT ~%SOURCE_FILE% : DestroySelf() block added in %SOURCE_FILE%...~
				PATCH_PRINT ~... // For Global("JO_JOIN_END_OF_BG1","LOCALS",0)
				~
		END*/
	END
END
 