// Expand JO2608.baf
	// Regular : At BG or SoD end, Travelers go to the switching room and can be recruted again.
		// SoD_Content : At BG end, Travelers with SoD content are destroyself once in the switching room.
			// BG2_Content : At SoD end, Travelers with BG2 content are destroyself once in the switching room.


// Regular

	ACTION_IF (~%Death_var%_SoD_Content~ = 0 AND ~%Death_var%_BG2_Content~ = 0) THEN BEGIN

	OUTER_SET x_coo = RANDOM(764 1177)
	OUTER_SET y_coo = RANDOM(207 487)

<<<<<<<< .../JOining_JO2608.baf

IF
	!TriggerOverride("%Death_var%",Global("JO_JOIN_END_OF_WATCH","LOCALS",0))
	!InMyArea("%Death_var%")
THEN
	RESPONSE #100
		FadeToColor([00.0],0)
		SetGlobal("JO2608_Create","MYAREA",1)
		ActionOverride("%Death_var%",SetGlobal("JO_JOIN_END_OF_WATCH","LOCALS",0))
		MoveGlobal("JO2608","%Death_var%",[%x_coo%.%y_coo%])
		ActionOverride("JO_JOIN_Room_Container",TakeCreatureItems("%Death_var%",BACKPACK))
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
END

>>>>>>>>
EXTEND_BOTTOM ~JO2608.bcs~ ~.../JOining_JO2608.baf~ EVALUATE_BUFFER

	END

// SoD_Content only

	ACTION_IF (~%Death_var%_SoD_Content~ = 1 AND NOT ~%Death_var%_BG2_Content~ = 1) THEN BEGIN

	OUTER_SET x_coo = RANDOM(1864 2220)
	OUTER_SET y_coo = RANDOM(963 1196)


<<<<<<<< .../JOining_SoD_JO2608.baf

IF
	!TriggerOverride("%Death_var%",Global("JO_JOIN_END_OF_WATCH","LOCALS",0))
	!InMyArea("%Death_var%")
THEN
	RESPONSE #100
		FadeToColor([00.0],0)
		SetGlobal("JO2608_Create","MYAREA",1)
		ActionOverride("%Death_var%",SetGlobal("JO_JOIN_END_OF_WATCH","LOCALS",0))
		MoveGlobal("JO2608","%Death_var%",[%x_coo%.%y_coo%])
		ActionOverride("JO_JOIN_Room_Container",TakeCreatureItems("%Death_var%",BACKPACK))
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
END

IF
	!TriggerOverride("%Death_var%",Global("JO_JOIN_END_OF_BG1","LOCALS",0))
	InMyArea("%Death_var%")
THEN
	RESPONSE #100
		DisplayStringHead(Player1,~%%Death_var%_name% has heard about the crusade.~)
		Wait(2)
		ActionOverride("%Death_var%",SetGlobal("JO_JOIN_END_OF_BG1","LOCALS",0))
		ActionOverride("%Death_var%",DestroySelf())
END

>>>>>>>>
EXTEND_BOTTOM ~JO2608.bcs~ ~.../JOining_SoD_JO2608.baf~ EVALUATE_BUFFER


	END 


// BG2_Content only

		ACTION_IF (~%Death_var%_BG2_Content~ = 1 AND NOT ~%Death_var%_SoD_Content~ = 1) THEN BEGIN

	OUTER_SET x_coo = RANDOM(1260 1607)
	OUTER_SET y_coo = RANDOM(1410 1643)


<<<<<<<< .../JOining_BG2_JO2608.baf

IF
	!TriggerOverride("%Death_var%",Global("JO_JOIN_END_OF_WATCH","LOCALS",0))
	!InMyArea("%Death_var%")
THEN
	RESPONSE #100
		FadeToColor([00.0],0)
		SetGlobal("JO2608_Create","MYAREA",1)
		ActionOverride("%Death_var%",SetGlobal("JO_JOIN_END_OF_WATCH","LOCALS",0))
		MoveGlobal("JO2608","%Death_var%",[%x_coo%.%y_coo%])
		ActionOverride("JO_JOIN_Room_Container",TakeCreatureItems("%Death_var%",BACKPACK))
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
END

IF
	!TriggerOverride("%Death_var%",Global("JO_JOIN_END_OF_SOD","LOCALS",0))
	InMyArea("%Death_var%")
THEN
	RESPONSE #100
		DisplayStringHead(Player1,~%%Death_var%_name% has heard about the city of coins.~)
		Wait(2)
		ActionOverride("%Death_var%",SetGlobal("JO_JOIN_END_OF_SOD","LOCALS",0))
		ActionOverride("%Death_var%",DestroySelf())
END

>>>>>>>>
EXTEND_BOTTOM ~JO2608.bcs~ ~.../JOining_BG2_JO2608.baf~ EVALUATE_BUFFER


		END


// SoD and BG2_Content

		ACTION_IF (~%Death_var%_BG2_Content~ = 1 AND ~%Death_var%_SoD_Content~ = 1) THEN BEGIN

	OUTER_SET x_coo = RANDOM(1260 1607)
	OUTER_SET y_coo = RANDOM(1410 1643)


<<<<<<<< .../JOining_BG2_JO2608.baf

IF
	!TriggerOverride("%Death_var%",Global("JO_JOIN_END_OF_WATCH","LOCALS",0))
	!InMyArea("%Death_var%")
THEN
	RESPONSE #100
		FadeToColor([00.0],0)
		SetGlobal("JO2608_Create","MYAREA",1)
		ActionOverride("%Death_var%",SetGlobal("JO_JOIN_END_OF_WATCH","LOCALS",0))
		MoveGlobal("JO2608","%Death_var%",[%x_coo%.%y_coo%])
		ActionOverride("JO_JOIN_Room_Container",TakeCreatureItems("%Death_var%",BACKPACK))
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
END

IF
	!TriggerOverride("%Death_var%",Global("JO_JOIN_END_OF_BG1","LOCALS",0))
	InMyArea("%Death_var%")
THEN
	RESPONSE #100
		DisplayStringHead(Player1,~%%Death_var%_name% has heard about the crusade.~)
		ActionOverride("%Death_var%",SetGlobal("JO_JOIN_END_OF_BG1","LOCALS",0))
		ActionOverride("%Death_var%",DestroySelf())
END

IF
	!TriggerOverride("%Death_var%",Global("JO_JOIN_END_OF_SOD","LOCALS",0))
	InMyArea("%Death_var%")
THEN
	RESPONSE #100
		DisplayStringHead(Player1,~%%Death_var%_name% has heard about the city of coins.~)
		ActionOverride("%Death_var%",SetGlobal("JO_JOIN_END_OF_SOD","LOCALS",0))
		ActionOverride("%Death_var%",DestroySelf())
END

>>>>>>>>
EXTEND_BOTTOM ~JO2608.bcs~ ~.../JOining_BG2_JO2608.baf~ EVALUATE_BUFFER


		END


///////////////////////////////////////////////////////////////////////////////

// END_OF_WATCH

///////////////////////////////////////////////////////////////////////////////
// Note :
		// Expand All_in.baf for BG1/SoD npc
			// After Leave Party above
				// Special BG1/SoD end
					// Related to JO_JOIN_CAMPAIGN_TRANSITION in JO_JOINI.baf
///////////////////////////////////////////////////////////////////////////////

//		ACTION_IF ~BG1_%Death_var%_Select~ = 1 OR ~SoD_%Death_var%_Select~ = 1 OR ~Continuous_%Death_var%_Select~ = 1 THEN BEGIN

COPY ~weidu_external/JOining_Party_Select/All_In/%Death_var%_All_In.baf~  ~weidu_external/JOining_Party_Select/All_In/%Death_var%_All_In.baf~ EVALUATE_BUFFER
	REPLACE_TEXTUALLY ~// REPLACE_END_OF_WATCH~ ~~~~~IF
	AreaCheck("BD0120")
//
	Global("JO_JOIN_CUTSCENE","GLOBAL",0)
	Global("JO_JOIN_LOADING_SWITCH","GLOBAL",0) // Loading switch inactive
	Global("JO_JOIN_CUTSCENE","GLOBAL",0) // No cuscene
	Global("JO_NOJOIN","GLOBAL",0) // No join stop
	Global("JO_JOIN_RETURN_SLOT","GLOBAL",0) // Not implemented
//
	Global("JO_Myself_LeaveParty","LOCALS",0)
	Global("JO_JOIN_END_OF_WATCH","LOCALS",1)
	Switch("JO_JOIN_TALK_TRANSITION","LOCALS") // Only one traveler say something (Set in JO_JOINI.baf)
THEN
	RESPONSE #0
		MakeGlobalOverride()
		SetGlobal("K#PartySoD","LOCALS",1)
		CreateVisualEffectObject("JOBG402",Myself)
		Wait(2)
		SetGlobal("JO_JOIN_END_OF_WATCH","LOCALS",2)
		SetGlobal("JO_JOIN_END_OF_BG1","LOCALS",1)
		DestroySelf()
	RESPONSE #1
		MakeGlobalOverride()
		SetGlobal("K#PartySoD","LOCALS",1)
		DisplayStringHead(Myself,~We will meet again.~)
		HideGUI()
		Wait(3)
		CreateVisualEffectObject("JOBG402",Myself)
		Wait(2)
		SetGlobal("JO_JOIN_END_OF_WATCH","LOCALS",2)
		SetGlobal("JO_JOIN_END_OF_BG1","LOCALS",1)
		DestroySelf()
END

IF
	AreaCheck("BD6000")
//
	Global("JO_JOIN_CUTSCENE","GLOBAL",0)
	Global("JO_JOIN_LOADING_SWITCH","GLOBAL",0) // Loading switch inactive
	Global("JO_JOIN_CUTSCENE","GLOBAL",0) // No cuscene
	Global("JO_NOJOIN","GLOBAL",0) // No join stop
	Global("JO_JOIN_RETURN_SLOT","GLOBAL",0) // Not implemented
//
	Global("JO_Myself_LeaveParty","LOCALS",0)
	Global("JO_JOIN_END_OF_WATCH","LOCALS",1)
	Switch("JO_JOIN_TALK_TRANSITION","LOCALS") // Only one traveler say something (Set in JO_JOINI.baf)
THEN
	RESPONSE #0
		MakeGlobalOverride()
		CreateVisualEffectObject("JOBG402",Myself)
		Wait(2)
		SetGlobal("JO_JOIN_END_OF_WATCH","LOCALS",2)
		SetGlobal("JO_JOIN_END_OF_SOD","LOCALS",1)
		DestroySelf()
	RESPONSE #1
		MakeGlobalOverride()
		DisplayStringHead(Myself,~Gonna make a diversion, the Flamming Fist will search for you everywhere...~)
		HideGUI()
		Wait(3)
		CreateVisualEffectObject("JOBG402",Myself)
		Wait(2)
		SetGlobal("JO_JOIN_END_OF_WATCH","LOCALS",2)
		SetGlobal("JO_JOIN_END_OF_SOD","LOCALS",1)
		DestroySelf()
END~~~~~

//		END

<<<<<<<< .../JOining_stay_JO2608.baf

IF
	TriggerOverride("%Death_var%",Global("JO_Myself_AllowDead","LOCALS",0))
	Global("JO_JOIN_LOADING_SWITCH","GLOBAL",0)
	InMyArea("%Death_var%")
	!Dead("%Death_var%")
	Global("JO2608_Create","MYAREA",0)
	RandomNum(30,5)
THEN
	RESPONSE #10
		DisplayStringHead("%Death_var%",~Don't expect me to do the dishes.~)
		ActionOverride("%Death_var%",MoveToPointNoInterrupt([253.823]))
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #10
		ActionOverride("%Death_var%",RandomTurn())
		DisplayStringHead("%Death_var%",~What about now ?~)
		Wait(2)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #10
		DisplayStringHead("%Death_var%",~Ha ha... Ha ha ha...~)
		Wait(4)
		DisplayStringHead("%Death_var%",~HAHAHAHAAAAAAAAH !~)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #10
		DisplayStringHead("%Death_var%",~Good on you if you save the day. I care not, for I am gone !~)
		ActionOverride("%Death_var%",MoveToPointNoInterrupt([1860.1346]))
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #10
		DisplayStringHead("%Death_var%",~I have nothing else to do...~)
		ActionOverride("%Death_var%",MoveToPointNoInterrupt([1655.666]))
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #10
		ActionOverride("%Death_var%",RandomTurn())
		DisplayStringHead("%Death_var%",~Where are the restrooms ?~)
		ActionOverride("%Death_var%",MoveToPointNoInterrupt([1251.962]))
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #10
		DisplayStringHead("%Death_var%",~What is this place by the way ?~)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #10
		DisplayStringHead("%Death_var%",~I am hungry !~)
		ActionOverride("%Death_var%",MoveToPointNoInterrupt([479.875]))
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #10
		DisplayStringHead("%Death_var%",~...~)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #10
		ActionOverride("%Death_var%",JumpToPoint([1860.1346]))
		Wait(1)
		DisplayStringHead("%Death_var%",~I hate dem Flamin' Fist pansies.~)
		Wait(1)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
END

>>>>>>>>
EXTEND_BOTTOM ~JO2608.bcs~ ~.../JOining_stay_JO2608.baf~ EVALUATE_BUFFER
