// Expand JO_joiW.baf
	// Regular : At BG or SoD end, Travelers go to the switching room and can be recruted again.
		// SoD_Content : At BG end, Travelers with SoD content are destroyself once in the switching room.
			// BG2_Content : At SoD end, Travelers with BG2 content are destroyself once in the switching room.

// For JO_JOINW.baf

// Regular
ACTION_IF (~%Death_var%_SoD_Content~ = 0 ) AND (~%Death_var%_BG2_Content~ = 0 OR NOT GAME_IS ~eet~) THEN BEGIN

		OUTER_SET x_coo = RANDOM(861 1122)
		OUTER_SET y_coo = RANDOM(287 467)

	<<<<<<<< .../JOining_JO2608.baf

	IF
		AreaCheck("JO2608")
		!TriggerOverride("%Death_var%",Global("JO_JOIN_END_OF_WATCH","LOCALS",0))
		!InMyArea("%Death_var%")
	THEN
		RESPONSE #100
			ActionOverride("%Death_var%",SetGlobal("JO_JOIN_END_OF_WATCH","LOCALS",0))
			SetGlobal("JO2608_Create","MYAREA",1)
			MoveGlobal("JO2608","%Death_var%",[%x_coo%.%y_coo%])
			ActionOverride("%Death_var%",SetGlobal("JO_JOIN_HOLD_WATCH","LOCALS",1))
			ReallyForceSpell("%Death_var%",HOLD_PARTY)
			ActionOverride("JO_JOIN_BG1_Container",TakeCreatureItems("%Death_var%",BACKPACK))
			ActionOverride("%Death_var%",RandomWalk())
			Continue()
	END

	>>>>>>>>
	EXTEND_TOP ~JO_JOINW.bcs~ ~.../JOining_JO2608.baf~ EVALUATE_BUFFER

END

// SoD_Content only
ACTION_IF (~%Death_var%_SoD_Content~ = 1) AND (NOT ~%Death_var%_BG2_Content~ = 1 OR NOT GAME_IS ~eet~) THEN BEGIN

		OUTER_SET x_coo = RANDOM(1921 2145)
		OUTER_SET y_coo = RANDOM(1088 1092)


	<<<<<<<< .../JOining_SoD_JO2608.baf

	IF
		AreaCheck("JO2608")
		!TriggerOverride("%Death_var%",Global("JO_JOIN_END_OF_WATCH","LOCALS",0))
		!InMyArea("%Death_var%")
	THEN
		RESPONSE #100
			ActionOverride("%Death_var%",SetGlobal("JO_JOIN_END_OF_WATCH","LOCALS",0))
			SetGlobal("JO2608_Create","MYAREA",1)
			MoveGlobal("JO2608","%Death_var%",[%x_coo%.%y_coo%])
			ActionOverride("%Death_var%",SetGlobal("JO_JOIN_HOLD_WATCH","LOCALS",1))
			ReallyForceSpell("%Death_var%",HOLD_PARTY)
			ActionOverride("JO_JOIN_SoD_Container",TakeCreatureItems("%Death_var%",BACKPACK))
			ActionOverride("%Death_var%",RandomWalk())
			Continue()
	END

	IF
		AreaCheck("JO2608")
		!TriggerOverride("%Death_var%",Global("JO_JOIN_END_OF_BG1","LOCALS",0))
		InMyArea("%Death_var%")
	THEN
		RESPONSE #100
			DisplayStringHead(Player1,~%%Death_var%_name% has heard about the crusade.~)
			SmallWait(2)
			ReallyForceSpell("%Death_var%",NOHOLD_PARTY)
			ActionOverride("%Death_var%",SetGlobal("JO_JOIN_HOLD_WATCH","LOCALS",0))
			ActionOverride("%Death_var%",SetGlobal("JO_JOIN_END_OF_BG1","LOCALS",0))
			ActionOverride("%Death_var%",DestroySelf())
	END

	>>>>>>>>
	EXTEND_TOP ~JO_JOINW.bcs~ ~.../JOining_SoD_JO2608.baf~ EVALUATE_BUFFER


END


// BG2_Content only
ACTION_IF (~%Death_var%_BG2_Content~ = 1 AND NOT ~%Death_var%_SoD_Content~ = 1) AND (GAME_IS ~eet~) THEN BEGIN

		OUTER_SET x_coo = RANDOM(1314 1509)
		OUTER_SET y_coo = RANDOM(1518 1522)


	<<<<<<<< .../JOining_BG2_JO2608.baf

	IF
		AreaCheck("JO2608")
		!TriggerOverride("%Death_var%",Global("JO_JOIN_END_OF_WATCH","LOCALS",0))
		!InMyArea("%Death_var%")
	THEN
		RESPONSE #100
			ActionOverride("%Death_var%",SetGlobal("JO_JOIN_END_OF_WATCH","LOCALS",0))
			SetGlobal("JO2608_Create","MYAREA",1)
			MoveGlobal("JO2608","%Death_var%",[%x_coo%.%y_coo%])
			ActionOverride("%Death_var%",SetGlobal("JO_JOIN_HOLD_WATCH","LOCALS",1))
			ReallyForceSpell("%Death_var%",HOLD_PARTY)
			ActionOverride("JO_JOIN_BG2_Container",TakeCreatureItems("%Death_var%",BACKPACK))
			Continue()
	END

	IF
		AreaCheck("JO2608")
		!TriggerOverride("%Death_var%",Global("JO_JOIN_END_OF_SOD","LOCALS",0))
		InMyArea("%Death_var%")
	THEN
		RESPONSE #100
			DisplayStringHead(Player1,~%%Death_var%_name% has heard about the city of coins.~)
			SmallWait(2)
			ReallyForceSpell("%Death_var%",NOHOLD_PARTY)
			ActionOverride("%Death_var%",SetGlobal("JO_JOIN_HOLD_WATCH","LOCALS",0))
			ActionOverride("%Death_var%",SetGlobal("JO_JOIN_END_OF_SOD","LOCALS",0))
			ActionOverride("%Death_var%",DestroySelf())
	END

	>>>>>>>>
	EXTEND_TOP ~JO_JOINW.bcs~ ~.../JOining_BG2_JO2608.baf~ EVALUATE_BUFFER


END


// SoD and BG2_Content
ACTION_IF (~%Death_var%_BG2_Content~ = 1 AND ~%Death_var%_SoD_Content~ = 1) AND (GAME_IS ~eet~) THEN BEGIN

		OUTER_SET x_coo = RANDOM(1250 1650)
		OUTER_SET y_coo = RANDOM(1110 1120)


	<<<<<<<< .../JOining_BG2_JO2608.baf

	IF
		AreaCheck("JO2608")
		!TriggerOverride("%Death_var%",Global("JO_JOIN_END_OF_WATCH","LOCALS",0))
		!InMyArea("%Death_var%")
	THEN
		RESPONSE #100
			ActionOverride("%Death_var%",SetGlobal("JO_JOIN_END_OF_WATCH","LOCALS",0))
			SetGlobal("JO2608_Create","MYAREA",1)
			MoveGlobal("JO2608","%Death_var%",[%x_coo%.%y_coo%])
			ActionOverride("%Death_var%",SetGlobal("JO_JOIN_HOLD_WATCH","LOCALS",1))
			ReallyForceSpell("%Death_var%",HOLD_PARTY)
			ActionOverride("JO_JOIN_BG2_Container",TakeCreatureItems("%Death_var%",BACKPACK))
			ActionOverride("%Death_var%",RandomWalk())
			Continue()
	END

	IF
		AreaCheck("JO2608")
		!TriggerOverride("%Death_var%",Global("JO_JOIN_END_OF_BG1","LOCALS",0))
		InMyArea("%Death_var%")
	THEN
		RESPONSE #100
			DisplayStringHead(Player1,~%%Death_var%_name% has heard about the crusade.~)
			SmallWait(2)
			ReallyForceSpell("%Death_var%",NOHOLD_PARTY)
			ActionOverride("%Death_var%",SetGlobal("JO_JOIN_HOLD_WATCH","LOCALS",0))
			ActionOverride("%Death_var%",SetGlobal("JO_JOIN_END_OF_BG1","LOCALS",0))
			ActionOverride("%Death_var%",DestroySelf())
	END

	IF
		AreaCheck("JO2608")
		!TriggerOverride("%Death_var%",Global("JO_JOIN_END_OF_SOD","LOCALS",0))
		InMyArea("%Death_var%")
	THEN
		RESPONSE #100
			DisplayStringHead(Player1,~%%Death_var%_name% has heard about the city of coins.~)
			SmallWait(2)
			ReallyForceSpell("%Death_var%",NOHOLD_PARTY)
			ActionOverride("%Death_var%",SetGlobal("JO_JOIN_HOLD_WATCH","LOCALS",0))
			ActionOverride("%Death_var%",SetGlobal("JO_JOIN_END_OF_SOD","LOCALS",0))
			ActionOverride("%Death_var%",DestroySelf())
	END

	>>>>>>>>
	EXTEND_TOP ~JO_JOINW.bcs~ ~.../JOining_BG2_JO2608.baf~ EVALUATE_BUFFER


END


///////////////////////////////////////////////////////////////////////////////

// END_OF_WATCH

///////////////////////////////////////////////////////////////////////////////
// Note :
		// Expand All_in.baf for BG1/SoD npc
			// After Leave Party above
				// Special BG1/SoD end
					// Related to JO_JOIN_CAMPAIGN_TRANSITION in JO_JOINI.baf
///////////////////////////////////////////////////////////////////////////////

//		ACTION_IF ~BG1_%Death_var%_Select~ = 1 OR ~SoD_%Death_var%_Select~ = 1 OR ~Continuous_%Death_var%_Select~ = 1 THEN BEGIN

COPY ~weidu_external/JOining_Party_Select/All_In/%Death_var%_All_In.baf~  ~weidu_external/JOining_Party_Select/All_In/%Death_var%_All_In.baf~ EVALUATE_BUFFER

// For All_in.baf
	REPLACE_TEXTUALLY ~// REPLACE_END_OF_WATCH~ ~~~~~

IF
	AreaCheck("BD0120")
//
	Global("JO_JOIN_CUTSCENE","GLOBAL",0)
	Global("JO_JOIN_LOADING_SWITCH","GLOBAL",0) // Loading switch inactive
	Global("JO_JOIN_CUTSCENE","GLOBAL",0) // No cuscene
	Global("JO_NOJOIN","GLOBAL",0) // No join stop
	Global("JO_JOIN_RETURN_SLOT","GLOBAL",0) // Not implemented
//
//	Global("JO_Myself_LeaveParty","LOCALS",0)
	Global("JO_JOIN_END_OF_WATCH","LOCALS",1)
	Switch("JO_JOIN_TALK_TRANSITION","LOCALS") // Only one traveler say something (Set in JO_JOINI.baf)
THEN
	RESPONSE #0
		SetInterrupt(FALSE)
		MakeGlobalOverride()
		SetGlobal("K#PartySoD","LOCALS",1)
		SetGlobal("JO_JOIN_END_OF_WATCH","LOCALS",2)
		SetGlobal("JO_JOIN_END_OF_BG1","LOCALS",1)
		CreateVisualEffectObject("JOBG402",Myself)
		SetInterrupt(TRUE)
		DestroySelf()
	RESPONSE #1
		SetInterrupt(FALSE)
		DisplayStringHead(Myself,~We will meet again.~)
		MakeGlobalOverride()
		SetGlobal("K#PartySoD","LOCALS",1)
		SetGlobal("JO_JOIN_END_OF_WATCH","LOCALS",2)
		SetGlobal("JO_JOIN_END_OF_BG1","LOCALS",1)
		CreateVisualEffectObject("JOBG402",Myself)
		SetInterrupt(TRUE)
		DestroySelf()
END

IF
	AreaCheck("BD6000")
//
	Global("JO_JOIN_CUTSCENE","GLOBAL",0)
	Global("JO_JOIN_LOADING_SWITCH","GLOBAL",0) // Loading switch inactive
	Global("JO_JOIN_CUTSCENE","GLOBAL",0) // No cuscene
	Global("JO_NOJOIN","GLOBAL",0) // No join stop
	Global("JO_JOIN_RETURN_SLOT","GLOBAL",0) // Not implemented
//
//	Global("JO_Myself_LeaveParty","LOCALS",0)
	Global("JO_JOIN_END_OF_WATCH","LOCALS",1)
	Switch("JO_JOIN_TALK_TRANSITION","LOCALS") // Only one traveler say something (Set in JO_JOINI.baf)
THEN
	RESPONSE #0
		SetInterrupt(FALSE)
		MakeGlobalOverride()
		SetGlobal("K#PartySoD","LOCALS",1)
		SetGlobal("JO_JOIN_END_OF_WATCH","LOCALS",2)
		SetGlobal("JO_JOIN_END_OF_SOD","LOCALS",1)
		CreateVisualEffectObject("JOBG402",Myself)
		SetInterrupt(TRUE)
		DestroySelf()
	RESPONSE #1
		SetInterrupt(FALSE)
		MakeGlobalOverride()
		DisplayStringHead(Myself,~Gonna make a diversion, the Flamming Fist will search for you everywhere...~)
		SetGlobal("K#PartySoD","LOCALS",1)
		SetGlobal("JO_JOIN_END_OF_WATCH","LOCALS",2)
		SetGlobal("JO_JOIN_END_OF_SOD","LOCALS",1)
		CreateVisualEffectObject("JOBG402",Myself)
		SetInterrupt(TRUE)
		DestroySelf()
END


	%c#ebg122_END_OF_WATCH%

~~~~~

//		END

// For JO2608AL.baf
	// Avatar of Alaundo
<<<<<<<< .../JOining_stay_JO2608AL.baf

IF
	See(Player1)
	AreaCheck("JO2608")
	InMyArea("%Death_var%")
	!Dead("%Death_var%")
	TriggerOverride(Player1,Global("JO_JOIN_JUMP_JO2608","LOCALS",0))
	!TriggerOverride("%Death_var%",Global("JO_JOIN_HOLD_WATCH","LOCALS",0))
	Global("JO2608_Create","MYAREA",0)
THEN
	RESPONSE #100
		ReallyForceSpell("%Death_var%",NOHOLD_PARTY)
		ActionOverride("%Death_var%",SetGlobal("JO_JOIN_HOLD_WATCH","LOCALS",0))
		Continue()
END

IF
	Global("JO_Myself_AllowDead","LOCALS",0)
	InMyArea([PC])
	AreaCheck("JO2608")
	InMyArea("%Death_var%")
	!Dead("%Death_var%")
	Global("JO_JOIN_GATHER_JO2608","MYAREA",1)
	TriggerOverride("%Death_var%",Global("JO_JOIN_SEE_JO2608AL","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride("%Death_var%",SetGlobal("JO_JOIN_SEE_JO2608AL","LOCALS",1)
		ActionOverride("%Death_var%",MoveToObjectNoInterrupt("JO2608AL"))
		Continue()
END

IF
	Global("JO_Myself_AllowDead","LOCALS",0)
	InMyArea([PC])
	AreaCheck("JO2608")
	InMyArea("%Death_var%")
	!Dead("%Death_var%")
	TriggerOverride("%Death_var%",Global("JO_JOIN_SEE_JO2608AL","LOCALS",2))
	TriggerOverride("%Death_var%",See("JO2608AL"))
THEN
	RESPONSE #100
		ActionOverride("%Death_var%",SetGlobal("JO_JOIN_SEE_JO2608AL","LOCALS",3)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
END

IF
	Global("JO_Myself_AllowDead","LOCALS",0)
	InMyArea([PC])
	AreaCheck("JO2608")
	InMyArea("%Death_var%")
	!Dead("%Death_var%")
	TriggerOverride("%Death_var%",Global("JO_JOIN_SEE_JO2608AL","LOCALS",3))
	OR(2)
		!TriggerOverride("%Death_var%",See("JO2608AL"))
		Global("JO_JOIN_GATHER_JO2608","MYAREA",0)
THEN
	RESPONSE #100
		ActionOverride("%Death_var%",SetGlobal("JO_JOIN_SEE_JO2608AL","LOCALS",0)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
END

>>>>>>>>
EXTEND_BOTTOM ~JO2608AL.bcs~ ~.../JOining_stay_JO2608AL.baf~ EVALUATE_BUFFER


// For JO2608.baf
<<<<<<<< .../JOining_stay_JO2608.baf

IF
	Global("JO_Myself_AllowDead","LOCALS",0)
	InMyArea([PC])
	Global("JO_JOIN_LOADING_SWITCH","GLOBAL",0)
	InMyArea("%Death_var%")
	!Dead("%Death_var%")
	Global("JO2608_Create","MYAREA",0)
	RandomNum(30,5)
	!GlobalTimerNotExpired("JO_JOIN_STAY_JO2608","LOCALS")
THEN
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		ActionOverride("%Death_var%",VerbalConstant(Myself,TIRED))
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		DisplayStringHead("%Death_var%",~Don't expect me to do the dishes.~)
		ActionOverride("%Death_var%",MoveToPointNoInterrupt([253.823]))
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		ActionOverride("%Death_var%",MoveToObjectNoInterrupt([PC]))
		ActionOverride("%Death_var%",ApplySpell([PC],RESTORE_FULL_HEALTH))
		Wait(3)
		DisplayStringHead("%Death_var%",~Here you go.~)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		ActionOverride("%Death_var%",RandomTurn())
		DisplayStringHead("%Death_var%",~What about now ?~)
		Wait(2)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		ActionOverride("%Death_var%",VerbalConstant(Myself,INITIAL_MEETING))
		Wait(2)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		ActionOverride("%Death_var%",MoveToObjectNoInterrupt([PC]))
		ActionOverride("%Death_var%",ApplySpell([PC],CLERIC_NEUTRALIZE_POISON))
		Wait(3)
		DisplayStringHead("%Death_var%",~Here you go.~)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		DisplayStringHead("%Death_var%",~Ha ha... Ha ha ha...~)
		Wait(4)
		DisplayStringHead("%Death_var%",~HAHAHAHAAAAAAAAH !~)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		DisplayStringHead("%Death_var%",~Good on you if you save the day. I care not, for I am gone !~)
		ActionOverride("%Death_var%",MoveToPointNoInterrupt([1860.1346]))
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		ActionOverride("%Death_var%",VerbalConstant(Myself,HAPPY))
		Wait(2)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		DisplayStringHead("%Death_var%",~I have nothing else to do...~)
		ActionOverride("%Death_var%",MoveToPointNoInterrupt([1655.666]))
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		ActionOverride("%Death_var%",MoveToObjectNoInterrupt([PC]))
		ActionOverride("%Death_var%",ApplySpell([PC],CLERIC_RESTORATION))
		Wait(3)
		DisplayStringHead("%Death_var%",~Here you go.~)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		ActionOverride("%Death_var%",MoveToObjectNoInterrupt([ANYONE]))
		Wait(5)
		ActionOverride("%Death_var%",VerbalConstant(Myself,MORALE))
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		DisplayStringHead("%Death_var%",~Eh. Onward, to futility !~)
		Wait(1)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		DisplayStringHead("%Death_var%",~You are too sensitive !~)
		Wait(1)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		ActionOverride("%Death_var%",MoveToObjectNoInterrupt([PC]))
		ActionOverride("%Death_var%",ApplySpell([PC],WIZARD_REMOVE_CURSE))
		Wait(3)
		DisplayStringHead("%Death_var%",~Here you go.~)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		ActionOverride("%Death_var%",VerbalConstant(Myself,BORED))
		Wait(2)
		ActionOverride("%Death_var%",ApplySpell(Myself,CLERIC_DETECT_EVIL))
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		DisplayStringHead("%Death_var%",~Whatever...~)
		Wait(10)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		ActionOverride("%Death_var%",RandomTurn())
		DisplayStringHead("%Death_var%",~Where are the restrooms ?~)
		ActionOverride("%Death_var%",MoveToPointNoInterrupt([1251.962]))
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		ActionOverride("%Death_var%",MoveToObjectNoInterrupt([PC]))
		ActionOverride("%Death_var%",ApplySpell([PC],WIZARD_MINOR_GLOBE_OF_INVULNERABILITY))
		Wait(3)
		DisplayStringHead("%Death_var%",~Here you go.~)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		ActionOverride("%Death_var%",MoveToObjectNoInterrupt([ANYONE]))
		Wait(5)
		ActionOverride("%Death_var%",VerbalConstant(Myself,BATTLE_CRY1))
		Wait(1)
		ActionOverride("%Death_var%",SetSequence(SEQ_ATTACK))
		Wait(1)
		ActionOverride([ANYONE],SetSequence(SEQ_DAMAGE))
		ActionOverride([ANYONE],VerbalConstant(Myself,DAMAGE))
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		DisplayStringHead("%Death_var%",~What is this place by the way ?~)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		ActionOverride("%Death_var%",MoveToObjectNoInterrupt([ANYONE]))
		Wait(3)
		ActionOverride("%Death_var%",VerbalConstant(Myself,INSULT2))
		Wait(3)
		ActionOverride([ANYONE],VerbalConstant(Myself,UNHAPPY_BREAKING_POINT))
		ActionOverride("%Death_var%",ApplySpell(Myself,WIZARD_HASTE))
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		ActionOverride("%Death_var%",MoveToObjectNoInterrupt([ANYONE]))
		Wait(2)
		DisplayStringHead("%Death_var%",~You be quiet !~)
		ActionOverride("%Death_var%",ApplySpell(Myself,CLERIC_SILENCE_15_FOOT))
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		ActionOverride("%Death_var%",MoveToObjectNoInterrupt([PC]))
		ActionOverride("%Death_var%",ApplySpell([PC],WIZARD_PROTECTION_FROM_PETRIFICATION))
		Wait(3)
		DisplayStringHead("%Death_var%",~Here you go.~)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		ActionOverride("%Death_var%",VerbalConstant(Myself,SELECT_COMMON1))
		Wait(2)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		DisplayStringHead("%Death_var%",~I am hungry !~)
		ActionOverride("%Death_var%",MoveToPointNoInterrupt([479.875]))
		ActionOverride("%Death_var%",ApplySpell(Myself,CLERIC_GOOD_BERRIES))
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		ActionOverride("%Death_var%",MoveToObjectNoInterrupt([ANYONE]))
		Wait(3)
		ActionOverride("%Death_var%",VerbalConstant(Myself,INSULT1))
		Wait(2)
		ActionOverride([ANYONE],SetSequence(SEQ_HEAD_TURN))
		Wait(3)
		ActionOverride([ANYONE],VerbalConstant(Myself,RESPONSE_TO_INSULT1))
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		DisplayStringHead("%Death_var%",~...~)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		DisplayStringHead("%Death_var%",~Parlez plus fort, plus fort !~)
		Wait(1)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		ActionOverride("%Death_var%",VerbalConstant(Myself,SELECT_ACTION1))
		Wait(2)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		ActionOverride("%Death_var%",VerbalConstant(Myself,SELECT_RARE1))
		Wait(2)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		DisplayStringHead("%Death_var%",~A Switching room... An absurdity !~)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		ActionOverride("%Death_var%",VerbalConstant(Myself,SELECT_RARE2))
		Wait(2)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		ActionOverride("%Death_var%",JumpToPoint([1860.1346]))
		Wait(1)
		DisplayStringHead("%Death_var%",~I hate dem Flamin' Fist pansies.~)
		Wait(1)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		ActionOverride("%Death_var%",MoveToObjectNoInterrupt([ANYONE]))
		Wait(3)
		ActionOverride("%Death_var%",VerbalConstant(Myself,COMPLIMENT1))
		Wait(2)
		ActionOverride([ANYONE],SetSequence(SEQ_HEAD_TURN))
		Wait(3)
		ActionOverride([ANYONE],VerbalConstant(Myself,RESPONSE_TO_COMPLIMENT1))
		Continue()
	RESPONSE #2
		SetGlobalTimer("JO_JOIN_STAY_JO2608","LOCALS",FOUR_TURNS)
		DisplayStringHead("%Death_var%",~I am happy not. No, I'm not.~)
		ActionOverride("%Death_var%",RandomWalk())
		Continue()
END

>>>>>>>>
EXTEND_BOTTOM ~JO2608.bcs~ ~.../JOining_stay_JO2608.baf~ EVALUATE_BUFFER
