

///////////////////////////////////////////////////////////////////////////////

// JO_JOIN_JUMP_JO2608

///////////////////////////////////////////////////////////////////////////////
// Note :
	// Jump to JO2608 to perform area script after traveler leave for transition
		// Related to JO_JOIN_CAMPAIGN_TRANSITION (Jo_joinI / All_in)
///////////////////////////////////////////////////////////////////////////////

// To EXTEND_TOP at the end
IF
	Global("JO_JOIN_JUMP_JO2608","LOCALS",1)
THEN
	RESPONSE #100
		StoreZoomLevel()
		StorePartyLocations()
		SetGlobal("JO_JOIN_JUMP_JO2608","LOCALS",2)
		FadeFromColor([50.0],0)
		LeaveAreaLUA("JO2608","",[1232.891],1)
		SetZoomViewport([2357.1646])
		MoveViewObject(Player1,INSTANT)
END
