

///////////////////////////////////////////////////////////////////////////////

// JO_JOIN_JUMP_JO2608

///////////////////////////////////////////////////////////////////////////////
// Note :
	// Jump to JO2608 to perform area script after traveler leave for transition
		// Related to JO_JOIN_CAMPAIGN_TRANSITION (Jo_joinI / All_in)
///////////////////////////////////////////////////////////////////////////////

// To EXTEND_TOP at the end
IF
	Global("JO_JOIN_JUMP_JO2608","LOCALS",1)
THEN
	RESPONSE #100
		StorePartyLocations()
		SetGlobal("JO_JOIN_JUMP_JO2608","LOCALS",2)
		DisplayStringHead(Myself,~I wonder if idle travelers will wait in the switching room...~)
		FadeFromColor([30.0],0)
		LeaveAreaLUA("JO2608","",[1232.891],1)
END
