

///////////////////////////////////////////////////////////////////////////////

// JO_JOIN_JUMP_JO2608

///////////////////////////////////////////////////////////////////////////////
// Note :
	// Jump to JO2608 to perform area script after traveler leave for transition
		// Related to JO_JOIN_CAMPAIGN_TRANSITION (Jo_joinI / All_in)
///////////////////////////////////////////////////////////////////////////////

IF
//
	AreaCheck("JO2608")
	Global("JO2608_Create","LOCALS",1)
THEN
	RESPONSE #100
		FadeToColor([45.0],0)
		SetGlobal("JO_JOIN_JUMP_JO2608","LOCALS",2)
		AddMapNote([1894.1155],~Travelers Items~)
		DisplayStringHead(Myself,~Hum...~)
		Wait(2)
		SetGlobal("JO2608_Create","LOCALS",2)
END

IF
//
	AreaCheck("JO2608")
	Global("JO2608_Create","LOCALS",2)
	Global("JO_JOIN_JUMP_JO2608","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("JO_JOIN_NOHOLD_JO2608","MYAREA",1)
		SetGlobal("JO_JOIN_JUMP_JO2608","LOCALS",3)
		ChangeAIScript("JO_JOINP",OVERRIDE)
END
