
/////////////////////////// Mods BG1 ///////////////////////////

////////////////////////////////////////////////////


// BG1

IF
	Global("JO_JOIN","LOCALS",2)
	Global("JO_JOIN_CAMPAIGN","GLOBAL",1)
THEN
	RESPONSE #100
		SetDialog("%BG1_JOINED%")
		SmallWait(1)
		SetGlobal("JO_JOIN","LOCALS",0)
//		ChangeAIScript("%BG1_BCS%",OVERRIDE)
END

 // SoD

IF
	Global("JO_JOIN","LOCALS",2)
	Global("JO_JOIN_CAMPAIGN","GLOBAL",2)
THEN
	RESPONSE #100
		SetDialog("%SoD_JOINED%")
		SmallWait(1)
		SetGlobal("JO_JOIN","LOCALS",0)
//		ChangeAIScript("%SoD_BCS%",OVERRIDE)
END

////////////////////////////////////////////////////

////////////////////////////////////////////////////


// Yeah Start ( Switch between familiar and party)

IF
	Allegiance(Myself,FAMILIAR)
	Global("JO_JOIN","LOCALS",0)
	Global("JO_JOIN_CLEAR","LOCALS",1)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,~Yeah.~)
		SetGlobal("JO_JOIN_CLEAR","LOCALS",2)
		Continue() // Go to Yeah End
END

///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////

// Yeah End (End Switch between familiar and party)

IF
	Allegiance(Myself,FAMILIAR)
	Global("JO_JOIN_CLEAR","LOCALS",2)
THEN
	RESPONSE #100
		ChangeAIScript("JO_JOINX",RACE)// Go to JO_JOINX (ScriptAction / XP)
		SetGlobal("JO_JOIN_CLEAR","LOCALS",3)
END

///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
