/*
*/

/////////////////////////// Mods BG1 ///////////////////////////

ACTION_IF (GAME_IS ~bgee eet~) BEGIN // BG1
		OUTER_SPRINT "RESPONSE_BG1" ~~~~~RESPONSE #1
				SetDialog("%BG1_JOINED%")
				SmallWait(1)
				SetGlobal("JO_JOIN","LOCALS",0)
		//		ChangeAIScript("%BG1_BCS%",OVERRIDE)
				Continue()~~~~~
END ELSE BEGIN
		OUTER_SPRINT "RESPONSE_BG1" ""
END
ACTION_IF (GAME_INCLUDES ~SoD~) BEGIN // SoD
		OUTER_SPRINT "RESPONSE_SoD" ~~~~~RESPONSE #2
				SetDialog("%SoD_JOINED%")
				SmallWait(1)
				SetGlobal("JO_JOIN","LOCALS",0)
		//		ChangeAIScript("%SoD_BCS%",OVERRIDE)
				Continue()~~~~~
END ELSE BEGIN
		OUTER_SPRINT "RESPONSE_SoD" ""
END
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN // BG2 / ToB
		OUTER_SPRINT "RESPONSE_BG2" ~~~~~RESPONSE #3
				SetDialog("%BG1_JOINED%")
				SmallWait(1)
				SetGlobal("JO_JOIN","LOCALS",0)
		//		ChangeAIScript("%BG1_BCS%",OVERRIDE)
				Continue()
			RESPONSE #4
				SetDialog("%BG1_JOINED%")
				SmallWait(1)
				SetGlobal("JO_JOIN","LOCALS",0)
		//		ChangeAIScript("%BG1_BCS%",OVERRIDE)
				Continue()~~~~~
END ELSE BEGIN
		OUTER_SPRINT "RESPONSE_BG2" ""
END
ACTION_IF (GAME_IS ~eet~) BEGIN // BG1 / EET
		OUTER_SPRINT "RESPONSE_EET" ~~~~~RESPONSE #5
				SetDialog("%BG1_JOINED%")
				SmallWait(1)
				SetGlobal("JO_JOIN","LOCALS",0)
		//		ChangeAIScript("%BG1_BCS%",OVERRIDE)
				Continue()~~~~~
END ELSE BEGIN
		OUTER_SPRINT "RESPONSE_EET" ""
END

<<<<<<<< .../JOining_mod_bg1.baf

IF
	Global("JO_JOIN","LOCALS",2)
	Switch("JO_JOIN_CAMPAIGN","GLOBAL")
THEN
%RESPONSE_BG1%
%RESPONSE_SoD%
%RESPONSE_BG2%
%RESPONSE_EET%
END

>>>>>>>>
EXTEND_BOTTOM ~%bcs%.bcs~ ~.../JOining_mod_bg1.baf~ EVALUATE_BUFFER

////////////////////////////////////////////////////

/*

///////////////////////////////////////////////////////////////////////////////

// Leave Party

///////////////////////////////////////////////////////////////////////////////

IF
	Global("JO_JOIN_LOADING_SWITCH","GLOBAL",0) // Don't use this block at loading
	Global("JO_JOIN_RETURN_SLOT","GLOBAL",0)
	Global("JO_JOIN_SWITCHING_PARTY","GLOBAL",0)
//
	!Global("JO_Myself_LeaveParty","LOCALS",0)
	!Global("JO_Myself_Valid","LOCALS",0)
	!Global("JO_JOIN_IS_TRAVELER","LOCALS",0)
	Switch("JO_JOIN_CAMPAIGN","GLOBAL")
THEN
	RESPONSE #1
		SetGlobal("JO_JOIN_QUICK_NEVER_JOIN","LOCALS",0)
		SetGlobal("JO_JOIN_NEVER_SWITCH","LOCALS",0)
		SetGlobal("JO_TRAVELER_Myself","LOCALS",0)
		SetGlobal("JO_TRAVELER_%Death_var%","GLOBAL",0)
		SetGlobal("JO_JOIN_IS_TRAVELER","LOCALS",0)
		SetGlobal("JO_JOIN_IS_JOINING","LOCALS",0)
		SetGlobal("JO_JOIN","LOCALS",0)
		SetGlobal("JO_JOINI","LOCALS",0)
		SetGlobal("JO_JOIN_Move_Done","LOCALS",0)
		EquipItemEx("JOMINHP1",1)
		SmallWait(1)
		DestroyItem("JOMINHP1")
		SmallWait(1)
		RemoveFamiliar()
//
		SetDialog("%LEAVE_DIALOG_NAME_BG1%")
//		ChangeAIScript("%BG1_BCS%",OVERRIDE)
		SetGlobal("JO_Myself_LeaveParty","LOCALS",0)
		Continue()
	RESPONSE #2
		SetGlobal("JO_JOIN_QUICK_NEVER_JOIN","LOCALS",0)
		SetGlobal("JO_JOIN_NEVER_SWITCH","LOCALS",0)
		SetGlobal("JO_TRAVELER_Myself","LOCALS",0)
		SetGlobal("JO_TRAVELER_%Death_var%","GLOBAL",0)
		SetGlobal("JO_JOIN_IS_TRAVELER","LOCALS",0)
		SetGlobal("JO_JOIN_IS_JOINING","LOCALS",0)
		SetGlobal("JO_JOIN","LOCALS",0)
		SetGlobal("JO_JOINI","LOCALS",0)
		SetGlobal("JO_JOIN_Move_Done","LOCALS",0)
		EquipItemEx("JOMINHP1",1)
		SmallWait(1)
		DestroyItem("JOMINHP1")
		SmallWait(1)
		RemoveFamiliar()
//
		SetDialog("%LEAVE_DIALOG_NAME_SOD%")
//		ChangeAIScript("%SoD_BCS%",OVERRIDE)
		SetGlobal("JO_Myself_LeaveParty","LOCALS",0)
		Continue()
	RESPONSE #3
		SetGlobal("JO_JOIN_QUICK_NEVER_JOIN","LOCALS",0)
		SetGlobal("JO_JOIN_NEVER_SWITCH","LOCALS",0)
		SetGlobal("JO_TRAVELER_Myself","LOCALS",0)
		SetGlobal("JO_TRAVELER_%Death_var%","GLOBAL",0)
		SetGlobal("JO_JOIN_IS_TRAVELER","LOCALS",0)
		SetGlobal("JO_JOIN_IS_JOINING","LOCALS",0)
		SetGlobal("JO_JOIN","LOCALS",0)
		SetGlobal("JO_JOINI","LOCALS",0)
		SetGlobal("JO_JOIN_Move_Done","LOCALS",0)
		EquipItemEx("JOMINHP1",1)
		SmallWait(1)
		DestroyItem("JOMINHP1")
		SmallWait(1)
		RemoveFamiliar()
//
		SetDialog("%LEAVE_DIALOG_NAME_BG2%")
//		ChangeAIScript("%BG2_BCS%",OVERRIDE)
		SetGlobal("JO_Myself_LeaveParty","LOCALS",0)
		Continue()
	RESPONSE #4
		SetGlobal("JO_JOIN_QUICK_NEVER_JOIN","LOCALS",0)
		SetGlobal("JO_JOIN_NEVER_SWITCH","LOCALS",0)
		SetGlobal("JO_TRAVELER_Myself","LOCALS",0)
		SetGlobal("JO_TRAVELER_%Death_var%","GLOBAL",0)
		SetGlobal("JO_JOIN_IS_TRAVELER","LOCALS",0)
		SetGlobal("JO_JOIN_IS_JOINING","LOCALS",0)
		SetGlobal("JO_JOIN","LOCALS",0)
		SetGlobal("JO_JOINI","LOCALS",0)
		SetGlobal("JO_JOIN_Move_Done","LOCALS",0)
		EquipItemEx("JOMINHP1",1)
		SmallWait(1)
		DestroyItem("JOMINHP1")
		SmallWait(1)
		RemoveFamiliar()
//
		SetDialog("%LEAVE_DIALOG_NAME_TOB%")
//		ChangeAIScript("%TOB_BCS%",OVERRIDE)
		SetGlobal("JO_Myself_LeaveParty","LOCALS",0)
		Continue()
END
*/