///////////////////////////////////////////////////////////////////////////////////

// For party member After Main Loading Switch 3 // Special non-traveler NPCs

IF // The party member making room for traveler Loading Switch if the party is full reintegrate the party right after
//
	!Global("JO_JOIN_LOADING_PLAYER","LOCALS",0) // Is deactivated
	OR(2)
		NumInPartyGT(3)
		Global("JO_JOIN_LOADING_PLAYER","LOCALS",1) // Is deactivated
	OR(3)
		NumInPartyGT(4)
		Global("JO_JOIN_LOADING_PLAYER","LOCALS",2) // Is deactivated
		Global("JO_JOIN_LOADING_PLAYER","LOCALS",1) // Is deactivated
	OR(2)
		GlobalGT("JO_JOIN_LOADING_SWITCH","GLOBAL",3) // Loading switch "almost" finished
		Global("JO_JOIN_LOADING_SWITCH","GLOBAL",0) // Broken cutscene
//
	NumInPartyLT(6)
THEN
	RESPONSE #100
		ActionOverride(Player1,IncrementGlobal("JO_JOIN_LOADING_PLAYER","LOCALS",-1))
		SetGlobal("JO_JOIN_LOADING_PLAYER","LOCALS",0)
		Activate(Myself)
		DisplayStringHead(Myself,~I'm back !~)
		JoinParty()
		ChangeAIScript("",GENERAL)
		Continue()
END
