// JO_LOAD_JO_JOINL.BAF Loading Switch script for Player1
	// EXTEND_TOP for JO_JOINL.BAF at installation by JOining_Party_Select_Core.tph

///////////////////////////////////////////////////////////////////////////////
// Variables :
	// JO_JOIN_LOAD (Used by Charname to slow down the script execution)
///////////////////////////////////////////////////////////////////////////////

// Main 2 // After JO_JOINP.baf Main 1 // Loading Switch


