
	ACTION_FOR_EACH crecomp IN

// Continuous_comp
~%DORN_CRE%~
~%NEERA_CRE%~
~%RASAAD_CRE%~
~%BAELOTH_CRE%~
~%CLARA_CRE%~
~%HEXXAT_CRE%~



/////////////////////////// Mods BG1 ///////////////////////////

// Ishlilka_The-Wizard-Slayer
// Mod Ishlilka                  ~#Ishy~                                             // Ishlilka

// ChaosKnight-kit
// Mod Jacob                     ~ZYCHAOS~                                           // Jacob

// Askaria-Quest
// Mod Askaria                   ~ZYASKA~                                            // Askaria

// Isra BG1
// Mod Isra_BG1                  ~rh#isra~                                           // Isra

// Finch
// Mod Finch                     ~SUFINCH1~                                          // Finch

// Drizzt Saga
// Mod Jarlaxle_Saga             ~F_JARLAX~                                          // Jarlaxle
// Mod Artemis_Enteri_Saga       ~F_ARTEMI~                                          // Artemis Enteri
// Mod Catti-Brie_Saga           ~F_CATTIB~                                          // Catti-Brie
// Mod Bruenor_Saga              ~F_BRUENO~                                          // Bruenor
// Mod Regis_Saga                ~F_REGIS2~                                          // Regis
// Mod Drizzt_Saga               ~F_DRIZZT~                                          // Drizzt
// Mod Wulfgar_Saga              ~F_WULFGA~                                          // Wulfgar

// Dark Horizons
// Mod Thorin                    ~CMTTHOR~                                           // Thorin
// Mod Morwen                     ~CMTMORW~                                          // Morwen

// DSotSC
// Mod Bardo                     ~DSBARDO~                                           // Bardo
// Mod Bub_Snikt                 ~DSBUB~                                             // Bub Snikt
// Mod Conchobhair               ~DSCONCH~                                           // Conchobhair
// Mod CuChoinneach              ~DSCUCHO~                                           // CuChoinneach
// Mod Ferthgil_Trollslayer      ~DSFERTH~                                           // Ferthgil Trollslayer
// Mod Jet'laya                  ~DSJETLA~                                           // Jet'laya
// Mod Keiria_Silverstring       ~DSKEIRI~                                           // Keiria Silverstring
// Mod Skeezer_Lumpkin_VI        ~DSSKEEZ~                                           // Skeezer Lumpkin VI
// Mod Thorfinn_Hauskluniff      ~DSTHORF~                                           // Thorfinn Hauskluniff

// NTotSC
// Mod Will_Scarlet              ~NTWILL2~                                           // Will Scarlet

// Valerie
// Mod Valerie                   ~T2VAL~

// Indira
// Mod Indira                    ~J#INDI01~

// Bristlelick BG1 / SoD
// Mod Bristlelick               ~L#BRIST~

// Glam's npc pack
// Mod Dave                      ~GV#DAVE~
// Mod Flara                     ~GV#FLAR~
// Mod Littlun                   ~GV#LITT~
// Mod Moidre                    ~GV#MOID~
// Mod Vynd                      ~GV#VYND~

// Kale BG1
// Mod Kale_BG1                  ~X3Kale~

// New Tales of the Sword Coast
// Mod Kasandra                  ~Kasandra~
// Mod Masambe                   ~Masambe~
// Mod Alethra                   ~Alethra~
// Mod Rimardo                   ~Rimardo~
// Mod Talindra                  ~Talindra~
// Mod Theodor                   ~Theodor~
// Mod Ariadne                   ~Ariadne~
// Mod Nathan                    ~Nathan~
// Mod Namiir                    ~Namiir~
// Mod Miranda                   ~Miranda~

// Walahnan BG1 / SoD
// Mod Walahnan_BG1              ~L#WALAH~

// Aerie in BG:EE
// Mod Aerie_BG1                 ~B2#Aeri~

// Margarita Zelleod
// Mod Margarita                 ~RL#MARG~

// Verr'sza BG1
// // Mod Verr'sza_BG1              ~L#1verr1~ // Statue cannot run script

// Next_Traveler BG1


/////////////////////////// Mods BG2 ///////////////////////////

// Alora BG2
// Mod Alora BG2                 ~ALORA09~                                          // Alora

// Yeslick BG2
// Mod Yeslick BG2               ~LK#YESL~                                         // Yeslick

// The Undying
// Mod Undying                   ~CMNINAF9~                                          // Ninafer
// Mod Undying                   ~CMCALLI~                                         // Callisto

// Summon Bhaalspawn
// Mod Sandra                    ~BHAALSPW~                                         // Sandra

// VampireTales
// Mod Miriam                    ~CMGMIRI~                                        // Miriam

// Kim
// Mod Kim                       ~KIM~                                              // Kim

// Severian
// Mod Severian                  ~#SEVER~                                        // Severian

// Frennedan
// Mod Frennedan                 ~SHAPE~                                        // Frennedan

// Branwen BG2
// Mod Branwen_BG2               ~O#Bran~                                           // Branwen
// Tiax BG2
// Mod Tiax_BG2                  ~O#Tiax~                                           // Tiax
// Xan BG2
// Mod Xan_BG2                   ~O#XAN09~                                            // Xan
// Coran BG2
// Mod Coran_BG2                 ~O#Coran~                                          // Coran

// Auren Aseph
// Mod Auren                     ~AUREN~                                  // Auren

// Isra BG2
// Mod Isra_BG2                  ~RH#ISR~                                 // Isra

// Nephele
// Mod Nephele_Samios            ~LK#NEPH~                                  // Nephele

// Sheena
// Mod Sheena                    ~K#SHEENA~                                 // Sheena

// Kiara / Zaiya
// Mod Kiara                     ~KIARA~                                    // Kiara
// Mod Zaiya                     ~ZAIYA~                                    // Zaiya

// The Beaurin Legacy
// Mod Minyae                    ~MINYAE~                                    // Minyae
// Mod Elaryn                    ~QI#ELA~                                   // Elaryn

// Tyris Flare
// Mod Tyris                     ~G#TYRS8~                                  // Tyris

// Region of Terror
// Mod Wulfgar_Terror            ~WULFG2~                                   // Wulfgar
// Mod Regis_Terror              ~REG2~                                     // Regis
// Mod Drizzt_Terror             ~DRIZ21~                                    // Drizz
// Mod Bruenor_Terror            ~BRUE2~                                    // Bruenor
// Mod Catti-Brie_Terror         ~CATT2~                                    // Catti-Brie
// Mod Artemis_Entreri_Terror    ~ENTER2~                                   // Artemis
// Mod Jarlaxle_Terror           ~JARLAX2~                                  // Jarlaxle
// Mod Tapio_Perkiomaki_Terror   ~TAPIO~                                    // Tapio
// Mod Randall_Terror            ~RANDALL1~                                  // Randall
// Mod Alissa_Terror             ~ALISSA8~                                  // Alissa
// Mod Mordragon_Terror          ~MORDRG1~                                   // Mordragon

//Shadow over Soubar
// Mod Selence_Hillstar_Soubar   ~SELENC07~                                  // Selence
// Mod Charlotte_Soubar          ~CHARLO09~                                 // Charlotte
// Mod Bolivar_Soubar            ~BOLIVR09~                                  // Bolivar
// Mod Tomas_Tomalson_Soubar     ~TOMAST11~                                  // Tomas

// ajantisbg2
// Mod Ajantis_BG2               ~C#AJAN08~                                // Ajantis

// Kivan and Deheriana
// Mod Kivan_BG2                 ~P#KIVAN~                                  // Kivan
// Mod Deheriana                 ~P#DEHER~                                  // Deheriana

// Yvette
// Mod Yvette                    ~YXYVE1~

// The Luxley Family
// Mod Sebastian                ~FHLSEB08~
// Mod Andrei                   ~FHLAND07~

//  Beyond the Law
// Mod Kiyone                   ~KIYONE~
// Mod Kova                     ~KOVA~

// Petsy
// Mod Petsy                   ~L3PETSY~

// Kale BG2
// Mod Kale_BG2                ~X3KAL~

// Walahnan BG2
// Mod Walahnan_BG2            ~L#2WH~

// Autumns Twilight
// Mod Dusk                    ~P_DUSK~
// Mod Fall                    ~P_FALL~
// Mod Cho'Nuja                ~P_CHON~
// Mod Alendir                 ~P_ALEN~

// Lysre, dragonne de poche
// Mod Lysre                   ~CKLYSRE~

// Tashia
// Mod Tashia                  ~TASHIA~

// Dace Linton
// Mod Dace                    ~T#DACE8~

// Amber
// Mod Amber                   ~m#ambr10~

// Evandra
// Mod Evandra                 ~rh#eva~

// Lena
// Mod Lena                    ~EU#Lena9~

// Paina
// Mod Pai'Na                  ~sppain~

// Verr'sza BG2
// Mod Verr'sza_BG2           ~L#2verr~
// Mod Phalh                  ~L#2phal~

// Saradas magic for BG2
// Mod Saradas                ~!sartob~

// Varshoon
// Mod Varshoon               ~VxVar01~

// Skie the Cost of One girl Soul
// Mod Skie                   ~l#2sdski~
// Mod Eddard                 ~l#2eddrd~

// Anishai
// Mod Anishai                ~Anishai~

// Will of the Wisps
// Mod WispWill               ~L0will~

// Angelo
// Mod Angelo                 ~ADANGEL~

// Adrian
// Mod Adrian                 ~RH#ADR~

// Hubelpot the Vegetable Merchant
// Mod Hubelpot               ~sc#hub~

// Next_Traveler BG2


/////////////////////////// Mods Continuous ///////////////////////////

// EET Nikita                  ~cmnikita~                                   // Nikita

// EET Walahnan_Continuous     ~L#WALAH~                                   // Walahnan_Continuous

// EET Isra_Continuous         ~rh#isra~                                  // Isra_Continuous

// Ascalon's Breagar
// // Mod Breagar                 ~ACBRE~ // Breagar not for BG2 should not be a problem

// EET Region_of_Terror_Continuous     ~F_JARLAX~ ~F_ARTEMI~ ~F_CATTIB~ ~F_BRUENO~ ~F_REGIS2~ ~F_DRIZZT~ // ~F_WULFGA~ // Wulfgar not for BG2

// Next_Traveler Continuous


	BEGIN


		ACTION_IF FILE_EXISTS_IN_GAME ~%crecomp%.cre~ BEGIN

				COPY_EXISTING ~%crecomp%.cre~  ~override~
					READ_ASCII 0x248 override_script_comp
//					READ_ASCII 0x268 Default_script_comp
//					READ_ASCII 0x260 general_script_comp
					READ_ASCII 0x280 DeathVar_comp (32) NULL
/*
					PATCH_IF (~%Default_script_comp%~ STRING_EQUAL_CASE ~~) BEGIN
							OUTER_SPRINT "DEFAULT" ~script_comp~
					END ELSE PATCH_IF (~%general_script_comp%~ STRING_EQUAL_CASE ~~) BEGIN
							OUTER_SPRINT "GENERAL" ~script_comp~
								WRITE_ASCII SCRIPT_GENERAL ~JOINSETG~ (8)
					END // PATCH_IF (~%Default_script_comp%~ STRING_EQUAL_CASE ~~)
*/
			INNER_ACTION BEGIN
// JOINSETG
	<<<<<<<< .../JOining_JOINSET.baf

IF
	Global("JO_%DeathVar_comp%_STARTING","GLOBAL",0)
	Global("JO_JOIN_STARTING_Override","LOCALS",0)
THEN
	RESPONSE #100
		MakeGlobal()
		SetGlobal("JO_Myself_InParty","LOCALS",0)
		SetGlobal("JO_Myself_Valid","LOCALS",0)
		SetGlobal("JO_Myself_AllowDead","LOCALS",0)
		SetGlobal("JO_%DeathVar_comp%_STARTING","GLOBAL",1)
		DisplayString(Myself,@1011)
		DestroySelf()
END
/*
IF
	Global("JO_%DeathVar_comp%_STARTING","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("JO_%DeathVar_comp%_STARTING","GLOBAL",2)
		ChangeAIScript("",%script_comp%)
END
*/
	>>>>>>>>
	EXTEND_TOP ~%override_script_comp%.bcs~ ~.../JOining_JOINSET.baf~ EVALUATE_BUFFER
		END

//						WRITE_ASCII SCRIPT_DEFAULT ~JOINSET~ (8)

						PATCH_PRINT ~%crecomp%.CRE : added...
											~

				COPY ~weidu_external/JOining_Party_Select/Mod_Compatibility/START.baf~  ~weidu_external/JOining_Party_Select/Mod_Compatibility/START.baf~ EVALUATE_BUFFER
					REPLACE_TEXTUALLY ~//	REPLACE_STARTING_BLOCK~ ~		CreateCreatureImpassable("%crecomp%",[-1.-1],0)
DisplayString("%DeathVar_comp%",@1010)
\0~
						PATCH_PRINT ~%crecomp% %DeathVar_comp% : added to %SOURCE_FILE%...
												~



					ACTION_IF FILE_EXISTS_IN_GAME ~%override_script_comp%.bcs~ BEGIN

								EXTEND_TOP ~%override_script_comp%.bcs~ ~JOining_Party_Select/Mod_Compatibility/MakeGlobalOverride.baf~ EVALUATE_BUFFER

						PATCH_PRINT ~MakeGlobalOverride : added to %SOURCE_FILE%...
												~
					END

		END

	END


/////////////////////////////////////////////////////////////////////////////////////////

// Valerie for SoD / BG2

/////////////////////////////////////////////////////////////////////////////////////////

ACTION_IF (MOD_IS_INSTALLED ~VALERIE.TP2~ ~0~) AND (Valerie_as_traveler = 1 OR Valerie_as_Real_traveler = 1) THEN BEGIN

	/* fetch language in which the mod is installed in - thanks to argent77 */
		// Valerie BG1
	// Language folder names listed in the order of LANGUAGE definitions in the mod.
		ACTION_DEFINE_ARRAY languages BEGIN
		"english" "russian" /*"german" "french" "polish" "spanish" "italian" "Schinese" "Polish" "korean"*/
			END

			// Fetching language index from the WeiDU.log
			OUTER_SET language_number = "-1"
			COPY "WeiDU.log" "WeiDU.log"
			REPLACE_EVALUATE CASE_INSENSITIVE
				"^~.*VALERIE\.tp2~ #\([0-9]+\) #5\b"
				BEGIN
				PATCH_IF (IS_AN_INT "MATCH1") BEGIN
					SET language_number = MATCH1
				END
				END
				"%MATCH0%"
			BUT_ONLY IF_EXISTS

			ACTION_IF (language_number >= 0) BEGIN
			OUTER_SPRINT mod_language $languages("Valerie_language_%")
		END

			WITH_TRA  "Valerie/lang/english/t2valp.TRA" // fallback
							"Valerie/lang/%VALERIE_language_%/t2valp.TRA" // Valerie installation language
			BEGIN
						OUTER_SET yes_t2valp = RESOLVE_STR_REF (@6)
						OUTER_SET yes_yes_t2valp = RESOLVE_STR_REF (@7)
						OUTER_SET no_t2valp = RESOLVE_STR_REF (@8)
			END

	COMPILE EVALUATE_BUFFER ~JOining_Party_Select/Mod_Compatibility/D/Special_Valerie_BG1.d~

END

/////////////////////////////////////////////////////////////////////////////////////////

//

/////////////////////////////////////////////////////////////////////////////////////////
