///////////////////////////////////////////////////////////////////////////////

// STARTING_BLOCK (See JOining_Party_Joined.tph, Start.baf, JOINSET.BAF)

///////////////////////////////////////////////////////////////////////////////

IF
	OR(2)
		InPartyAllowDead(Myself)
		Global("JO_Myself_AllowDead","LOCALS",1)
	Global("JO_JOIN_STARTING_Override","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("JO_JOIN_STARTING_Override","LOCALS",1)
		MakeGlobalOverride()
END
