IF
	Allegiance("%Death_var%",FAMILIAR)
	AreaCheck("bd2000")  // Boareskyr Bridge & Bridgefort
	Name("knockdown",Myself)
	Global("bd_knock_down_pc","BD2000",1)  // Boareskyr Bridge & Bridgefort
	IsOverMe("%Death_var%")
	OR(2)
		GlobalLT("bd_bridgefort_plot","global",9)
		GlobalLT("BD_PLOT","global",240)
THEN
	RESPONSE #100
		SetGlobal("bd_knock_down_pc","BD2000",0)  // Boareskyr Bridge & Bridgefort
		ActionOverride("%Death_var%",PlayDead(25))
		Continue()
END
