IF
	Global("RerakFight","GLOBAL",2)
THEN
	RESPONSE #100
		EscapeArea()
END

IF
	HPLT(Myself,21)
	Global("RerakFight","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("RerakFight","GLOBAL",3)
END

IF
	Global("RerakFight","GLOBAL",3)
	Allegiance(Myself,EVILBUTGREEN)
THEN
	RESPONSE #100
		CreateVisualEffectObject("SPFLESHS",Myself)
		PolymorphCopy("Raksha01")  // Rakshasa
		ChangeEnemyAlly(Myself,ENEMY)
END


