IF
	OR(3)
			!Global("JO_TRAVELER_%Death_var%","GLOBAL",0)
			!TriggerOverride("%Death_var%",Global("JO_JOIN_IS_TRAVELER","LOCALS",0))
			Allegiance("%Death_var%",FAMILIAR)
	!TriggerOverride("%Death_var%",Global("JO_Myself_Valid","LOCALS",0))
	Delay(1)
THEN
	RESPONSE #25
		ActionOverride("%Death_var%",PlayDead(25))
	RESPONSE #25
		ActionOverride("%Death_var%",PlayDead(40))
	RESPONSE #25
		ActionOverride("%Death_var%",PlayDead(30))
	RESPONSE #25
		ActionOverride("%Death_var%",PlayDead(20))
END
