
IF
	OnCreation()
THEN
	RESPONSE #100
		SetGlobal("JO_JOIN_GATHER_JO2608","MYAREA",0)
		PlaySong(%BPTheme%)
		Continue()
END

IF
	Global("JO2608_Explore","MYAREA",0)
THEN
	RESPONSE #100
		SetGlobal("JO2608_Explore","MYAREA",1)
		CreateCreatureImpassable("JO2608AL",[1729.1305],0)
		CreateCreatureImpassable("JOINEAN",[2051.1114],0)
		CreateCreatureImpassable("JOINEAN",[1431.1555],0)
		CreateCreatureImpassable("JOINEAN",[962.526],0)
		Explore()
		Continue()
END


///////////////////////////////////////////////////////////////////////////////

// END_OF_WATCH / JO_JOIN_CAMPAIGN_TRANSITION

///////////////////////////////////////////////////////////////////////////////
// Note :
		// Expanded by END_OF_WATCH.tph
			// Related to END_OF_WATCH in All_in.baf and END_OF_WATCH.tph
				// Special BG1/SoD end
					// Related to JO_JOIN_CAMPAIGN_TRANSITION in JO_JOINI.baf
///////////////////////////////////////////////////////////////////////////////

// Reset JO_JOIN_CAMPAIGN_TRANSITION for Switch trigger in JO_JOINI
IF
	!AreaCheck("BD6200")
	!AreaCheck("BD6100")
	!AreaCheck("BD6000")
	!AreaCheck("BD0120")
	!AreaCheck("BD0130")
	!AreaCheck("%NBaldursGate_DucalPalace_L1%")
	!AreaCheck("%NBaldursGate%")
	!Global("JO_JOIN_CAMPAIGN_TRANSITION","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("JO_JOIN_CAMPAIGN_TRANSITION","GLOBAL",0)
		Continue()
END

