// JO_JOINX 


///////////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////////


IF
    XPLT(Myself, 10000000)
    XPGT(Player1, 11000000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 1000000)
END

IF
    XPLT(Myself, 10000000)
    XPGT(Player1, 11000000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 1000000)
END

IF
    XPLT(Myself, 9000000)
    XPGT(Player1, 10000000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 1000000)
END

IF
    XPLT(Myself, 8000000)
    XPGT(Player1, 9000000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 1000000)
END

IF
    XPLT(Myself, 7750000)
    XPGT(Player1, 8000000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 7500000)
    XPGT(Player1, 7750000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 7250000)
    XPGT(Player1, 7500000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 7000000)
    XPGT(Player1, 7250000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 6750000)
    XPGT(Player1, 7000000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 6500000)
    XPGT(Player1, 6750000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 6250000)
    XPGT(Player1, 6500000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 6000000)
    XPGT(Player1, 6250000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 5750000)
    XPGT(Player1, 6000000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 5500000)
    XPGT(Player1, 5750000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 5250000)
    XPGT(Player1, 5500000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 5000000)
    XPGT(Player1, 5250000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 4750000)
    XPGT(Player1, 5000000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 4500000)
    XPGT(Player1, 4750000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 4250000)
    XPGT(Player1, 4500000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 4000000)
    XPGT(Player1, 4250000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 3750000)
    XPGT(Player1, 4000000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 3500000)
    XPGT(Player1, 3750000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 3250000)
    XPGT(Player1, 3500000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 3000000)
    XPGT(Player1, 3250000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 2750000)
    XPGT(Player1, 3000000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 2500000)
    XPGT(Player1, 2750000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 2250000)
    XPGT(Player1, 2500000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 2000000)
    XPGT(Player1, 2250000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 1750000)
    XPGT(Player1, 2000000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 1500000)
    XPGT(Player1, 1750000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 1250000)
    XPGT(Player1, 1500000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 1000000)
    XPGT(Player1, 1250000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 750000)
    XPGT(Player1, 1000000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 500000)
    XPGT(Player1, 750000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 250000)
    XPGT(Player1, 500000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 250000)
END

IF
    XPLT(Myself, 125000)
    XPGT(Player1, 250000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 125000)
END

IF
    XPLT(Myself, 64000)
    XPGT(Player1, 125000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 64000)
END

IF
    XPLT(Myself, 32000)
    XPGT(Player1, 64000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 32000)
END

IF
    XPLT(Myself, 16000)
    XPGT(Player1, 32000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 16000)
END

IF
    XPLT(Myself, 8000)
    XPGT(Player1, 16000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 8000)
END

IF
    XPLT(Myself, 4000)
    XPGT(Player1, 8000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 4000)
END

IF
    XPLT(Myself, 2000)
    XPGT(Player1, 4000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 2000)
END

IF
    XPLT(Myself, 1500)
    XPGT(Player1, 2000)
THEN
    RESPONSE #100
        AddXPObject(Myself, 500)
END


///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

// Basic without script

IF
	Allegiance(Myself,FAMILIAR)
	Global("JO_JOIN_CLEAR","LOCALS",3)
THEN
	RESPONSE #100
		SetGlobal("JO_JOIN_CLEAR","LOCALS",0)
		ChangeAIScript("",RACE)
END


///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////


