IF
	AreaCheck("AR0602")
	Global("JO_JOIN_BG2EE","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("JO_JOIN_BG2EE","GLOBAL",1)
		SetGlobal("JO_JOIN_ToB","GLOBAL",0)
		SetGlobal("%JO_JOIN_BG%","GLOBAL",0)
		SetGlobal("JO_JOIN_SoD","GLOBAL",0)
END

IF
	AreaCheck("AR4500")
	Global("JO_JOIN_ToB","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("JO_JOIN_ToB","GLOBAL",1)
		SetGlobal("%JO_JOIN_BG%","GLOBAL",0)
		SetGlobal("JO_JOIN_SoD","GLOBAL",0)
		SetGlobal("JO_JOIN_BG2EE","GLOBAL",0)
END


