IF
	Delay(10)
	Global("JO_Join_ability","GLOBAL",0)
THEN
	RESPONSE #100
		ActionOverride(Player1,AddSpecialAbility("jo_join"))
		SetGlobal("JO_Join_ability","GLOBAL",1)
		Continue()
END

IF
	Global("JO_JOIN","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("JO_NOJOIN","GLOBAL",0)
END

IF
	OR(2)
		HasItem("JO_JOIN",Myself)
		HasItem("JOMINHP1",Myself)
THEN
	RESPONSE #100
		DestroyItem("JO_JOIN")
		DestroyItem("JOMINHP1")
END
