
IF
//
	!Global("JO_JOIN_AREA_TRANSITION","GLOBAL",1) 
	Global("JO_JOIN_LOADING_SWITCH","GLOBAL",0) // Not at loading
	Global("JO_JOIN_BANTER_BLOCK","GLOBAL",0)
//
	Global("JO_JOIN_SWITCHING_PARTY","GLOBAL",0)
	Global("JO_Myself_LeaveParty","LOCALS",0)
//
//	!GlobalTimerNotExpired("JO_JOIN_BANTER_TIMER","LOCALS")
//
	OR(3)
		Global("JO_JOIN_BANTER_TIMER","GLOBAL",1)
		Global("JO_JOIN_BANTER_INTERACT","LOCALS",1)
		HotKey(B)
//
	Global("JO_JOIN_IS_JOINING","LOCALS",0)
	Global("JO_JOIN_CUTSCENE","GLOBAL",0)
	Global("JO_JOIN","LOCALS",0)
	Global("JO_JOINI","LOCALS",0)
	Global("JO_NOJOIN","GLOBAL",0)
//
	ActionListEmpty()
	!ActuallyInCombat()
	!See([ENEMY])
	OR(2)
		Allegiance(Myself,FAMILIAR)
		!Global("JO_JOIN_IS_TRAVELER","LOCALS",0)
//
	Global("JO_JOIN_NEVER_BANTER","LOCALS",0)
	!Global("JO_Myself_Valid","LOCALS",0)
//	OR(2)
//		RandomNum(4,2)
//		Global("JO_JOIN_BANTER_INTERACT","LOCALS",1)
	!AreaCheck("JO2608")
THEN
	RESPONSE #100
//		SetGlobalTimer("JO_JOIN_BANTER_TIMER","LOCALS",FOUR_HOURS)
		DisplayString(Myself,~Try to banter.~)
		SetGlobal("JO_JOIN_BANTER_TIMER","GLOBAL",0)
		SetGlobal("JO_JOIN_BANTER_INTERACT","LOCALS",0)
		StartDialogOverride("%BG1_BANTER%",Myself) // [ALLY] [FAMILIAR] [PC] [ANYONE]
		Continue()
END
