
//JOINABLE NPCS ARRAY MACRO__________________________________________________________
//
DEFINE_ACTION_MACRO JOINABLE_NPC_ARRAYS BEGIN
	//PDIALOG.2DA exists in all games
	ACTION_DEFINE_ASSOCIATIVE_ARRAY JOINABLE_NPC_ARRAY_2da BEGIN ~PDIALOG~ => ~~ END
	//Check PDIALOG.2DA file variants referenced in CAMPAIGN.2DA
	ACTION_IF FILE_EXISTS_IN_GAME ~CAMPAIGN.2DA~ BEGIN
		COPY_EXISTING ~CAMPAIGN.2DA~ ~CAMPAIGN.2DA~
			COUNT_2DA_ROWS 32 "cntrow"
			FOR (i = 0; i < cntrow; i = i + 1) BEGIN
				READ_2DA_ENTRY i 11 32 file
				TO_UPPER file
				DEFINE_ASSOCIATIVE_ARRAY JOINABLE_NPC_ARRAY_2da BEGIN ~%file%~ => ~~ END
			END
		BUT_ONLY
	END
	//Generate array with joinable NPC DV
	ACTION_PHP_EACH JOINABLE_NPC_ARRAY_2da AS file => ~~ BEGIN
		ACTION_IF FILE_EXISTS_IN_GAME ~%file%.2da~ BEGIN
			COPY_EXISTING ~%file%.2da~ ~override~
				COUNT_2DA_ROWS 3 "cntrow"
				FOR (i = 1; i < cntrow; i = i + 1) BEGIN
					READ_2DA_ENTRY i 0 3 "dv"
					TO_UPPER dv
					// Starting Block
					DEFINE_ASSOCIATIVE_ARRAY JOINABLE_NPC_ARRAY_dv BEGIN ~%dv%~ => ~~ END
				END
			BUT_ONLY
		END
	END
	//Generate array with joinable NPC cre files
	COPY_EXISTING_REGEXP GLOB ~.+\.CRE~ ~override~
		READ_ASCII DEATHVAR "dv" (32) NULL
		TO_UPPER dv
		PATCH_IF VARIABLE_IS_SET $JOINABLE_NPC_ARRAY_dv(~%dv%~) BEGIN
			DEFINE_ASSOCIATIVE_ARRAY JOINABLE_NPC_ARRAY BEGIN ~%SOURCE_FILE%~ => ~%dv%~ END
		END
		PATCH_IF NOT VARIABLE_IS_SET $JOINABLE_NPC_ARRAY_dv(~%dv%~) BEGIN
			DEFINE_ASSOCIATIVE_ARRAY NON_JOINABLE_NPC_ARRAY BEGIN ~%SOURCE_FILE%~ => ~%dv%~ END
		END
	BUT_ONLY
END
//__________________________________________________________________________________

LAM JOINABLE_NPC_ARRAYS

ACTION_PHP_EACH JOINABLE_NPC_ARRAY AS cre => dv BEGIN
// 	PRINT ~%cre% => %dv%~


  COPY_EXISTING ~%cre%~ ~override~
    READ_ASCII 0x248 override_script
    PATCH_IF NOT (~%override_script%~ STRING_EQUAL_CASE ~idiot01~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~NONE~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~SHOUT~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~INITDLG~)

// Imoen
// Original Imoen AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%IMOEN_BCS%~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~BDIMOENS~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~IMOE25~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~IMOEN~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~C#STIMOE~) // AND NOT (~%override_script%~ STRING_EQUAL_CASE ~TTIMOEN~) // BDIMOENS is for Imoen4Ever
// Original Imoen // EET_END AND NOT (~%override_script%~ STRING_EQUAL_CASE ~IMOEN_~)
// Original Imoen // EET_ODD AND NOT (~%override_script%~ STRING_EQUAL_CASE ~IMOEN2~)

// Edwin
// Original Edwin AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%EDWIN_BCS%~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~EDWI25~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~BDEDWIN~)
// Original Edwin // EET_END AND NOT (~%override_script%~ STRING_EQUAL_CASE ~EDWIN_~)
// Original Edwin // EET_ODD AND NOT (~%override_script%~ STRING_EQUAL_CASE ~EDWIN~)

// Jaheira
// Original Jaheira AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%JAHEIRA_BCS%~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~JAHE25~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~BDJAHEIR~) // AND NOT (~%override_script%~ STRING_EQUAL_CASE ~TTJAHEIR~)
// Original Jaheira // EET_END AND NOT (~%override_script%~ STRING_EQUAL_CASE ~JAHEIRA_~)
// Original Jaheira // EET_ODD AND NOT (~%override_script%~ STRING_EQUAL_CASE ~JAHEIRA~)

// Minsc
// Original Minsc AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%MINSC_BCS%~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~MINS25~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~BDMINSC~) // AND NOT (~%override_script%~ STRING_EQUAL_CASE ~TTMINSC~)
// Original Minsc // EET_END AND NOT (~%override_script%~ STRING_EQUAL_CASE ~MINSC_~)
// Original Minsc // EET_ODD AND NOT (~%override_script%~ STRING_EQUAL_CASE ~MINSC~)

// Viconia
// Original Viconia AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%VICONIA_BCS%~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~VICO25~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~BDVICONI~)
// Original Viconia // EET_END AND NOT (~%override_script%~ STRING_EQUAL_CASE ~VICONIA_~)
// Original Viconia // EET_ODD AND NOT (~%override_script%~ STRING_EQUAL_CASE ~VICONIA~)

// Dorn
// Original Dorn AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%DORN_BCS%~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~DORN25~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~BDDORN~)
// Original Dorn // EET_END AND NOT (~%override_script%~ STRING_EQUAL_CASE ~DORN_~)
// Original Dorn // EET_ODD AND NOT (~%override_script%~ STRING_EQUAL_CASE ~DORN~)

// Neera
// Original Neera AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%NEERA_BCS%~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~NEER25~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~BDNEERA~)
// Original Neera // EET_END AND NOT (~%override_script%~ STRING_EQUAL_CASE ~NEERA_~)
// Original Neera // EET_ODD AND NOT (~%override_script%~ STRING_EQUAL_CASE ~NEERA~)

// Rasaad
// Original Rasaad AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%RASAAD_BCS%~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~RASA25~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~BDRASAAD~)
// Original Rasaad // EET_END AND NOT (~%override_script%~ STRING_EQUAL_CASE ~RASAAD_~)
// Original Rasaad // EET_ODD AND NOT (~%override_script%~ STRING_EQUAL_CASE ~RASAAD~)

//////////////////////////////////////////////////////////////////////////////////////
/////////////////////////// bg1 ///////////////////////////

// Ajantis
// Original Ajantis AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%AJANTIS_BCS%~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~BDAJANTI~)  // BDAJANTI is for Ajantis_BG1_Expansion

// Alora
// Original Alora AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%ALORA_BCS%~)

// Branwen
// Original Branwen AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%BRANWEN_BCS%~) // AND NOT (~%override_script%~ STRING_EQUAL_CASE ~TTBRAN~)
// Original Branwen // EET_END AND NOT (~%override_script%~ STRING_EQUAL_CASE ~BRANWEN_~)
// Original Branwen // EET_ODD AND NOT (~%override_script%~ STRING_EQUAL_CASE ~BRANWEN~)

// Coran
// Original Coran AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%CORAN_BCS%~)

// Dynaheir
// Original Dynaheir AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%DYNAHEIR_BCS%~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~BDDYNAHE~)

// Eldoth
// Original Eldoth AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%ELDOTH_BCS%~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~BDELDOTH~)

// Faldorn
// Original Faldorn AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%FALDORN_BCS%~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~bdFALDORN~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~bdfaldor~)
// Original Faldorn // EET_END AND NOT (~%override_script%~ STRING_EQUAL_CASE ~FALDORN_~)
// Original Faldorn // EET_ODD AND NOT (~%override_script%~ STRING_EQUAL_CASE ~FALDORN~)

// Garrick
// Original Garrick AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%GARRICK_BCS%~)
// Original Garrick // EET_END AND NOT (~%override_script%~ STRING_EQUAL_CASE ~GARRICK_~)
// Original Garrick // EET_ODD AND NOT (~%override_script%~ STRING_EQUAL_CASE ~GARRICK~)

// Kagain
// Original Kagain AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%KAGAIN_BCS%~)

// Khalid
// Original Khalid AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%KHALID_BCS%~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~BDKHALID~)

// Kivan
// Original Kivan AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%KIVAN_BCS%~)

// Montaron
// Original Montaron AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%MONTARON_BCS%~)

// Quayle
// Original Quayle AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%QUAYLE_BCS%~)

// Safana TODO : Something wrong with bg2 override script (probably related to Safana BG2)
// Original Safana AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%SAFANA_BCS%~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~BDSAFANA~)

// Sharteel
// Original Sharteel AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%SHARTEEL_BCS%~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~k9shar~)

// Skie
// Original Skie AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%SKIE_BCS%~)
// Original Skie // EET_END AND NOT (~%override_script%~ STRING_EQUAL_CASE ~SKIE_~)
// Original Skie // EET_ODD AND NOT (~%override_script%~ STRING_EQUAL_CASE ~SKIE~)

// Tiax
// Original Tiax AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%TIAX_BCS%~)

// Xan
// Original Xan AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%XAN_BCS%~) // AND NOT (~%override_script%~ STRING_EQUAL_CASE ~ttxan~)

// Xzar
// Original Xzar AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%XZAR_BCS%~)

// Yeslick
// Original Yeslick AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%YESLICK_BCS%~)

// Baeloth
// Original Baeloth AND NOT (~%override_script%~ STRING_EQUAL_CASE ~BAELOTH~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~BDBAELOT~)

/////////////////////////// SoD ///////////////////////////

// Voghiln
// Original Voghiln AND NOT (~%override_script%~ STRING_EQUAL_CASE ~BDVOGHIL~)

// Corwin
// Original Corwin AND NOT (~%override_script%~ STRING_EQUAL_CASE ~BDCORWIN~)

// Mkhiin
// Original Mkhiin AND NOT (~%override_script%~ STRING_EQUAL_CASE ~BDMKHIIN~)

// Glint
// Original Glint AND NOT (~%override_script%~ STRING_EQUAL_CASE ~BDGLINT~)

/////////////////////////// bg2 ///////////////////////////

// Aerie
// Original Aerie AND NOT (~%override_script%~ STRING_EQUAL_CASE ~AERIE~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~AERI25~)

// Anomen
// Original Anomen AND NOT (~%override_script%~ STRING_EQUAL_CASE ~ANOMEN~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~ANOM25~)

// Cernd
// Original Cernd AND NOT (~%override_script%~ STRING_EQUAL_CASE ~CERND~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~CERN25~)

// Haerdalis
// Original Haerdalis AND NOT (~%override_script%~ STRING_EQUAL_CASE ~HAERDALI~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~HAER25~)

// Hexxat
// Original Hexxat AND NOT (~%override_script%~ STRING_EQUAL_CASE ~HEXXAT~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~HEXXA25~)

// Jan
// Original Jan AND NOT (~%override_script%~ STRING_EQUAL_CASE ~JAN~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~JAN25~)

// Keldorn
// Original Keldorn AND NOT (~%override_script%~ STRING_EQUAL_CASE ~KELDORN~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~KELD25~)

// Korgan
// Original Korgan AND NOT (~%override_script%~ STRING_EQUAL_CASE ~KORGAN~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~KORG25~)

// Mazzy
// Original Mazzy AND NOT (~%override_script%~ STRING_EQUAL_CASE ~MAZZY~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~MAZZ25~)

// Nalia
// Original Nalia AND NOT (~%override_script%~ STRING_EQUAL_CASE ~NALIA~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~NALI25~)

// Sarevok
// Original Sarevok AND NOT (~%override_script%~ STRING_EQUAL_CASE ~SAREV25~)

// Valygar
// Original Valygar AND NOT (~%override_script%~ STRING_EQUAL_CASE ~VALYGAR~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~VALY25~)

// Wilson
// Original Wilson AND NOT (~%override_script%~ STRING_EQUAL_CASE ~WILSON~)

// Yoshimo
// Original Yoshimo AND NOT (~%override_script%~ STRING_EQUAL_CASE ~YOSHIMO~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~YOSH25~)

/////////////////////////// Mods BG1 ///////////////////////////

// Ishlilka (#Ishy)
// Mod Ishlilka AND NOT (~%override_script%~ STRING_EQUAL_CASE ~ishyscrp~)

// ChaosKnight-kit
// Mod Jacob AND NOT (~%override_script%~ STRING_EQUAL_CASE ~ZYJCOB~)

// Askaria-Quest
// Mod Askaria AND NOT (~%override_script%~ STRING_EQUAL_CASE ~ZYASKA~)

// Isra BG1
// Mod Isra_BG1 AND NOT (~%override_script%~ STRING_EQUAL_CASE ~RH#ISRA~)

// Finch
// Mod Finch AND NOT (~%override_script%~ STRING_EQUAL_CASE ~SUFINCH~)

// Drizzt Saga
// Mod Jarlaxle_Saga AND NOT (~%override_script%~ STRING_EQUAL_CASE ~F_JARLAX~)
// Mod Artemis_Enteri_Saga AND NOT (~%override_script%~ STRING_EQUAL_CASE ~F_ASSASI~)
// Mod Catti-Brie_Saga AND NOT (~%override_script%~ STRING_EQUAL_CASE ~F_CATTIB~)
// Mod Bruenor_Saga AND NOT (~%override_script%~ STRING_EQUAL_CASE ~F_BRUENO~)
// Mod Regis_Saga AND NOT (~%override_script%~ STRING_EQUAL_CASE ~F_REGIS2~)
// Mod Drizzt_Saga AND NOT (~%override_script%~ STRING_EQUAL_CASE ~F_DRIZZT~)
// Mod Wulfgar_Saga AND NOT (~%override_script%~ STRING_EQUAL_CASE ~F_WULFGA~)

// Dark Horizons
// Mod Thorin AND NOT (~%override_script%~ STRING_EQUAL_CASE ~cmtthor~)
// Mod Morwen AND NOT (~%override_script%~ STRING_EQUAL_CASE ~cmtmorw~)

// DSotSC
// Mod Bardo AND NOT (~%override_script%~ STRING_EQUAL_CASE ~DSBARDO~)
// Mod Bub_Snikt AND NOT (~%override_script%~ STRING_EQUAL_CASE ~DSBUB~)
// Mod Conchobhair AND NOT (~%override_script%~ STRING_EQUAL_CASE ~dsconcho~)
// Mod CuChoinneach AND NOT (~%override_script%~ STRING_EQUAL_CASE ~dscucho~)
// Mod Ferthgil_Trollslayer AND NOT (~%override_script%~ STRING_EQUAL_CASE ~dsferth~)
// Mod Jet'laya AND NOT (~%override_script%~ STRING_EQUAL_CASE ~dsjetla~)
// Mod Keiria_Silverstring AND NOT (~%override_script%~ STRING_EQUAL_CASE ~dskeiri~)
// Mod Skeezer_Lumpkin_VI AND NOT (~%override_script%~ STRING_EQUAL_CASE ~dsskeez~)
// Mod Thorfinn_Hauskluniff AND NOT (~%override_script%~ STRING_EQUAL_CASE ~dsthorf~)

// NTotSC
// Mod Will_Scarlet AND NOT (~%override_script%~ STRING_EQUAL_CASE ~ntwill~)

// Valerie
// Mod Valerie AND NOT (~%override_script%~ STRING_EQUAL_CASE ~T2VAL~)

// Indira
// Mod Indira AND NOT (~%override_script%~ STRING_EQUAL_CASE ~J#Indi~)

// Bristlelick
// Mod Bristlelick AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#BRIST~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#2BRIST~)

// Glam's npc pack
// Mod Dave AND NOT (~%override_script%~ STRING_EQUAL_CASE ~GV#DAVE~)
// Mod Flara AND NOT (~%override_script%~ STRING_EQUAL_CASE ~GV#FLAR~)
// Mod Littlun AND NOT (~%override_script%~ STRING_EQUAL_CASE ~GV#LITT~)
// Mod Moidre AND NOT (~%override_script%~ STRING_EQUAL_CASE ~GV#MOID~)
// Mod Vynd AND NOT (~%override_script%~ STRING_EQUAL_CASE ~GV#VYND~)

// Kale BG1
// Mod Kale_BG1 AND NOT (~%override_script%~ STRING_EQUAL_CASE ~X3Kale~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~X32Kale~)

// New Tales of the Sword Coast
// Mod Kasandra AND NOT (~%override_script%~ STRING_EQUAL_CASE ~Kasandra~)
// Mod Masambe AND NOT (~%override_script%~ STRING_EQUAL_CASE ~Masambe~)
// Mod Alethra AND NOT (~%override_script%~ STRING_EQUAL_CASE ~Alethra~)
// Mod Rimardo AND NOT (~%override_script%~ STRING_EQUAL_CASE ~Rimardo~)
// Mod Talindra AND NOT (~%override_script%~ STRING_EQUAL_CASE ~Talindra~)
// Mod Theodor AND NOT (~%override_script%~ STRING_EQUAL_CASE ~Theodor~)
// Mod Ariadne AND NOT (~%override_script%~ STRING_EQUAL_CASE ~Ariadne~)
// Mod Nathan AND NOT (~%override_script%~ STRING_EQUAL_CASE ~Nathan~)
// Mod Namiir AND NOT (~%override_script%~ STRING_EQUAL_CASE ~Namiir~)
// Mod Miranda AND NOT (~%override_script%~ STRING_EQUAL_CASE ~Miranda~)

// Walahnan
// Mod Walahnan_BG1 AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#WALAH~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#SWALAH~)

// Aerie in BG:EE
// Mod Aerie_BG1 AND NOT (~%override_script%~ STRING_EQUAL_CASE ~B2#Aeri2~)

// Margarita Zelleod
// Mod Margarita AND NOT (~%override_script%~ STRING_EQUAL_CASE ~RL#MARG~)

// Verr'sza BG1
// Mod Verr'sza_BG1 AND NOT (~%override_script%~ STRING_EQUAL_CASE ~l#1verr~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#1DVer~)

// Mur'neth
// Mod Mur'neth AND NOT (~%override_script%~ STRING_EQUAL_CASE ~A#MURN~)

// Next_Traveler BG1

/////////////////////////// Mods BG2 ///////////////////////////

// Alora BG2 (CMALORA)
// Mod Alora BG2 AND NOT (~%override_script%~ STRING_EQUAL_CASE ~cmalora~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~cmalo25~)

// Yeslick BG2 (LK#YESLK)
// Mod Yeslick BG2 AND NOT (~%override_script%~ STRING_EQUAL_CASE ~LK#YESL~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~LK#YES25~)

// The Undying (cmninaf)
// Mod Undying AND NOT (~%override_script%~ STRING_EQUAL_CASE ~CMNINAF~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~CMNINA25~)

// The Undying (callisto)
// Mod Undying AND NOT (~%override_script%~ STRING_EQUAL_CASE ~CALLISTO~)

// Summon Bhaalspawn (BHAALSPW)
// Mod Sandra AND NOT (~%override_script%~ STRING_EQUAL_CASE ~BHAALSPW~)

// Vampire Tales (cmgmiriam)
// Mod Miriam AND NOT (~%override_script%~ STRING_EQUAL_CASE ~CMGMIRI~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~CMGMI25~)

// Kim (Kim)
// Mod Kim AND NOT (~%override_script%~ STRING_EQUAL_CASE ~Kim~)

// Severian (#Severian)
// Mod Severian AND NOT (~%override_script%~ STRING_EQUAL_CASE ~#Sever~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~#SevD25~)

// Branwen BG2
// Mod Branwen_BG2 AND NOT (~%override_script%~ STRING_EQUAL_CASE ~O#BranS~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~O#Bra25S~)

// Tiax BG2
// Mod Tiax_BG2 AND NOT (~%override_script%~ STRING_EQUAL_CASE ~O#TiaxS~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~O#Tia25S~)

// Xan BG2
// Mod Xan_BG2 AND NOT (~%override_script%~ STRING_EQUAL_CASE ~O#XanS~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~O#Xan25S~)

// Coran BG2
// Mod Coran_BG2 AND NOT (~%override_script%~ STRING_EQUAL_CASE ~O#CORANS~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~O#COR25S~)

// Auren
// Mod Auren AND NOT (~%override_script%~ STRING_EQUAL_CASE ~K#Auren~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~K#Aure25~)

// Isra BG2
// Mod Isra_BG2 AND NOT (~%override_script%~ STRING_EQUAL_CASE ~rh#isr~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~rh#is25~)

// Nephele
// Mod Nephele_Samios AND NOT (~%override_script%~ STRING_EQUAL_CASE ~lk#neph~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~lk#ne25~)

// Sheena
// Mod Kiara AND NOT (~%override_script%~ STRING_EQUAL_CASE ~K#Sheena~)

// Kiara / Zaiya
// Mod Kiara AND NOT (~%override_script%~ STRING_EQUAL_CASE ~kiara~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~kiar25~)

// Mod Zaiya AND NOT (~%override_script%~ STRING_EQUAL_CASE ~Zaiya~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~zai25~)


// The Beaurin Legacy
// Mod Minyae AND NOT (~%override_script%~ STRING_EQUAL_CASE ~QI#MIS~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~QI#M25S~)

// Mod Elaryn AND NOT (~%override_script%~ STRING_EQUAL_CASE ~QI#ElaS~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~QI#E25S~)


// Tyris Flare
// Mod Finch AND NOT (~%override_script%~ STRING_EQUAL_CASE ~CMGMIRI~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~CMGMI25~)


// Finch
// Mod Tyris AND NOT (~%override_script%~ STRING_EQUAL_CASE ~g#tyris~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~g#tyrs25~)


// Region of Terror
// Mod Wulfgar_Terror AND NOT (~%override_script%~ STRING_EQUAL_CASE ~WULFG2~)
// Mod Regis_Terror AND NOT (~%override_script%~ STRING_EQUAL_CASE ~REG2~)
// Mod Drizzt_Terror AND NOT (~%override_script%~ STRING_EQUAL_CASE ~DRIZ21~)
// Mod Bruenor_Terror AND NOT (~%override_script%~ STRING_EQUAL_CASE ~Brue2~)
// Mod Catti-Brie_Terror AND NOT (~%override_script%~ STRING_EQUAL_CASE ~Catt2~)
// Mod Artemis_Entreri_Terror AND NOT (~%override_script%~ STRING_EQUAL_CASE ~ENTER2~)
// Mod Jarlaxle_Terror AND NOT (~%override_script%~ STRING_EQUAL_CASE ~Jarlax2~)
// Mod Tapio_Perkiomaki_Terror AND NOT (~%override_script%~ STRING_EQUAL_CASE ~Tapio~)
// Mod Randall_Terror AND NOT (~%override_script%~ STRING_EQUAL_CASE ~RANDALL~)
// Mod Alissa_Terror AND NOT (~%override_script%~ STRING_EQUAL_CASE ~ALISSA1~)
// Mod Mordragon_Terror AND NOT (~%override_script%~ STRING_EQUAL_CASE ~Mordrg~)

// Shadow over Soubar
// Mod Selence_Hillstar_Soubar AND NOT (~%override_script%~ STRING_EQUAL_CASE ~SELENCE~)
// Mod Charlotte_Soubar AND NOT (~%override_script%~ STRING_EQUAL_CASE ~CHARLOT0~)
// Mod Bolivar_Soubar AND NOT (~%override_script%~ STRING_EQUAL_CASE ~BOLIVAR1~)
// Mod Tomas_Tomalson_Soubar AND NOT (~%override_script%~ STRING_EQUAL_CASE ~TOMASTOM~)

// ajantisbg2
// Mod Ajantis_BG2 AND NOT (~%override_script%~ STRING_EQUAL_CASE ~C#Ajan~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~C#Ajan25~)

// Kivan and Deheriana
// Mod Kivan_BG2 AND NOT (~%override_script%~ STRING_EQUAL_CASE ~P#KIV01~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~P#KI25~)
// Mod Deheriana AND NOT (~%override_script%~ STRING_EQUAL_CASE ~P#DEH01~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~P#DE25~)

// Yvette
// Mod Yvette AND NOT (~%override_script%~ STRING_EQUAL_CASE ~YxYve~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~YxYv25~)

// The Luxley Family
// Mod Sebastian AND NOT (~%override_script%~ STRING_EQUAL_CASE ~fhlseb~)
// Mod Andrei AND NOT (~%override_script%~ STRING_EQUAL_CASE ~FHLAND~)

//  Beyond the Law
// Mod Kiyone AND NOT (~%override_script%~ STRING_EQUAL_CASE ~z#kiyone~)
// Mod Kova AND NOT (~%override_script%~ STRING_EQUAL_CASE ~z#kova~)

// Petsy
// Mod Petsy AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L3PETSY~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L3Pet25~)

// Kale BG2
// Mod Kale_BG2 AND NOT (~%override_script%~ STRING_EQUAL_CASE ~X3Kal~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~X3Kal25~)

// Walahnan BG2
// Mod Walahnan_BG2 AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#2WH~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#2WH25~)

// Autumns Twilight
// Mod Dusk AND NOT (~%override_script%~ STRING_EQUAL_CASE ~P_DUSKS~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~P_DUS25S~)
// Mod Fall AND NOT (~%override_script%~ STRING_EQUAL_CASE ~P_FALLS~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~P_FAL25S~)
// Mod Cho'Nuja AND NOT (~%override_script%~ STRING_EQUAL_CASE ~P_CHONS~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~P_CHO25S~)
// Mod Alendir AND NOT (~%override_script%~ STRING_EQUAL_CASE ~P_ALENS~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~P_ALE25S~)

// Lysre, dragonne de poche
// Mod Lysre AND NOT (~%override_script%~ STRING_EQUAL_CASE ~CKLYSRES~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~CKLys25S~)

// Tashia
// Mod Tashia AND NOT (~%override_script%~ STRING_EQUAL_CASE ~TASHIA~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~tash25~)

// Dace Linton
// Mod Dace AND NOT (~%override_script%~ STRING_EQUAL_CASE ~T#DACE~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~T#DAC25~)

// Sharteel_BG2
// Mod Sharteel_BG2 AND NOT (~%override_script%~ STRING_EQUAL_CASE ~JOsharte~)

// Amber
// Mod Amber AND NOT (~%override_script%~ STRING_EQUAL_CASE ~m#amber~)

// Evandra
// Mod Evandra AND NOT (~%override_script%~ STRING_EQUAL_CASE ~rh#Eva~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~rh#ev25~)

// Lena
// Mod Lena AND NOT (~%override_script%~ STRING_EQUAL_CASE ~EU#Lena~)

// Paina
// Mod Pai'Na AND NOT (~%override_script%~ STRING_EQUAL_CASE ~C0Paina~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~C0Pai25S~)

// Verr'sza BG2
// Mod Verr'sza_BG2 AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#2verr~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~l#2ve25~)
// Mod Phalh AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#2phal~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#2ph25~)

// Saradas magic for BG2
// Mod Saradas AND NOT (~%override_script%~ STRING_EQUAL_CASE ~!SARTOB~)

// Varshoon
// Mod Varshoon AND NOT (~%override_script%~ STRING_EQUAL_CASE ~VXVAR~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~VxVar25~)

// Skie the Cost of One girl Soul
// Mod BG2_Skie AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#2SDSKI~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~l#2sd25~)
// Mod Eddard AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#L#2ED~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~l#2ED25~)

// Anishai
// Mod Anishai AND NOT (~%override_script%~ STRING_EQUAL_CASE ~Anishai~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~Anishai25~)

// Will of the Wisps
// Mod WispWill AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L0will~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~l0wil25~)

// Angelo
// Mod Angelo AND NOT (~%override_script%~ STRING_EQUAL_CASE ~ADANGEL~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~ADANG25~)

// Adrian
// Mod Adrian AND NOT (~%override_script%~ STRING_EQUAL_CASE ~RH#ADR~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~rh#ad25~)

// Hubelpot the Vegetable Merchant
// Mod Hubelpot AND NOT (~%override_script%~ STRING_EQUAL_CASE ~sc#hub~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~sc#hub25~)

// Living Clara
// Mod Clara AND NOT (~%override_script%~ STRING_EQUAL_CASE ~YF_CLARA~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~YF_CLA25~)

// Arath
// Mod Arath AND NOT (~%override_script%~ STRING_EQUAL_CASE ~LK#ARATH~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~LK#AR25~)

// In Love Undeath, Xzelë Melaenitt
// Mod Xzelë AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#XZE~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#XZE25~)

// Juniper and the Stone Leech
// Mod Juniper AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#JN25~)

// Baeloth BG2
// Mod BG2_Baeloth AND NOT (~%override_script%~ STRING_EQUAL_CASE ~ZDBAES~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~ZDBAE25S~)

// Hephernaan BG2
// Mod Hephernaan AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#HPH~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#HPH25~)

// Fyalvara
// Mod Fyalvara AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#fya~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#fya25~)

// The Journey to the Whin Hill
// Mod Afu-Zuuvi AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#AFU~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#AFU25~)

// Dvaradime
// Mod Dvaradime AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#DVA~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#DVA25~)

// Fade
// Mod Fade AND NOT (~%override_script%~ STRING_EQUAL_CASE ~E3Fade~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~E3Fade25~)

// Ehlastra
// Mod Ehlastra AND NOT (~%override_script%~ STRING_EQUAL_CASE ~HG_Ehla~)

// Sime NPC
// Mod Sime AND NOT (~%override_script%~ STRING_EQUAL_CASE ~PPSime~)

// Ninde Amblecrown
// Mod Ninde AND NOT (~%override_script%~ STRING_EQUAL_CASE ~lk#nins~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~LK#NI25~)

// Sarah ToB
// Mod Sarah AND NOT (~%override_script%~ STRING_EQUAL_CASE ~K#Sarah~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~K#Sara25~)

// Lhannd
// Mod Lhannd AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#LHA~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#LHA25~)

// Fhaugy
// Mod Fhaugy AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#FHA~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#FHA25~)

// Gahesh
// Mod Gahesh AND NOT (~%override_script%~ STRING_EQUAL_CASE ~G1Gahe~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~G1Gahe25~)

// Valkrana
// Mod Valkrana AND NOT (~%override_script%~ STRING_EQUAL_CASE ~vvVALK~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~vvVALK25~)

// Frennedan_NPC
// Mod Frennedan AND NOT (~%override_script%~ STRING_EQUAL_CASE ~FREN~)

// Next_Traveler BG2

/////////////////////////// Mods Continuous ///////////////////////////

// EET Nikita AND NOT (~%override_script%~ STRING_EQUAL_CASE ~cmtnikit~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~cmnikita~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~CMNIK25~)

// EET Alora_Continuous AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%ALORA_BCS%~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~cmalora~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~cmalo25~)

// EET Ajantis_Continuous AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%AJANTIS_BCS%~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~BDAJANTI~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~C#Ajan~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~C#Ajan25~) // BDAJANTI is for Ajantis_BG1_Expansion

// EET Kivan_Continuous AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%KIVAN_BCS%~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~P#KIV01~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~P#KI25~)

// EET Walahnan_Continuous AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#WALAH~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#SWALAH~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#2WH~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~L#2WH25~)

// EET Coran_Continuous AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%CORAN_BCS%~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~O#CORANS~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~O#COR25S~)

// EET Yeslick_Continuous AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%YESLICK_BCS%~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~LK#YES~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~LK#YES25~)

// EET Xan_Continuous AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%XAN_BCS%~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~O#XanS~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~O#Xan25S~)

// EET Branwen_Continuous AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%BRANWEN_BCS%~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~O#BranS~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~O#Bra25S~)
// EET Branwen_Continuous // EET_END AND NOT (~%override_script%~ STRING_EQUAL_CASE ~BRANWEN_~)
// EET Branwen_Continuous // EET_ODD AND NOT (~%override_script%~ STRING_EQUAL_CASE ~BRANWEN~)

// EET Tiax_Continuous AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%TIAX_BCS%~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~O#TiaxS~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~O#Tia25S~)

// EET Isra_Continuous AND NOT (~%override_script%~ STRING_EQUAL_CASE ~RH#ISRA~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~rh#isr~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~rh#is25~)

// Ascalon's Breagar
// Mod Breagar AND NOT (~%override_script%~ STRING_EQUAL_CASE ~ACBRE~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~ACBRE25~)

// EET Sharteel_Continuous AND NOT (~%override_script%~ STRING_EQUAL_CASE ~%SHARTEEL_BCS%~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~k9shar~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~JOsharte~)

// EET Region_of_Terror_Continuous AND NOT (~%override_script%~ STRING_EQUAL_CASE ~F_JARLAX~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~Jarlax2~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~F_ASSASI~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~Enter2~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~F_CATTIB~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~Catt2~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~F_BRUENO~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~Brue2~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~F_REGIS2~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~Reg2~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~F_DRIZZT~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~Driz21~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~F_WULFGA~) AND NOT (~%override_script%~ STRING_EQUAL_CASE ~WULFG2~)

// Husam
// Mod Husam AND NOT (~%override_script%~ STRING_EQUAL_CASE ~C#Husam1~)

// Next_Traveler Continuous


	BEGIN 
      SPRINT $npc_scripts (~%override_script%~)~1~
    END
  BUT_ONLY
END
ACTION_PHP_EACH npc_scripts AS script => ind BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~%script%.bcs~) BEGIN
    EXTEND_TOP ~%script%.bcs~ ~JOining_Party_Select/Baf/All_NPC_JOIN.baf~ EVALUATE_BUFFER
	PRINT ~%script%.BCS extended with All_NPC_JOIN.baf
	~
  END
END

///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////

// No cre ToB


  ACTION_IF (FILE_EXISTS_IN_GAME ~P#KI25.bcs~ AND NOT Kivan_BG2_as_traveler = 1 AND NOT Kivan_BG2_as_Real_traveler = 1) AND NOT Kivan_Continuous_as_traveler = 1 AND NOT Kivan_Continuous_as_Real_traveler = 1 BEGIN
    EXTEND_TOP ~P#KI25.bcs~ ~JOining_Party_Select/Baf/All_NPC_JOIN.baf~ EVALUATE_BUFFER
	PRINT ~P#KI25.BCS extended with All_NPC_JOIN.baf
	~
  END

  ACTION_IF (FILE_EXISTS_IN_GAME ~P#DE25.bcs~ AND NOT Deheriana_as_traveler = 1 AND NOT Deheriana_as_Real_traveler = 1) BEGIN
    EXTEND_TOP ~P#DE25.bcs~ ~JOining_Party_Select/Baf/All_NPC_JOIN.baf~ EVALUATE_BUFFER
	PRINT ~P#DE25.BCS extended with All_NPC_JOIN.baf
	~
  END

  ACTION_IF (FILE_EXISTS_IN_GAME ~#SevD25.bcs~ AND NOT Severian_de_Demerya_as_traveler = 1 AND NOT Severian_de_Demerya_as_Real_traveler = 1) BEGIN
    EXTEND_TOP ~#SevD25.bcs~ ~JOining_Party_Select/Baf/All_NPC_JOIN.baf~ EVALUATE_BUFFER
	PRINT ~#SevD25.BCS extended with All_NPC_JOIN.baf
	~
  END

  ACTION_IF (FILE_EXISTS_IN_GAME ~kiar25.bcs~ AND NOT Kiara_as_traveler = 1 AND NOT Kiara_as_Real_traveler = 1) BEGIN
    EXTEND_TOP ~kiar25.bcs~ ~JOining_Party_Select/Baf/All_NPC_JOIN.baf~ EVALUATE_BUFFER
	PRINT ~kiar25.BCS extended with All_NPC_JOIN.baf
	~
  END

  ACTION_IF (FILE_EXISTS_IN_GAME ~zai25.bcs~ AND NOT Zaiya_as_traveler = 1 AND NOT Zaiya_as_Real_traveler = 1) BEGIN
    EXTEND_TOP ~zai25.bcs~ ~JOining_Party_Select/Baf/All_NPC_JOIN.baf~ EVALUATE_BUFFER
	PRINT ~zai25.BCS extended with All_NPC_JOIN.baf
	~
  END

  ACTION_IF (FILE_EXISTS_IN_GAME ~YxYv25.bcs~ AND NOT Yvette_as_traveler = 1 AND NOT Yvette_as_Real_traveler = 1) BEGIN
    EXTEND_TOP ~YxYv25.bcs~ ~JOining_Party_Select/Baf/All_NPC_JOIN.baf~ EVALUATE_BUFFER
	PRINT ~YxYv25.BCS extended with All_NPC_JOIN.baf
	~
  END

  ACTION_IF (FILE_EXISTS_IN_GAME ~L#HPH25.bcs~ AND NOT Hephernaan_as_traveler = 1 AND NOT Hephernaan_as_Real_traveler = 1) BEGIN
    EXTEND_TOP ~L#HPH25.bcs~ ~JOining_Party_Select/Baf/All_NPC_JOIN.baf~ EVALUATE_BUFFER
	PRINT ~L#HPH25.BCS extended with All_NPC_JOIN.baf
	~
  END

