/////////////////////////// Mods BG1 ///////////////////////////

/////////////// Reset

// BG1
OUTER_SPRINT "BG1_JOINED" ""
OUTER_SPRINT "BG1_BCS" ""
OUTER_SPRINT "BG1_BANTER" ""
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
	OUTER_SPRINT "SoD_JOINED" ""
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""
		// BG2
		OUTER_SPRINT "BG2_JOINED" ""
		OUTER_SPRINT "BG2_BCS" ""
		OUTER_SPRINT "BG2_BANTER" ""
		OUTER_SPRINT "BG2_DREAM" ""
			// ToB
			OUTER_SPRINT "TOB_JOINED" ""
			OUTER_SPRINT "TOB_BCS" ""
			OUTER_SPRINT "TOB_BANTER" ""
			OUTER_SPRINT "TOB_DREAM" ""

/////////////////////////// Ishlilka ///////////////////////////

/*OUTER_SPRINT "Death_var" "#Ishy"*/

// BG1
OUTER_SPRINT "BG1_JOINED" "IshyD"
OUTER_SPRINT "BG1_BCS" "ishyscrp"
OUTER_SPRINT "BG1_BANTER" "BISHY"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" "IshyD"
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" "bdishy"
		END
	OUTER_SPRINT "SoD_BCS" "ishyscrp"
	OUTER_SPRINT "SoD_BANTER" "BISHY"
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Ishlilka ~ishyscrp~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/#Ishy_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

/////////////////////////// ChaosKnight ///////////////////////////

// BG1
OUTER_SPRINT "BG1_JOINED" "ZYJCOBJ"
OUTER_SPRINT "BG1_BCS" "ZYJCOB"
OUTER_SPRINT "BG1_BANTER" ""
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Jacob ~ZYJCOB~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/ZYJCOB_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

/////////////////////////// Askaria-Quest ///////////////////////////

// BG1
OUTER_SPRINT "BG1_JOINED" "ZYASKAJ"
OUTER_SPRINT "BG1_BCS" "ZYASKA"
OUTER_SPRINT "BG1_BANTER" ""
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Askaria ~ZYASKA~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/ZYASKA_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

/////////////////////////// Isra BG1 ///////////////////////////

// BG1
OUTER_SPRINT "BG1_JOINED" "RH#ISRAJ"
OUTER_SPRINT "BG1_BCS" "RH#ISRA"
OUTER_SPRINT "BG1_BANTER" "BRH#ISRA"
OUTER_SPRINT "BG1_DREAM" "RH#ISRAD"
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Isra_BG1 ~RH#ISRA~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/rh#isra_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

/////////////////////////// Finch ///////////////////////////

// BG1
OUTER_SPRINT "BG1_JOINED" "SUFINCHJ"
OUTER_SPRINT "BG1_BCS" "SUFINCH"
OUTER_SPRINT "BG1_BANTER" "BSUFINCH"
OUTER_SPRINT "BG1_DREAM" "SUFINCHD"
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Finch ~SUFINCH~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/SUFINCH_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

/////////////////////////// Drizzt Saga ///////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~F_JARLAX.cre~ BEGIN
		COPY_EXISTING ~F_JARLAX.CRE~ ~override/F_JARLAX.CRE~
		WRITE_ASCII SCRIPT_OVERRIDE ~F_JARLAX~ (8)
		WRITE_ASCII SCRIPT_CLASS ~~ (8)
	END

// BG1
OUTER_SPRINT "BG1_JOINED" "F_JARLAJ"
OUTER_SPRINT "BG1_BCS" "F_JARLAX"
OUTER_SPRINT "BG1_BANTER" "F_JARLAB"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Jarlaxle_Saga ~F_JARLAX~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/F_JARLAXE_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

ACTION_IF FILE_EXISTS_IN_GAME ~F_ARTEMI.cre~ BEGIN
		COPY_EXISTING ~F_ARTEMI.CRE~ ~override/F_ARTEMI.CRE~
		WRITE_ASCII SCRIPT_OVERRIDE ~F_ASSASI~ (8)
		WRITE_ASCII SCRIPT_CLASS ~~ (8)
	END

// BG1
OUTER_SPRINT "BG1_JOINED" "F_ARTEMJ"
OUTER_SPRINT "BG1_BCS" "F_ASSASI"
OUTER_SPRINT "BG1_BANTER" "F_ARTEMB"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Artemis_Enteri_Saga ~F_ASSASI~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/F_ARTEMIS_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// BG1
OUTER_SPRINT "BG1_JOINED" "F_CATTIJ"
OUTER_SPRINT "BG1_BCS" "F_CATTIB"
OUTER_SPRINT "BG1_BANTER" "F_CATTIB"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Catti-Brie_Saga ~F_CATTIB~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/F_CATTIBR_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// BG1
OUTER_SPRINT "BG1_JOINED" "F_BRUENJ"
OUTER_SPRINT "BG1_BCS" "F_BRUENO"
OUTER_SPRINT "BG1_BANTER" "F_BRUENB"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Bruenor_Saga ~F_BRUENO~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/F_BRUENOR_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// BG1
OUTER_SPRINT "BG1_JOINED" "F_REGISJ"
OUTER_SPRINT "BG1_BCS" "F_REGIS2"
OUTER_SPRINT "BG1_BANTER" "F_REGISB"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Regis_Saga ~F_REGIS2~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/F_REGIS_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// BG1
OUTER_SPRINT "BG1_JOINED" "F_DRIZTJ"
OUTER_SPRINT "BG1_BCS" "F_DRIZZT"
OUTER_SPRINT "BG1_BANTER" "F_DRIZTB"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Drizzt_Saga ~F_DRIZZT~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/F_DRIZZT_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// BG1
OUTER_SPRINT "BG1_JOINED" "F_WULFGJ"
OUTER_SPRINT "BG1_BCS" "F_WULFGA"
OUTER_SPRINT "BG1_BANTER" "F_WULFGB"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Wulfgar_Saga ~F_WULFGA~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/F_WULFGAR_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

/////////////////////////// Dark Horizons ///////////////////////////

// BG1
OUTER_SPRINT "BG1_JOINED" "CMTTHORJ"
OUTER_SPRINT "BG1_BCS" "CMTTHOR"
OUTER_SPRINT "BG1_BANTER" "BCMTTHOR"
OUTER_SPRINT "BG1_DREAM" "CMTTHORD"
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Thorin ~cmtthor~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/CMTTHOR_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// BG1
OUTER_SPRINT "BG1_JOINED" "CMTMORWJ"
OUTER_SPRINT "BG1_BCS" "CMTMORW"
OUTER_SPRINT "BG1_BANTER" "BCMTMORW"
OUTER_SPRINT "BG1_DREAM" "CMTMORWD"
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Morwen ~cmtmorw~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/CMTMORW_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

/////////////////////////// DSotSC ///////////////////////////

// BG1
OUTER_SPRINT "BG1_JOINED" "BARDOJ"
OUTER_SPRINT "BG1_BCS" "DSBARDO"
OUTER_SPRINT "BG1_BANTER" "BBARDO"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Bardo ~DSBARDO~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/DSBARDO_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// BG1
OUTER_SPRINT "BG1_JOINED" "BUBJ"
OUTER_SPRINT "BG1_BCS" "DSBUB"
OUTER_SPRINT "BG1_BANTER" "BBUB"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Bub_Snikt ~DSBUB~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/DSBUB_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// BG1
OUTER_SPRINT "BG1_JOINED" "CONCHOJ"
OUTER_SPRINT "BG1_BCS" "DSCONCHO"
OUTER_SPRINT "BG1_BANTER" "BCONCHO"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Conchobhair ~dsconcho~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Conchobhair_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// BG1
OUTER_SPRINT "BG1_JOINED" "CUCHOINJ"
OUTER_SPRINT "BG1_BCS" "DSCUCHO"
OUTER_SPRINT "BG1_BANTER" "BCUCHOI"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod CuChoinneach ~dscucho~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/CuChoinneach_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// BG1
OUTER_SPRINT "BG1_JOINED" "FERTHJ"
OUTER_SPRINT "BG1_BCS" "DSFERTH"
OUTER_SPRINT "BG1_BANTER" "BFERTHG"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Ferthgil_Trollslayer ~dsferth~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Ferthgil_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// BG1
OUTER_SPRINT "BG1_JOINED" "JETLAJ"
OUTER_SPRINT "BG1_BCS" "dsjetla"
OUTER_SPRINT "BG1_BANTER" "BJETLA"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Jet'laya ~dsjetla~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/JETLAYA_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// BG1
OUTER_SPRINT "BG1_JOINED" "KEIRIJ"
OUTER_SPRINT "BG1_BCS" "DSKEIRI"
OUTER_SPRINT "BG1_BANTER" "BKEIRIA"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Keiria_Silverstring ~dskeiri~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/KEIRIA_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// BG1
OUTER_SPRINT "BG1_JOINED" "SKEEZJ"
OUTER_SPRINT "BG1_BCS" "DSSKEEZ"
OUTER_SPRINT "BG1_BANTER" "BSKEEZE"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Skeezer_Lumpkin_VI ~dsskeez~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/SKEEZER_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// BG1
OUTER_SPRINT "BG1_JOINED" "THORFJ"
OUTER_SPRINT "BG1_BCS" "DSTHORF"
OUTER_SPRINT "BG1_BANTER" "BTHORF"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Thorfinn_Hauskluniff ~dsthorf~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Thorfinn_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

/////////////////////////// NTotSC ///////////////////////////

ACTION_IF FILE_EXISTS_IN_GAME ~ntwill2.cre~ BEGIN
		COPY_EXISTING ~ntwill2.CRE~ ~override/ntwill2.CRE~
		WRITE_ASCII SCRIPT_OVERRIDE ~ntwill~ (8)
		WRITE_ASCII SCRIPT_DEFAULT ~INITDLG~ (8)
	END
ACTION_IF FILE_EXISTS_IN_GAME ~ntwill4.cre~ BEGIN
		COPY_EXISTING ~ntwill4.CRE~ ~override/ntwill4.CRE~
		WRITE_ASCII SCRIPT_OVERRIDE ~ntwill~ (8)
		WRITE_ASCII SCRIPT_DEFAULT ~INITDLG~ (8)
	END
ACTION_IF FILE_EXISTS_IN_GAME ~ntwill6.cre~ BEGIN
		COPY_EXISTING ~ntwill6.CRE~ ~override/ntwill6.CRE~
		WRITE_ASCII SCRIPT_OVERRIDE ~ntwill~ (8)
		WRITE_ASCII SCRIPT_DEFAULT ~INITDLG~ (8)
	END

COPY ~JOining_Party_Select/Baf/JO_JOIN/EMPTY.baf~ ~override/ntwill.bcs~

// BG1
OUTER_SPRINT "BG1_JOINED" "WILLJ"
OUTER_SPRINT "BG1_BCS" "NTWILL"
OUTER_SPRINT "BG1_BANTER" "BWILL"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Will_Scarlet ~ntwill~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/WILL_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// Valerie

// BG1
OUTER_SPRINT "BG1_JOINED" "T2VALJ"
OUTER_SPRINT "BG1_BCS" "T2VAL"
OUTER_SPRINT "BG1_BANTER" "BT2VAL"
OUTER_SPRINT "BG1_DREAM" "T2VALD"
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Valerie ~T2VAL~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/T2VAL_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// Indira

// BG1
OUTER_SPRINT "BG1_JOINED" "J#IndiJ"
OUTER_SPRINT "BG1_BCS" "J#Indi"
OUTER_SPRINT "BG1_BANTER" "J#IndiB"
OUTER_SPRINT "BG1_DREAM" "J#IndiD"
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Indira ~J#Indi~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/J#Indi_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// Bristlelick

// BG1
OUTER_SPRINT "BG1_JOINED" "L#BRISTJ"
OUTER_SPRINT "BG1_BCS" "L#BRIST"
OUTER_SPRINT "BG1_BANTER" "L#BRISTB"
OUTER_SPRINT "BG1_DREAM" "L#BRISTD"
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" "L#BRISTJ"
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" "L#2BRISJ"
		END
	OUTER_SPRINT "SoD_BCS" "L#2BRIST"
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" "L#2BRISD"

ACTION_FOR_EACH bcs IN

// Mod Bristlelick ~L#BRIST~ ~L#2BRIST~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/L#BRIST_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// Glam's npc pack

// BG1
OUTER_SPRINT "BG1_JOINED" "GV#DAVEJ"
OUTER_SPRINT "BG1_BCS" "GV#DAVE"
OUTER_SPRINT "BG1_BANTER" "BGV#DAVE"
OUTER_SPRINT "BG1_DREAM" "GV#DAVED"
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Dave ~GV#DAVE~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/GV#DAVE_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// BG1
OUTER_SPRINT "BG1_JOINED" "GV#FLARJ"
OUTER_SPRINT "BG1_BCS" "GV#FLAR"
OUTER_SPRINT "BG1_BANTER" "BGV#FLAR"
OUTER_SPRINT "BG1_DREAM" "GV#FLARD"
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Flara ~GV#FLAR~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/GV#FLAR_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// BG1
OUTER_SPRINT "BG1_JOINED" "GV#LITTJ"
OUTER_SPRINT "BG1_BCS" "GV#LITT"
OUTER_SPRINT "BG1_BANTER" "BGV#LITT"
OUTER_SPRINT "BG1_DREAM" "GV#LITTD"
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Littlun ~GV#LITT~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/GV#LITT_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// BG1
OUTER_SPRINT "BG1_JOINED" "GV#MOIDJ"
OUTER_SPRINT "BG1_BCS" "GV#MOID"
OUTER_SPRINT "BG1_BANTER" "BGV#MOID"
OUTER_SPRINT "BG1_DREAM" "GV#MOIDD"
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Moidre ~GV#MOID~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/GV#MOID_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// BG1
OUTER_SPRINT "BG1_JOINED" "GV#VYNDJ"
OUTER_SPRINT "BG1_BCS" "GV#VYND"
OUTER_SPRINT "BG1_BANTER" "BGV#VYND"
OUTER_SPRINT "BG1_DREAM" "GV#VYNDD"
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Vynd ~GV#VYND~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/GV#VYND_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// Kale BG1

// BG1
OUTER_SPRINT "BG1_JOINED" "X3KaleJ"
OUTER_SPRINT "BG1_BCS" "X3Kale"
OUTER_SPRINT "BG1_BANTER" "X3KaleB"
OUTER_SPRINT "BG1_DREAM" "X3KaleD"
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" "X3KaleJ"
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" "X32KaleJ"
		END
	OUTER_SPRINT "SoD_BCS" "X32Kale"
	OUTER_SPRINT "SoD_BANTER" "X32KaleB"
	OUTER_SPRINT "SoD_DREAM" "X32KaleD"

ACTION_FOR_EACH bcs IN

// Mod Kale_BG1 ~X3Kale~ ~X32Kale~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/X3Kale_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// New Tales of the Sword Coast

// BG1
OUTER_SPRINT "BG1_JOINED" "KasandrJ"
OUTER_SPRINT "BG1_BCS" "Kasandra"
OUTER_SPRINT "BG1_BANTER" "KasandrB"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Kasandra ~Kasandra~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Kasandra_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// BG1
OUTER_SPRINT "BG1_JOINED" "MasambeJ"
OUTER_SPRINT "BG1_BCS" "Masambe"
OUTER_SPRINT "BG1_BANTER" "MasambeB"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Masambe ~Masambe~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Masambe_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// BG1
OUTER_SPRINT "BG1_JOINED" "AlethraJ"
OUTER_SPRINT "BG1_BCS" "Alethra"
OUTER_SPRINT "BG1_BANTER" "AlethraB"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Alethra ~Alethra~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Alethra_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// BG1
OUTER_SPRINT "BG1_JOINED" "RimardoJ"
OUTER_SPRINT "BG1_BCS" "Rimardo"
OUTER_SPRINT "BG1_BANTER" "RimardoB"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Rimardo ~Rimardo~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Rimardo_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// BG1
OUTER_SPRINT "BG1_JOINED" "TalindraJ"
OUTER_SPRINT "BG1_BCS" "Talindra"
OUTER_SPRINT "BG1_BANTER" "TalindraB"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Talindra ~Talindra~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Talindra_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// BG1
OUTER_SPRINT "BG1_JOINED" "TheodorJ"
OUTER_SPRINT "BG1_BCS" "Theodor"
OUTER_SPRINT "BG1_BANTER" "TheodorB"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Theodor ~Theodor~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Theodor_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// BG1
OUTER_SPRINT "BG1_JOINED" "AriadneJ"
OUTER_SPRINT "BG1_BCS" "Ariadne"
OUTER_SPRINT "BG1_BANTER" "AriadneB"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Ariadne ~Ariadne~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Ariadne_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// BG1
OUTER_SPRINT "BG1_JOINED" "NathanJ"
OUTER_SPRINT "BG1_BCS" "Nathan"
OUTER_SPRINT "BG1_BANTER" "NathanB"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Nathan ~Nathan~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Nathan_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// BG1
OUTER_SPRINT "BG1_JOINED" "NamiirJ"
OUTER_SPRINT "BG1_BCS" "Namiir"
OUTER_SPRINT "BG1_BANTER" "NamiirB"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Namiir ~Namiir~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Namiir_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// BG1
OUTER_SPRINT "BG1_JOINED" "MirandaJ"
OUTER_SPRINT "BG1_BCS" "Miranda"
OUTER_SPRINT "BG1_BANTER" "MirandaB"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
		END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Miranda ~Miranda~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Miranda_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// Walahnan

// BG1
OUTER_SPRINT "BG1_JOINED" "L#WALAHJ"
OUTER_SPRINT "BG1_BCS" "L#WALAH"
OUTER_SPRINT "BG1_BANTER" "L#WALAHB"
OUTER_SPRINT "BG1_DREAM" "L#WALAHD"
	// SoD
		ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" "L#WALAHJ"
		END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" "L#SWALAJ"
		END
	OUTER_SPRINT "SoD_BCS" "L#SWALAH"
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" "L#SWALAD"

ACTION_FOR_EACH bcs IN

// Mod Walahnan ~L#WALAH~ ~L#SWALAH~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/L#WALAH_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// Aerie in BG:EE

// BG1
OUTER_SPRINT "BG1_JOINED" "B2#AeriJ"
OUTER_SPRINT "BG1_BCS" "B2#Aeri2"
OUTER_SPRINT "BG1_BANTER" ""
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
	ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "SoD_JOINED" "B2#AeriJ"
	END ELSE BEGIN
	OUTER_SPRINT "SoD_JOINED" ""
	END
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Aerie_BG1 ~B2#Aeri2~ ~~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/B2#Aeri_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

// Next_Traveler BG1






