// JOining_Party_End.tph

// Compatiblity with transition mods

		INCLUDE ~JOining_Party_Select/Campaign_Transition/BG1_to_SoD_compat.tph~

//////////////////////////////////////////////////////////////////////////////////////

COPY_EXISTING_REGEXP GLOB ~.*\.are~ ~override~
//			PATCH_IF (~%SOURCE_RES%~ STR_CMP ~~) AND (NOT ~%SOURCE_RES%~ STR_EQ ~NONE~) BEGIN
//				WRITE_ASCIIE 0x94 ~%SOURCE_RES%~ #8
//						PATCH_PRINT ~%SOURCE_FILE% - Area script not assigned~
//			END
//			PATCH_IF (!FILE_EXISTS_IN_GAME ~%SOURCE_RES%.bcs~) BEGIN
//				PATCH_PRINT ~%SOURCE_RES% - Missing area script~
//					INNER_ACTION BEGIN
//				COPY ~JOining_Party_Select/Baf/blank.bcs~ ~override/%SOURCE_RES%.BCS~
//					END
//			END
			PATCH_IF (SOURCE_SIZE > 0x11b) AND (RESOURCE_CONTAINS ~mastarea.2da~ ~%SOURCE_RES%~) AND NOT (~%SOURCE_RES%~ STRING_EQUAL_CASE ~XG0319~) OR (SOURCE_SIZE > 0x11b) AND (RESOURCE_CONTAINS ~SODMAREA.2da~ ~%SOURCE_RES%~) AND NOT (~%SOURCE_RES%~ STRING_EQUAL_CASE ~XG0319~) BEGIN
				LPF fj_are_structure
					INT_VAR
					fj_variable_value = 1
					STR_VAR
					fj_structure_type = "variable"
					fj_name           = "JO_JOIN_AREA"
				END
			END
// INNER_ACTION BEGIN APPEND ~MASTAREA.2da~ ~%SOURCE_RES% value~ UNLESS ~%SOURCE_RES%~ END
				PATCH_PRINT ~... // %SOURCE_RES% is in mastarea.2da or sodmarea.2da
				Adding Global("JO_JOIN_AREA","MYAREA",1)
						~
//			PATCH_IF (SOURCE_SIZE > 0x11b) AND NOT (RESOURCE_CONTAINS ~mastarea.2da~ ~%SOURCE_RES%~) AND NOT (~%SOURCE_RES%~ STRING_EQUAL_CASE ~XG0319~) BEGIN
//					INNER_ACTION BEGIN
//				EXTEND_TOP ~%SOURCE_RES%.bcs~ ~JOining_Party_Select/Baf/SetMasterArea.baf~
//					END
//			END
			READ_LONG 0x14 flag
			PATCH_IF (SOURCE_SIZE > 0x11b) AND (flag BAND BIT0) AND NOT (~%SOURCE_RES%~ STRING_EQUAL_CASE ~XG0319~) BEGIN
				LPF fj_are_structure
					INT_VAR
					fj_variable_value = 1
					STR_VAR
					fj_structure_type = "variable"
					fj_name           = "JO_JOIN_NOSAVE"
				END
					PATCH_PRINT ~... // %SOURCE_RES% is a no save area
					Adding Global("JO_JOIN_NOSAVE","MYAREA",1)
						~
/*				PATCH_IF NOT (~%SOURCE_RES%.bcs~ STRING_EQUAL_CASE ~~) AND (FILE_EXISTS_IN_GAME ~%SOURCE_RES%.bcs~) BEGIN
					PATCH_PRINT ~... // %SOURCE_RES% have area script
						~
					INNER_ACTION BEGIN
						COPY_EXISTING_REGEXP ~%SOURCE_RES%.bcs~ ~override~
							DECOMPILE_AND_PATCH BEGIN
								SPRINT textToReplace ~RemoveAreaFlag(NOSAVE)~
								COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
									PATCH_IF (num_matches > 0) BEGIN
										REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~SetGlobal("JO_JOIN_SAVE_AREA","MYAREA",1)
									\0~
										PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
										PATCH_PRINT ~... // RemoveAreaFlag(NOSAVE) found in %SOURCE_FILESPEC%
										~
									END ELSE BEGIN
										PATCH_PRINT ~...%SOURCE_FILESPEC% don't have // RemoveAreaFlag(NOSAVE) ...No need patching.
										~
									END
								SPRINT textToReplace ~AddAreaFlag(NOSAVE)~
								COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
									PATCH_IF (num_matches > 0) BEGIN
										REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~SetGlobal("JO_JOIN_SAVE_AREA","MYAREA",0)
									\0~
										PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
										PATCH_PRINT ~... // AddAreaFlag(NOSAVE) found in %SOURCE_FILESPEC%
										~
									END ELSE BEGIN
										PATCH_PRINT ~...%SOURCE_FILESPEC% don't have // AddAreaFlag(NOSAVE) ...No need patching.
										~
									END
							END
					END
				END ELSE BEGIN
										PATCH_PRINT ~...%SOURCE_FILESPEC% don't have area script...No need patching.
										~
				END
			END ELSE PATCH_IF NOT (~%SOURCE_RES%.bcs~ STRING_EQUAL_CASE ~~) AND (FILE_EXISTS_IN_GAME ~%SOURCE_RES%.bcs~) BEGIN
						INNER_ACTION BEGIN
							COPY_EXISTING_REGEXP ~%SOURCE_RES%.bcs~ ~override~
								DECOMPILE_AND_PATCH BEGIN
									SPRINT textToReplace ~AddAreaFlag(NOSAVE)~
									COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
									PATCH_IF (num_matches > 0) BEGIN
										REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~SetGlobal("JO_JOIN_NOSAVE","MYAREA",1)
									\0~
										PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
										PATCH_PRINT ~... // AddAreaFlag(NOSAVE) found in %SOURCE_FILESPEC%
										~
									END
									SPRINT textToReplace ~RemoveAreaFlag(NOSAVE)~
									COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
									PATCH_IF (num_matches > 0) BEGIN
										REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~SetGlobal("JO_JOIN_NOSAVE","MYAREA",0)
									\0~
										PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
										PATCH_PRINT ~... // RemoveAreaFlag(NOSAVE) found in %SOURCE_FILESPEC%
										~
									END
								END
						END*/
			END
BUT_ONLY

// JO2608.are (Switching room)
COPY ~JOining_Party_Select/Are~ ~override~

	ACTION_IF !FILE_EXISTS_IN_GAME ~AM0604A.BAM~ THEN BEGIN
COPY ~JOining_Party_Select/Are/Bam/AM0604A.BAM~ ~override~
	END

APPEND ~MASTAREA.2da~ ~JO2608 value~ UNLESS ~JO2608~

	ACTION_IF FILE_EXISTS_IN_GAME ~SODMAREA.2da~ THEN BEGIN
APPEND ~SODMAREA.2da~ ~JO2608 value~ UNLESS ~JO2608~
	END

	COPY_EXISTING ~JO2608.are~ ~override~
		WRITE_ASCII 0x94 ~JO2608~ #8
		WRITE_LONG  0x14 (THIS BAND BNOT BIT0)
		WRITE_LONG  0x14 (THIS BAND BNOT BIT2)
		WRITE_LONG  0x14 (THIS BAND BNOT BIT5)
		WRITE_LONG  0x48 THIS | BIT7
		WRITE_SHORT  0x4e ~100~
		ADD_MAP_NOTE #1894 #1155 ~gray~ ~Travelers Items~


	COPY_EXISTING ~JO2608.wed~ ~override~
		WRITE_ASCII 0x24 ~JO2608~ (8)

//////////////////////////////////////////////////////////////////////////////////////

// Special JOJOINNE

	INCLUDE ~weidu_external/JOining_Party_Select/JOining_Party_JOJOINNE.tph~

//////////////////////////////////////////////////////////////////////////////////////



//////////////////////////////////////////////////////////////////////////////////////

// CutSceneBreakable
ACTION_FOR_EACH bcs IN cutskip cutskip1 cutskip2 BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ THEN BEGIN
	  COPY_EXISTING_REGEXP ~%bcs%.bcs~ ~override~
		DECOMPILE_AND_PATCH BEGIN
	// SetCutSceneBreakable situation
			SPRINT textToReplace ~\(SetCutSceneBreakable(FALSE)\)~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) /*AND (~%SOURCE_FILESPEC%~ STRING_EQUAL_CASE ~cutskip.bcs~) OR (~%SOURCE_FILESPEC%~ STRING_EQUAL_CASE ~cutskip1.bcs~) OR (~%SOURCE_FILESPEC%~ STRING_EQUAL_CASE ~cutskip2.bcs~)*/ BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~SetGlobal("JO_JOIN_CUTSCENE","GLOBAL",0)
	SetCutSceneBreakable(FALSE)~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // SetCutSceneBreakable(FALSE) found in %SOURCE_FILESPEC%
				~
			END
		END
			BUT_ONLY
	END

END // ACTION_FOR_EACH // SetCutSceneBreakable

// BG2 party clones in random area
ACTION_IF GAME_IS ~bg2ee bgt eet~ BEGIN
	ACTION_FOR_EACH bcs IN AR0041 AR0042 AR0043 AR0044 AR0045 AR0046 BEGIN

		ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ THEN BEGIN
		  COPY_EXISTING_REGEXP ~%bcs%.bcs~ ~override~
			DECOMPILE_AND_PATCH BEGIN
	// RERAK02 situation
				SPRINT textToReplace ~^[%TAB% ]*CreateCreature("RERAK02",\[500\.454\],\([^)]*\))~
				COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
				PATCH_IF (num_matches > 0) BEGIN
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~\0 CreateCreature("JORAK00",[600.400],10)~
					PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
					PATCH_PRINT ~... // RERAK02 found in %SOURCE_FILESPEC%
					~
				END
			END
				BUT_ONLY
		END
	END // ACTION_FOR_EACH // RERAK02

	COPY_EXISTING ~RERAK02.CRE~ ~override/JORAK00.CRE~
		WRITE_ASCII SCRIPT_OVERRIDE ~JORAK00~ (8)
		WRITE_ASCII DEATHVAR ~JORAK00~ (32)
		WRITE_BYTE 0x272 1
		WRITE_BYTE 0x273 155
	COPY_EXISTING ~RERAK01.CRE~ ~override/JORAK01.CRE~
		WRITE_ASCII SCRIPT_OVERRIDE ~JORAK07~ (8)
		WRITE_ASCII DEATHVAR ~JORAK01~ (32)
	COPY_EXISTING ~RERAK02.CRE~ ~override/JORAK02.CRE~
		WRITE_ASCII SCRIPT_OVERRIDE ~JORAK07~ (8)
		WRITE_ASCII DEATHVAR ~JORAK02~ (32)
	COPY_EXISTING ~RERAK03.CRE~ ~override/JORAK03.CRE~
		WRITE_ASCII SCRIPT_OVERRIDE ~JORAK07~ (8)
		WRITE_ASCII DEATHVAR ~JORAK03~ (32)
	COPY_EXISTING ~RERAK04.CRE~ ~override/JORAK04.CRE~
		WRITE_ASCII SCRIPT_OVERRIDE ~JORAK07~ (8)
		WRITE_ASCII DEATHVAR ~JORAK04~ (32)
	COPY_EXISTING ~RERAK05.CRE~ ~override/JORAK05.CRE~
		WRITE_ASCII SCRIPT_OVERRIDE ~JORAK07~ (8)
		WRITE_ASCII DEATHVAR ~JORAK05~ (32)
	COPY_EXISTING ~RERAK06.CRE~ ~override/JORAK06.CRE~
		WRITE_ASCII SCRIPT_OVERRIDE ~JORAK07~ (8)
		WRITE_ASCII DEATHVAR ~JORAK06~ (32)


		EXTEND_BOTTOM ~JORAK00.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/JORAK00.baf~ EVALUATE_BUFFER


END // GAME_IS ~bg2ee bgt eet~


	ACTION_FOR_EACH bcs IN BDBALDUR BDELEV02 BDEXITBF BDNORES2 HELLPOOL BEGIN

		ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ THEN BEGIN
		  COPY_EXISTING_REGEXP ~%bcs%.bcs~ ~override~
			DECOMPILE_AND_PATCH BEGIN
	// IsOverMe situation
				SPRINT textToReplace ~^[%TAB% ]*OR(6)
^[%TAB% ]*IsOverMe(Player1)~
				COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
				PATCH_IF (num_matches > 0) /*AND (~%SOURCE_FILESPEC%~ STRING_EQUAL_CASE ~BALDUR.bcs~)*/ BEGIN
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~OR(7)
IsOverMe(Familiar)
IsOverMe(Player1)~
					PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
					PATCH_PRINT ~... // %Death_var% : OR(6) IsOverMe found in %SOURCE_FILESPEC%
					~
				END
			END
				BUT_ONLY
		END
	END // ACTION_FOR_EACH // CreateVisualEffectObject


// Lilarcor
	ACTION_FOR_EACH bcs IN BALDUR BALDUR25 BDBALDUR BEGIN

		ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ THEN BEGIN
		  COPY_EXISTING_REGEXP ~%bcs%.bcs~ ~override~
			DECOMPILE_AND_PATCH BEGIN
	// Lilarcor situation
				SPRINT textToReplace ~^[%TAB% ]*OR(6)
^[%TAB% ]*HasItemEquipedReal(\([^)]*\),Player1)~
				COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
				PATCH_IF (num_matches > 0) BEGIN
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~OR(7)
HasItemEquipedReal(\1,Familiar)
HasItemEquipedReal(\1,Player1)~
					PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
					PATCH_PRINT ~... // %Death_var% : OR(6) HasItemEquipedReal found in %SOURCE_FILESPEC%
					~
				END
			END
				BUT_ONLY
		END
	END // ACTION_FOR_EACH // CreateVisualEffectObject

//////////////////////////////////////////////////////////////////////////////////////

	ACTION_FOR_EACH bcs IN IWSHCUT1 IDSHCUT1 BDCUT62 BEGIN // K#TELBGT AR0602 BD0103

		ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ THEN BEGIN
		  COPY_EXISTING_REGEXP ~%bcs%.bcs~ ~override~
			DECOMPILE_AND_PATCH BEGIN
	// TakeCreatureItems situation
				SPRINT textToReplace ~^[%TAB% ]*ActionOverride(\([^)]*\),TakeCreatureItems(Player4,\([^)]*\)))~
				COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
				PATCH_IF (num_matches > 0) AND (~%SOURCE_FILESPEC%~ STRING_EQUAL_CASE ~BDCUT62.bcs~) BEGIN
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~\0
					SetGlobal("JO_JOIN_SCRIPT","GLOBAL",1)
					SetGlobal("JO_JOIN_BDCUT62","GLOBAL",1)~
					PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace
					~
				END
				PATCH_IF (num_matches > 0) AND (~%SOURCE_FILESPEC%~ STRING_EQUAL_CASE ~IWSHCUT1.bcs~) BEGIN
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~\0
					SetGlobal("JO_JOIN_SCRIPT","GLOBAL",1)
					SetGlobal("JO_JOIN_IWSHCUT1","GLOBAL",1)~
					PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace
					~
				END
				PATCH_IF (num_matches > 0) AND (~%SOURCE_FILESPEC%~ STRING_EQUAL_CASE ~IDSHCUT1.bcs~) BEGIN
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~\0
					SetGlobal("JO_JOIN_SCRIPT","GLOBAL",1)
					SetGlobal("JO_JOIN_IDSHCUT1","GLOBAL",1)~
					PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace
					~
				END
			END
			BUT_ONLY
		END
	END // ACTION_FOR_EACH // TakeCreatureItems

///////////////////////////////////////////////////////////////////////////////

// Special expand script at installation move in weidu_external before ACTION_FOR_EACH

///////////////////////////////////////////////////////////////////////////////

// Loading Switch
COPY ~JOining_Party_Select/Baf/Join_ability/JO_JOINL.baf~ ~weidu_external/JOining_Party_Select/Join_ability/JO_JOINL.baf~

// Charname override script JO_JOINP.baf
COPY ~JOining_Party_Select/Baf/Join_ability/JO_JOINP.baf~ ~weidu_external/JOining_Party_Select/Join_ability/JO_JOINP.baf~

// JO_JOIN_COUNT_TRAVELER for JO_JOINC.baf
COPY ~JOining_Party_Select/Baf/Join_ability/JO_JOINC.baf~ ~weidu_external/JOining_Party_Select/Join_ability/JO_JOINC.baf~


ACTION_FOR_EACH Death_var IN

// Original Imoen                ~%IMOEN_DV%~ // ImoenIren ~Imoen~ // ~ttimoen~     // Imoen
// Original Edwin                ~Edwin~                                            // Edwin
// Original Jaheira              ~Jaheira~                         // ~ttjaheir~    // Jaheira
// Original Minsc                ~Minsc~                           // ~ttminsc~     // Minsc
// Original Viconia              ~Viconia~                                          // Viconia
// Original Dorn                 ~Dorn~                                             // Dorn
// Original Neera                ~Neera~                                            // Neera
// Original Rasaad               ~Rasaad~                                           // Rasaad


/////////////////////////// BG1 ///////////////////////////

// Original Ajantis              ~Ajantis~                                          // Ajantis
// Original Alora                ~Alora~                                            // Alora
// Original Branwen              ~Branwen~                         // ~ttbran~      // Branwen
// Original Coran                ~Coran~                                            // Coran
// Original Dynaheir             ~Dynaheir~                                         // Dynaheir

// Original Eldoth               ~Eldoth~                                           // Eldoth
// Original Faldorn              ~Faldorn~                                          // Faldorn
// Original Garrick              ~Garrick~                                          // Garrick

// Original Kagain               ~Kagain~                                           // Kagain
// Original Khalid               ~Khalid~                                           // Khalid
// Original Kivan                ~Kivan~                                            // Kivan

// Original Montaron             ~Montaron~                                         // Montaron
// Original Quayle               ~Quayle~                                           // Quayle
// Original Safana               ~Safana~                                           // Safana
// Original Sharteel             ~Sharteel~                        // ~Shar-teel~   // Sharteel
// Original Skie                 ~Skie~                                             // Skie
// Original Tiax                 ~Tiax~                                             // Tiax

// Original Xan                  ~Xan~                             // ttxan~        // Xan
// Original Xzar                 ~Xzar~                                             // Xzar
// Original Yeslick              ~Yeslick~                                          // Yeslick

// Original Baeloth              ~Baeloth~                                          // Baeloth


/////////////////////////// SoD ///////////////////////////

// Original Voghiln              ~Voghiln~                                          // Voghiln
// Original Corwin               ~Corwin~                                           // Corwin
// Original Mkhiin               ~Mkhiin~                                           // Mkhiin
// Original Glint                ~Glint~                                            // Glint


/////////////////////////// BG2 ///////////////////////////

// Original Aerie                ~Aerie~                                            // Aerie
// Original Anomen               ~Anomen~                                           // Anomen
// Original Cernd                ~Cernd~                                            // Cernd
// Original Haerdalis            ~Haerdalis~                                        // Haerdalis
// Original Hexxat               ~Hexxat~                                           // Hexxat
// Original Jan                  ~Jan~                                              // Jan
// Original Keldorn              ~Keldorn~                                          // Keldorn
// Original Korgan               ~Korgan~                                           // Korgan
// Original Mazzy                ~Mazzy~                                            // Mazzy
// Original Nalia                ~Nalia~                                            // Nalia
// Original Sarevok              ~Sarevok~                                          // Sarevok
// Original Valygar              ~Valygar~                                          // Valygar
// Original Wilson               ~Wilson~                                           // Wilson
// Original Yoshimo              ~Yoshimo~                                          // Yoshimo


/////////////////////////// Mods BG1 ///////////////////////////

// Ishlilka_The-Wizard-Slayer
// Mod Ishlilka                  ~#Ishy~                                            // Ishlilka

// ChaosKnight-kit
// Mod Jacob                     ~ZYJCOB~                                           // Jacob

// Askaria-Quest
// Mod Askaria                   ~ZYASKA~                                           // Askaria

// Isra BG1
// Mod Isra_BG1                  ~rh#isra~                                          // Isra

// Finch
// Mod Finch                     ~SUFINCH~                                          // Finch

// Drizzt Saga
// Mod Jarlaxle_Saga             ~F_JARLAXE~                                        // Jarlaxle
// Mod Artemis_Enteri_Saga       ~F_ARTEMIS~                                        // Artemis Enteri
// Mod Catti-Brie_Saga           ~F_CATTIBR~                                        // Catti-Brie
// Mod Bruenor_Saga              ~F_BRUENOR~                                        // Bruenor
// Mod Regis_Saga                ~F_REGIS~                                          // Regis
// Mod Drizzt_Saga               ~F_DRIZZT~                                         // Drizzt
// Mod Wulfgar_Saga              ~F_WULFGAR~                                        // Wulfgar

// Dark Horizons
// Mod Thorin                    ~CMTTHOR~                                          // Thorin
// Mod Morwen                     ~CMTMORW~                                         // Morwen

// DSotSC
// Mod Bardo                     ~DSBARDO~                                          // Bardo
// Mod Bub_Snikt                 ~DSBUB~                                            // Bub Snikt
// Mod Conchobhair               ~Conchobhair~                                      // Conchobhair
// Mod CuChoinneach              ~CuChoinneach~                                     // CuChoinneach
// Mod Ferthgil_Trollslayer      ~Ferthgil~                                         // Ferthgil Trollslayer
// Mod Jet'laya                  ~JETLAYA~                                          // Jet'laya
// Mod Keiria_Silverstring       ~KEIRIA~                                           // Keiria Silverstring
// Mod Skeezer_Lumpkin_VI        ~SKEEZER~                                          // Skeezer Lumpkin VI
// Mod Thorfinn_Hauskluniff      ~Thorfinn~                                         // Thorfinn Hauskluniff

// NTotSC
// Mod Will_Scarlet              ~WILL~                                             // Will Scarlet

// Valerie
// Mod Valerie                   ~T2VAL~

// Indira
// Mod Indira                    ~J#Indi~

// Bristlelick BG1 / SoD
// Mod Bristlelick               ~L#BRIST~

// Glam's npc pack
// Mod Dave                      ~GV#DAVE~
// Mod Flara                     ~GV#FLAR~
// Mod Littlun                   ~GV#LITT~
// Mod Moidre                    ~GV#MOID~
// Mod Vynd                      ~GV#VYND~

// Kale BG1
// Mod Kale_BG1                  ~X3Kale~

// New Tales of the Sword Coast
// Mod Kasandra                  ~Kasandra~
// Mod Masambe                   ~Masambe~
// Mod Alethra                   ~Alethra~
// Mod Rimardo                   ~Rimardo~
// Mod Talindra                  ~Talindra~
// Mod Theodor                   ~Theodor~
// Mod Ariadne                   ~Ariadne~
// Mod Nathan                    ~Nathan~
// Mod Namiir                    ~Namiir~
// Mod Miranda                   ~Miranda~

// Walahnan BG1 / SoD
// Mod Walahnan                  ~L#WALAH~

// Aerie in BG:EE
// Mod Aerie_BG1            ~B2#Aeri~

// Next_Traveler BG1


/////////////////////////// Mods BG2 ///////////////////////////

// Alora BG2
// Mod Alora BG2                 ~CMALORA~                                          // Alora

// Yeslick BG2
// Mod Yeslick BG2               ~LK#YESLK~                                         // Yeslick

// The Undying
// Mod Undying                   ~cmninaf~                                          // Ninafer
// Mod Undying                   ~callisto~                                         // Callisto

// Summon Bhaalspawn
// Mod Sandra                    ~BHAALSPW~                                         // Sandra

// VampireTales
// Mod Miriam                    ~cmgmiriam~                                        // Miriam

// Kim
// Mod Kim                       ~Kim~                                              // Kim

// Severian
// Mod Severian                  ~#Severian~                                        // Severian

// Frennedan
// Mod Frennedan                 ~Frennedan~                                        // Frennedan

// Branwen BG2
// Mod Branwen_BG2               ~O#Bran~                                           // Branwen
// Tiax BG2
// Mod Tiax_BG2                  ~O#Tiax~                                           // Tiax
// Xan BG2
// Mod Xan_BG2                   ~O#XAN~                                            // Xan
// Coran BG2
// Mod Coran_BG2                 ~O#Coran~                                          // Coran

// Auren Aseph
// Mod Auren                     ~K#AUREN~                                  // Auren

// Isra BG2
// Mod Isra_BG2                  ~rh#Isra2~                                 // Isra

// Nephele
// Mod Nephele_Samios            ~Nephele~                                  // Nephele

// Sheena
// Mod Sheena                    ~K#SHEENA~                                 // Sheena

// Kiara / Zaiya
// Mod Kiara                     ~Kiara~                                    // Kiara
// Mod Zaiya                     ~Zaiya~                                    // Zaiya

// The Beaurin Legacy
// Mod Minyae                    ~QI#MI~                                    // Minyae
// Mod Elaryn                    ~QI#ELA~                                   // Elaryn

// Tyris Flare
// Mod Tyris                     ~g#Tyris~                                  // Tyris

// Region of Terror
// Mod Wulfgar_Terror            ~Wulfg2~                                   // Wulfgar
// Mod Regis_Terror              ~Reg2~                                     // Regis
// Mod Drizzt_Terror             ~Driz2~                                    // Drizz
// Mod Bruenor_Terror            ~Brue2~                                    // Bruenor
// Mod Catti-Brie_Terror         ~Catt2~                                    // Catti-Brie
// Mod Artemis_Entreri_Terror    ~Enter2~                                   // Artemis
// Mod Jarlaxle_Terror           ~Jarlax2~                                  // Jarlaxle
// Mod Tapio_Perkiomaki_Terror   ~Tapio~                                    // Tapio
// Mod Randall_Terror            ~Randall~                                  // Randall
// Mod Alissa_Terror             ~ALISSA1~                                  // Alissa
// Mod Mordragon_Terror          ~Mordrg~                                   // Mordragon

//Shadow over Soubar
// Mod Selence_Hillstar_Soubar   ~SELENCE~                                  // Selence
// Mod Charlotte_Soubar          ~CHARLOTT~                                 // Charlotte
// Mod Bolivar_Soubar            ~BOLIVAR~                                  // Bolivar
// Mod Tomas_Tomalson_Soubar     ~TOMASTM~                                  // Tomas

// ajantisbg2
// Mod Ajantis_BG2               ~C#Ajantis~                                // Ajantis

// Kivan and Deheriana
// Mod Kivan_BG2                 ~P#KIVAN~                                  // Kivan
// Mod Deheriana                 ~P#DEHER~                                  // Deheriana

// Yvette
// Mod Yvette                    ~YxYve~

// The Luxley Family
// Mod Sebastian                ~fhlseb~
// Mod Andrei                   ~FHLAND~

//  Beyond the Law
// Mod Kiyone                   ~Kiyone~
// Mod Kova                     ~Kova~

// Petsy
// Mod Petsy                   ~L3PETSY~

// Kale BG2
// Mod Kale_BG2                ~X3Kal~

// Walahnan BG2
// Mod Walahnan_BG2            ~L#2WALAH~

// Autumns Twilight
// Mod Dusk                    ~P_Dusk~
// Mod Fall                    ~P_Fall~
// Mod Cho'Nuja                ~P_Chon~
// Mod Alendir                 ~P_Alen~

// Next_Traveler BG2


/////////////////////////// Mods Continuous ///////////////////////////

// EET Nikita                  ~cmnikita~                                   // Nikita

// EET Alora_Continuous        ~Alora~                                     // Alora_Continuous

// EET Ajantis_Continuous      ~Ajantis~                                   // Ajantis_Continuous

// EET Kivan_Continuous        ~Kivan~                                     // Kivan_Continuous

// EET Walahnan_Continuous     ~L#WALAH~                                   // Walahnan_Continuous

// EET Coran_Continuous        ~Coran~                                     // Coran_Continuous

// EET Yeslick_Continuous      ~Yeslick~                                   // Yeslick_Continuous

// EET Xan_Continuous          ~Xan~                                       // Xan_Continuous

// EET Branwen_Continuous      ~Branwen~                                   // Branwen_Continuous

// EET Tiax_Continuous         ~Tiax~                                      // Tiax_Continuous

// EET Isra_Continuous         ~rh#isra~                                  // Isra_Continuous

// Next_Traveler Continuous

BEGIN

//////////////////////////////////////////////////////////////////////////////////////


// JO_LOAD_TRAVELER.TPA add block for each traveler in JO_JOINL.bcs.
	INCLUDE ~JOining_Party_Select/Baf/Join_ability/JO_LOAD_TRAVELER.tpa~

// original All_In.baf modified and created for each traveler Death_var.
COPY ~JOining_Party_Select/Baf/All_In.baf~ ~weidu_external/JOining_Party_Select/All_In/%Death_var%_All_In.baf~ EVALUATE_BUFFER

// Charname override script JO_JOINP.baf (allow to know if no traveler are present).
COPY ~weidu_external/JOining_Party_Select/Join_ability/JO_JOINP.baf~ ~weidu_external/JOining_Party_Select/Join_ability/JO_JOINP.baf~ EVALUATE_BUFFER
	REPLACE_TEXTUALLY ~//	REPLACE_TRAVELER_NumInParty~ ~Global("JO_TRAVELER_%Death_var%","GLOBAL",0)
	\0~

// JO_JOIN_COUNT_TRAVELER for JO_JOINC.baf allow to count traveler.
COPY ~weidu_external/JOining_Party_Select/Join_ability/JO_JOINC.baf~  ~weidu_external/JOining_Party_Select/Join_ability/JO_JOINC.baf~ EVALUATE_BUFFER
	REPLACE_TEXTUALLY ~//	ADD_JO_JOIN_COUNT_TRAVELER~ ~~~~~IF
	Global("JO_TRAVELER_%Death_var%","GLOBAL",1)
	Global("JO_JOINP_%Death_var%","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("JO_JOINP_%Death_var%","LOCALS",1)
		IncrementGlobal("JO_JOIN_LEGION","LOCALS",1)
		Continue()
END

IF
	!Global("JO_TRAVELER_%Death_var%","GLOBAL",1)
	!Global("JO_JOINP_%Death_var%","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("JO_JOINP_%Death_var%","LOCALS",0)
		IncrementGlobal("JO_JOIN_LEGION","LOCALS",-1)
		Continue()
END

	\0~~~~~

//////////////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////

// Edge cases

//////////////////////////////////////////////////////////////////////////////////////

	ACTION_IF FILE_EXISTS_IN_GAME ~ar1901.bcs~ THEN BEGIN
		COPY_EXISTING ~ar1901.bcs~ ~override~
			DECOMPILE_AND_PATCH BEGIN
	// FakeEffectExpiryCheck() situation
			SPRINT textToReplace ~^[%TAB% ]*FakeEffectExpiryCheck(Player2,\([^)]*\))~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) /*AND (~%SOURCE_FILESPEC%~ STRING_EQUAL_CASE ~ar1901.bcs~)*/ BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~\0 FakeEffectExpiryCheck("%Death_var%",\1)~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %Death_var% : FakeEffectExpiryCheck() found in %SOURCE_FILESPEC%
				~
			END
		END
			BUT_ONLY
	END

//////////////////////////////////////////////////////////////////////////////////////

	ACTION_FOR_EACH bcs IN BDBALDUR BDELEV02 BDEXITBF BDNORES2 HELLPOOL BEGIN

		ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ THEN BEGIN
		  COPY_EXISTING_REGEXP ~%bcs%.bcs~ ~override~
			DECOMPILE_AND_PATCH BEGIN
				SPRINT textToReplace ~^[%TAB% ]*!IsOverMe(Player2)
^[%TAB% ]*!IsOverMe(Player3)~
				COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
				PATCH_IF (num_matches > 0) /*AND (~%SOURCE_FILESPEC%~ STRING_EQUAL_CASE ~BALDUR.bcs~)*/ BEGIN
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~\0 !IsOverMe("%Death_var%")~
					PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
					PATCH_PRINT ~... // %Death_var% : !IsOverMe found in %SOURCE_FILESPEC%
					~
				END
			END
				BUT_ONLY
		END
	END // ACTION_FOR_EACH // CreateVisualEffectObject

//////////////////////////////////////////////////////////////////////////////////////

	ACTION_FOR_EACH bcs IN BALDUR BALDUR25 BDBALDUR BEGIN

		ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ THEN BEGIN
		  COPY_EXISTING_REGEXP ~%bcs%.bcs~ ~override~
			DECOMPILE_AND_PATCH BEGIN
	// HabibAppearance situation
				SPRINT textToReplace ~^[%TAB% ]*ActionOverride(Player2,DropItem(\([^)]*\),\[-1\.-1\]))
	^[%TAB% ]*ActionOverride(Player3,DropItem("\([^)]*\)",\[-1\.-1\]))~
				COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
				PATCH_IF (num_matches > 0) /*AND (~%SOURCE_FILESPEC%~ STRING_EQUAL_CASE ~BALDUR.bcs~)*/ BEGIN
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~\0 ActionOverride("%Death_var%",DropItem(\1,[-1.-1]))~
					PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
					PATCH_PRINT ~... // %Death_var% : HabibAppearance found in %SOURCE_FILESPEC%
					~
				END
			END
				BUT_ONLY
		END
	END // ACTION_FOR_EACH // CreateVisualEffectObject

//////////////////////////////////////////////////////////////////////////////////////
/*

Don't disable AI for traveler

	ACTION_FOR_EACH bcs IN BDCUT61A BDCUT62 BDCUT65 K#TELBGT BEGIN

		ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ THEN BEGIN
		  COPY_EXISTING_REGEXP ~%bcs%.bcs~ ~override~
			DECOMPILE_AND_PATCH BEGIN
	// DisableAI situation
				SPRINT textToReplace ~^[%TAB% ]*DisableAI(Player3,\([^)]*\)
^[%TAB% ]*DisableAI(Player4,\1)~
				COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
				PATCH_IF (num_matches > 0) BEGIN
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~\0 DisableAI("%Death_var%",\1)~
					PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
					PATCH_PRINT ~... // %Death_var% : DisableAI found in %SOURCE_FILESPEC%
					~
				END
			END
			BUT_ONLY
		END
	END // ACTION_FOR_EACH // DisableAI
*/
//////////////////////////////////////////////////////////////////////////////////////

END // ACTION_FOR_EACH Death_var

//////////////////////////////////////////////////////////////////////////////////////

// BG1 / SoD only

//////////////////////////////////////////////////////////////////////////////////////


ACTION_IF (GAME_IS ~eet~ OR GAME_INCLUDES ~SoD~) BEGIN

	ACTION_FOR_EACH Death_var IN // ACTION_FOR_EACH BGSoD

//////////////////////////////////////////////////////////////////////////////////////

// Original Imoen                ~%IMOEN_DV%~ // ImoenIren ~Imoen~ // ~ttimoen~     // Imoen
// Original Edwin                ~Edwin~                                            // Edwin
// Original Jaheira              ~Jaheira~                         // ~ttjaheir~    // Jaheira
// Original Minsc                ~Minsc~                           // ~ttminsc~     // Minsc
// Original Viconia              ~Viconia~                                          // Viconia
// Original Dorn                 ~Dorn~                                             // Dorn
// Original Neera                ~Neera~                                            // Neera
// Original Rasaad               ~Rasaad~                                           // Rasaad


/////////////////////////// BG1 ///////////////////////////

// Original Ajantis              ~Ajantis~                                          // Ajantis
// Original Alora                ~Alora~                                            // Alora
// Original Branwen              ~Branwen~                         // ~ttbran~      // Branwen
// Original Coran                ~Coran~                                            // Coran
// Original Dynaheir             ~Dynaheir~                                         // Dynaheir

// Original Eldoth               ~Eldoth~                                           // Eldoth
// Original Faldorn              ~Faldorn~                                          // Faldorn
// Original Garrick              ~Garrick~                                          // Garrick

// Original Kagain               ~Kagain~                                           // Kagain
// Original Khalid               ~Khalid~                                           // Khalid
// Original Kivan                ~Kivan~                                            // Kivan

// Original Montaron             ~Montaron~                                         // Montaron
// Original Quayle               ~Quayle~                                           // Quayle
// Original Safana               ~Safana~                                           // Safana
// Original Sharteel             ~Sharteel~                        // ~Shar-teel~   // Sharteel
// Original Skie                 ~Skie~                                             // Skie
// Original Tiax                 ~Tiax~                                             // Tiax

// Original Xan                  ~Xan~                             // ttxan~        // Xan
// Original Xzar                 ~Xzar~                                             // Xzar
// Original Yeslick              ~Yeslick~                                          // Yeslick

// Original Baeloth              ~Baeloth~                                          // Baeloth


/////////////////////////// SoD ///////////////////////////

// Original Voghiln              ~Voghiln~                                          // Voghiln
// Original Corwin               ~Corwin~                                           // Corwin
// Original Mkhiin               ~Mkhiin~                                           // Mkhiin
// Original Glint                ~Glint~                                            // Glint


/////////////////////////// Mods BG1 ///////////////////////////

// Ishlilka_The-Wizard-Slayer
// Mod Ishlilka                  ~#Ishy~                                            // Ishlilka

// ChaosKnight-kit
// Mod Jacob                     ~ZYJCOB~                                           // Jacob

// Askaria-Quest
// Mod Askaria                   ~ZYASKA~                                           // Askaria

// Isra BG1
// Mod Isra_BG1                  ~rh#isra~                                          // Isra

// Finch
// Mod Finch                     ~SUFINCH~                                          // Finch

// Drizzt Saga
// Mod Jarlaxle_Saga             ~F_JARLAXE~                                        // Jarlaxle
// Mod Artemis_Enteri_Saga       ~F_ARTEMIS~                                        // Artemis Enteri
// Mod Catti-Brie_Saga           ~F_CATTIBR~                                        // Catti-Brie
// Mod Bruenor_Saga              ~F_BRUENOR~                                        // Bruenor
// Mod Regis_Saga                ~F_REGIS~                                          // Regis
// Mod Drizzt_Saga               ~F_DRIZZT~                                         // Drizzt
// Mod Wulfgar_Saga              ~F_WULFGAR~                                        // Wulfgar

// Dark Horizons
// Mod Thorin                    ~CMTTHOR~                                          // Thorin
// Mod Morwen                     ~CMTMORW~                                         // Morwen

// DSotSC
// Mod Bardo                     ~DSBARDO~                                          // Bardo
// Mod Bub_Snikt                 ~DSBUB~                                            // Bub Snikt
// Mod Conchobhair               ~Conchobhair~                                      // Conchobhair
// Mod CuChoinneach              ~CuChoinneach~                                     // CuChoinneach
// Mod Ferthgil_Trollslayer      ~Ferthgil~                                         // Ferthgil Trollslayer
// Mod Jet'laya                  ~JETLAYA~                                          // Jet'laya
// Mod Keiria_Silverstring       ~KEIRIA~                                           // Keiria Silverstring
// Mod Skeezer_Lumpkin_VI        ~SKEEZER~                                          // Skeezer Lumpkin VI
// Mod Thorfinn_Hauskluniff      ~Thorfinn~                                         // Thorfinn Hauskluniff

// NTotSC
// Mod Will_Scarlet              ~WILL~                                             // Will Scarlet

// Valerie
// Mod Valerie                   ~T2VAL~

// Indira
// Mod Indira                    ~J#Indi~

// Bristlelick BG1 / SoD
// Mod Bristlelick               ~L#BRIST~

// Glam's npc pack
// Mod Dave                      ~GV#DAVE~
// Mod Flara                     ~GV#FLAR~
// Mod Littlun                   ~GV#LITT~
// Mod Moidre                    ~GV#MOID~
// Mod Vynd                      ~GV#VYND~

// Kale BG1
// Mod Kale_BG1                  ~X3Kale~

// New Tales of the Sword Coast
// Mod Kasandra                  ~Kasandra~
// Mod Masambe                   ~Masambe~
// Mod Alethra                   ~Alethra~
// Mod Rimardo                   ~Rimardo~
// Mod Talindra                  ~Talindra~
// Mod Theodor                   ~Theodor~
// Mod Ariadne                   ~Ariadne~
// Mod Nathan                    ~Nathan~
// Mod Namiir                    ~Namiir~
// Mod Miranda                   ~Miranda~

// Walahnan BG1 / SoD
// Mod Walahnan                  ~L#WALAH~

// Aerie in BG:EE
// Mod Aerie_BG1            ~B2#Aeri~

// Next_Traveler BG1

/////////////////////////// Mods Continuous ///////////////////////////

// EET Nikita                  ~cmnikita~                                   // Nikita

// EET Alora_Continuous        ~Alora~                                     // Alora_Continuous

// EET Ajantis_Continuous      ~Ajantis~                                   // Ajantis_Continuous

// EET Kivan_Continuous        ~Kivan~                                     // Kivan_Continuous

// EET Walahnan_Continuous     ~L#WALAH~                                   // Walahnan_Continuous

// EET Coran_Continuous        ~Coran~                                     // Coran_Continuous

// EET Yeslick_Continuous      ~Yeslick~                                   // Yeslick_Continuous

// EET Xan_Continuous          ~Xan~                                       // Xan_Continuous

// EET Branwen_Continuous      ~Branwen~                                   // Branwen_Continuous

// EET Tiax_Continuous         ~Tiax~                                      // Tiax_Continuous

// EET Isra_Continuous         ~rh#isra~                                  // Isra_Continuous

// Next_Traveler Continuous

//////////////////////////////////////////////////////////////////////////////////////

	BEGIN // ACTION_FOR_EACH BGSoD

ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT ~252034~ ~252034~
END ELSE ACTION_IF (NOT GAME_IS ~eet~ AND GAME_INCLUDES ~SoD~) BEGIN
	OUTER_SPRINT ~252034~ ~52034~
END

	INCLUDE ~JOining_Party_Select/Baf/Extend_SELECT/replace_bcs_block/BDBALDUR.tph~
	INCLUDE ~JOining_Party_Select/Baf/Extend_SELECT/replace_bcs_block/BDTARGET.tph~

// Transition between campaigns

// JO_JOINP / JO_JOINI transitions addition

		INCLUDE ~JOining_Party_Select/Campaign_Transition/END_OF_WATCH.tph~

/*

///////////Don't work

// IwD1
	ACTION_IF FILE_EXISTS_IN_GAME ~WTKERJMP.bcs~ BEGIN
EXTEND_BOTTOM ~WTKERJMP.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/WTKERJMP.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~LWSTPASD.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/LWSTPASD.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~LWPRVFOL.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/LWPRVFOL.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~LWPRVFCE.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/LWPRVFCE.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~LWFCEALP.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/LWFCEALP.baf~ EVALUATE_BUFFER
	END
// DSotSC
	ACTION_IF FILE_EXISTS_IN_GAME ~MEGACUT.bcs~ BEGIN
INCLUDE ~JOining_Party_Select/Baf/Extend_SELECT/replace_bcs_block/MEGACUT.tph~
	END


INCLUDE ~JOining_Party_Select/Baf/Extend_SELECT/replace_bcs_block/PRISMCUT.tph~
EXTEND_BOTTOM ~GARRCUT.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/GARRCUT.baf~ EVALUATE_BUFFER
*/

ACTION_IF (MOD_IS_INSTALLED ~iwd2_eet.TP2~ ~0~) BEGIN
	OUTER_SPRINT ~// 60CLCKIR_IWD2_EET~ ~~
END
EXTEND_BOTTOM ~BDBALDUR.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/BDBALDUR.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~ICELAND.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/ICELAND.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~ICELAND1.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/ICELAND1.baf~ EVALUATE_BUFFER

	OUTER_SPRINT ~bdmenhi~ ~bdmenhi1~
INCLUDE ~JOining_Party_Select/Baf/Extend_SELECT/replace_bcs_block/BDMENHI.tph~

	OUTER_SPRINT ~bdmenhi~ ~bdmenhi2~
INCLUDE ~JOining_Party_Select/Baf/Extend_SELECT/replace_bcs_block/BDMENHI.tph~

	OUTER_SPRINT ~bdmenhi~ ~bdmenhi3~
INCLUDE ~JOining_Party_Select/Baf/Extend_SELECT/replace_bcs_block/BDMENHI.tph~

	OUTER_SPRINT ~bdmenhi~ ~bdmenhi4~
INCLUDE ~JOining_Party_Select/Baf/Extend_SELECT/replace_bcs_block/BDMENHI.tph~

	OUTER_SPRINT ~bdmenhi~ ~bdmenhi5~
INCLUDE ~JOining_Party_Select/Baf/Extend_SELECT/replace_bcs_block/BDMENHI.tph~

	OUTER_SPRINT ~bdmenhi~ ~bdmenhi6~
INCLUDE ~JOining_Party_Select/Baf/Extend_SELECT/replace_bcs_block/BDMENHI.tph~

	END

END // ACTION_FOR_EACH BGSoD


//////////////////////////////////////////////////////////////////////////////////////

// BG2 only

//////////////////////////////////////////////////////////////////////////////////////

ACTION_IF GAME_IS ~bgt bg2ee eet~ BEGIN

	ACTION_FOR_EACH Death_var IN // ACTION_FOR_EACH BG2

//////////////////////////////////////////////////////////////////////////////////////

// Original Imoen                ~%IMOEN_DV%~ // ImoenIren ~Imoen~ // ~ttimoen~     // Imoen
// Original Edwin                ~Edwin~                                            // Edwin
// Original Jaheira              ~Jaheira~                         // ~ttjaheir~    // Jaheira
// Original Minsc                ~Minsc~                           // ~ttminsc~     // Minsc
// Original Viconia              ~Viconia~                                          // Viconia
// Original Dorn                 ~Dorn~                                             // Dorn
// Original Neera                ~Neera~                                            // Neera
// Original Rasaad               ~Rasaad~                                           // Rasaad

/////////////////////////// bg2 ///////////////////////////

// Original Aerie                ~Aerie~                                            // Aerie
// Original Anomen               ~Anomen~                                           // Anomen
// Original Cernd                ~Cernd~                                            // Cernd
// Original Haerdalis            ~Haerdalis~                                        // Haerdalis
// Original Hexxat               ~Hexxat~                                           // Hexxat
// Original Jan                  ~Jan~                                              // Jan
// Original Keldorn              ~Keldorn~                                          // Keldorn
// Original Korgan               ~Korgan~                                           // Korgan
// Original Mazzy                ~Mazzy~                                            // Mazzy
// Original Nalia                ~Nalia~                                            // Nalia
// Original Sarevok              ~Sarevok~                                          // Sarevok
// Original Valygar              ~Valygar~                                          // Valygar
// Original Wilson               ~Wilson~                                           // Wilson
// Original Yoshimo              ~Yoshimo~                                          // Yoshimo


/////////////////////////// Mods BG2 ///////////////////////////

// Alora BG2
// Mod Alora BG2                 ~CMALORA~                                          // Alora

// Yeslick BG2
// Mod Yeslick BG2               ~LK#YESLK~                                         // Yeslick

// The Undying
// Mod Undying                   ~cmninaf~                                          // Ninafer
// Mod Undying                   ~callisto~                                         // Callisto

// Summon Bhaalspawn
// Mod Sandra                    ~BHAALSPW~                                         // Sandra

// VampireTales
// Mod Miriam                    ~cmgmiriam~                                        // Miriam

// Kim
// Mod Kim                       ~Kim~                                              // Kim

// Severian
// Mod Severian                  ~#Severian~                                        // Severian

// Frennedan
// Mod Frennedan                 ~Frennedan~                                        // Frennedan

// Branwen BG2
// Mod Branwen_BG2               ~O#Bran~                                           // Branwen
// Tiax BG2
// Mod Tiax_BG2                  ~O#Tiax~                                           // Tiax
// Xan BG2
// Mod Xan_BG2                   ~O#XAN~                                            // Xan
// Coran BG2
// Mod Coran_BG2                 ~O#Coran~                                          // Coran

// Auren Aseph
// Mod Auren                     ~K#AUREN~                                  // Auren

// Isra BG2
// Mod Isra_BG2                  ~rh#Isra2~                                 // Isra

// Nephele
// Mod Nephele_Samios            ~Nephele~                                  // Nephele

// Sheena
// Mod Sheena                    ~K#SHEENA~                                 // Sheena

// Kiara / Zaiya
// Mod Kiara                     ~Kiara~                                    // Kiara
// Mod Zaiya                     ~Zaiya~                                    // Zaiya

// The Beaurin Legacy
// Mod Minyae                    ~QI#MI~                                    // Minyae
// Mod Elaryn                    ~QI#ELA~                                   // Elaryn

// Tyris Flare
// Mod Tyris                     ~g#Tyris~                                  // Tyris

// Region of Terror
// Mod Wulfgar_Terror            ~Wulfg2~                                   // Wulfgar
// Mod Regis_Terror              ~Reg2~                                     // Regis
// Mod Drizzt_Terror             ~Driz2~                                    // Drizz
// Mod Bruenor_Terror            ~Brue2~                                    // Bruenor
// Mod Catti-Brie_Terror         ~Catt2~                                    // Catti-Brie
// Mod Artemis_Entreri_Terror    ~Enter2~                                   // Artemis
// Mod Jarlaxle_Terror           ~Jarlax2~                                  // Jarlaxle
// Mod Tapio_Perkiomaki_Terror   ~Tapio~                                    // Tapio
// Mod Randall_Terror            ~Randall~                                  // Randall
// Mod Alissa_Terror             ~ALISSA1~                                  // Alissa
// Mod Mordragon_Terror          ~Mordrg~                                   // Mordragon

//Shadow over Soubar
// Mod Selence_Hillstar_Soubar   ~SELENCE~                                  // Selence
// Mod Charlotte_Soubar          ~CHARLOTT~                                 // Charlotte
// Mod Bolivar_Soubar            ~BOLIVAR~                                  // Bolivar
// Mod Tomas_Tomalson_Soubar     ~TOMASTM~                                  // Tomas

// ajantisbg2
// Mod Ajantis_BG2               ~C#Ajantis~                                // Ajantis

// Kivan and Deheriana
// Mod Kivan_BG2                 ~P#KIVAN~                                  // Kivan
// Mod Deheriana                 ~P#DEHER~                                  // Deheriana

// Yvette
// Mod Yvette                    ~YxYve~

// The Luxley Family
// Mod Sebastian                ~fhlseb~
// Mod Andrei                   ~FHLAND~

//  Beyond the Law
// Mod Kiyone                   ~Kiyone~
// Mod Kova                     ~Kova~

// Petsy
// Mod Petsy                   ~L3PETSY~

// Kale BG2
// Mod Kale_BG2                ~X3Kal~

// Walahnan BG2
// Mod Walahnan_BG2            ~L#2WALAH~

// Autumns Twilight
// Mod Dusk                    ~P_Dusk~
// Mod Fall                    ~P_Fall~
// Mod Cho'Nuja                ~P_Chon~
// Mod Alendir                 ~P_Alen~

// Next_Traveler BG2

/////////////////////////// Mods Continuous ///////////////////////////

// EET Nikita                  ~cmnikita~                                   // Nikita

// EET Alora_Continuous        ~Alora~                                     // Alora_Continuous

// EET Ajantis_Continuous      ~Ajantis~                                   // Ajantis_Continuous

// EET Kivan_Continuous        ~Kivan~                                     // Kivan_Continuous

// EET Walahnan_Continuous     ~L#WALAH~                                   // Walahnan_Continuous

// EET Coran_Continuous        ~Coran~                                     // Coran_Continuous

// EET Yeslick_Continuous      ~Yeslick~                                   // Yeslick_Continuous

// EET Xan_Continuous          ~Xan~                                       // Xan_Continuous

// EET Branwen_Continuous      ~Branwen~                                   // Branwen_Continuous

// EET Tiax_Continuous         ~Tiax~                                      // Tiax_Continuous

// EET Isra_Continuous         ~rh#isra~                                  // Isra_Continuous

// Next_Traveler Continuous

//////////////////////////////////////////////////////////////////////////////////////

	BEGIN // ACTION_FOR_EACH BG2

EXTEND_BOTTOM ~OHHBARHX.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/OHHBARHX.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~OHHFAKOK.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/OHHFAKOK.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~ohhspike.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/ohhspike.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~ohdwater.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/ohdwater.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~OHBGREST.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/OHBGREST.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~OHRDLG01.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/OHRDLG01.baf~ EVALUATE_BUFFER

/*

///////////Don't work

// Unfinished Business / Bouh rapt
	ACTION_IF FILE_EXISTS_IN_GAME ~WWRLGV.bcs~ BEGIN
EXTEND_BOTTOM ~WWRLGV.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/WWRLGV.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~WWGOVT.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/WWRLGV.baf~ EVALUATE_BUFFER
INCLUDE ~JOining_Party_Select/Baf/Extend_SELECT/replace_bcs_block/WWCUT.tph~
	END
// Imoen Romance
	ACTION_IF FILE_EXISTS_IN_GAME ~MRGOREX3.bcs~ BEGIN
EXTEND_BOTTOM ~MRGOREX3.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/MRGOREX3.baf~ EVALUATE_BUFFER
INCLUDE ~JOining_Party_Select/Baf/Extend_SELECT/replace_bcs_block/MRGOREN2.tph~
INCLUDE ~JOining_Party_Select/Baf/Extend_SELECT/replace_bcs_block/LOVEME5A.tph~
INCLUDE ~JOining_Party_Select/Baf/Extend_SELECT/replace_bcs_block/LOVEME3I.tph~
EXTEND_BOTTOM ~LOVEME2.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/LOVEME2.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~LOVEME1A.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/LOVEME1A.baf~ EVALUATE_BUFFER
	END

*/

ACTION_IF GAME_IS ~eet~ BEGIN
	INCLUDE ~JOining_Party_Select/Campaign_Transition/AR4000.tph~ // ToB transition
END

INCLUDE ~JOining_Party_Select/Baf/Extend_SELECT/replace_bcs_block/ar2500.tph~
INCLUDE ~JOining_Party_Select/Baf/Extend_SELECT/replace_bcs_block/cut85b.tph~
INCLUDE ~JOining_Party_Select/Baf/Extend_SELECT/replace_bcs_block/cut220b.tph~
INCLUDE ~JOining_Party_Select/Baf/Extend_SELECT/replace_bcs_block/HELLPOOL.tph~

	OUTER_SPRINT ~Wait~ ~~
	OUTER_SPRINT ~Hallbattle~ ~Hallbattle1~
EXTEND_BOTTOM ~HALL1.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/HALL1.baf~ EVALUATE_BUFFER

	OUTER_SPRINT ~Hallbattle~ ~Hallbattle2~
EXTEND_BOTTOM ~HALL2.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/HALL1.baf~ EVALUATE_BUFFER

	OUTER_SPRINT ~Hallbattle~ ~Hallbattle1~
	OUTER_SPRINT ~Wait~ ~Wait(6)~
EXTEND_BOTTOM ~HALL3.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/HALL1.baf~ EVALUATE_BUFFER

	OUTER_SPRINT ~Wait~ ~Wait(18)~
EXTEND_BOTTOM ~HALL4.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/HALL1.baf~ EVALUATE_BUFFER

	OUTER_SPRINT ~Hallbattle~ ~Hallbattle2~
	OUTER_SPRINT ~Wait~ ~Wait(6)~
EXTEND_BOTTOM ~HALL5.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/HALL1.baf~ EVALUATE_BUFFER

	OUTER_SPRINT ~Wait~ ~Wait(18)~
EXTEND_BOTTOM ~HALL6.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/HALL1.baf~ EVALUATE_BUFFER

ACTION_IF (MOD_IS_INSTALLED ~iwd2_eet.TP2~ ~0~) BEGIN
	OUTER_SPRINT ~// 60CLCKIR_IWD2_EET~ ~~
END
EXTEND_BOTTOM ~BALDUR25.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/BALDUR.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~BALDUR.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/BALDUR.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~CUT218E.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/CUT218E.baf~ EVALUATE_BUFFER

EXTEND_TOP ~JORAK07.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/JORAK07.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~JORAK07.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/JORAK07_once.baf~ EVALUATE_BUFFER
EXTEND_TOP ~JORAK00.bcs~ ~JOining_Party_Select/Baf/Extend_SELECT/JORAK01.baf~ EVALUATE_BUFFER

	END

// To see
// OHHGFORM // Hexxat



END // ACTION_FOR_EACH BG2

//////////////////////////////////////////////////////////////////////////////////////

// Special transition between game

///////////////////////////////////////////////////////////////////////////////

// SoD transition


// Avoid traveler to reintegrate party in Korlaz donjon
	ACTION_IF FILE_EXISTS_IN_GAME ~BDINTRO.bcs~ THEN BEGIN

		COPY_EXISTING ~BDINTRO.bcs~ ~override~
			DECOMPILE_AND_PATCH BEGIN
	// BDINTRO situation
			SPRINT textToReplace ~^[%TAB% ]*Global("SOD_fromimport","global",0)
^[%TAB% ]*InMyArea(\([^)]*\))~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~\0
	TriggerOverride(\1,Global("JO_JOIN_IS_TRAVELER","LOCALS",0))~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... //  InMyArea found in %SOURCE_FILESPEC%
				~
			END
		END
			BUT_ONLY


// Safana situation // Delete JoinPartyOverride
<<<<<<<<BDINTRO_SAFANA_rep.baf
IF
	Global("SOD_fromimport","global",1)
	Global("BD_Imoen_Items","GLOBAL",1)
	OR(2)
		Global("bd_party_has_lockpicking","BD0120",0)
		Global("bd_party_has_traps","BD0120",0)
	BeenInParty("safana")
THEN
	RESPONSE #100
		CutSceneId(Player1)
		MoveGlobal("BD0120","safana",[934.1718])
		ApplySpellRES("bdresurr","safana")
		SmallWait(1)
		ApplySpellRES("bdrejuve","safana")
		ActionOverride("safana",ChangeAIScript("bdsafana",OVERRIDE))
		ActionOverride("safana",SetDialog("bdsafana"))
		ActionOverride("safana",JoinPartyOverride())
END

IF
	Global("SOD_fromimport","global",1)
	Global("BD_Imoen_Items","GLOBAL",1)
	OR(2)
		Global("bd_party_has_lockpicking","BD0120",0)
		Global("bd_party_has_traps","BD0120",0)
	!BeenInParty("safana")
THEN
	RESPONSE #100
		CutSceneId(Player1)
		CreateCreature("safana7",[934.1718],NE)
		ActionOverride("safana",JoinPartyOverride())
END
>>>>>>>>

<<<<<<<<BDINTRO_SAFANA_add.baf
IF
	Global("SOD_fromimport","global",1)
	Global("BD_Imoen_Items","GLOBAL",1)
	OR(2)
		Global("bd_party_has_lockpicking","BD0120",0)
		Global("bd_party_has_traps","BD0120",0)
	BeenInParty("safana")
THEN
	RESPONSE #100
		CutSceneId(Player1)
		MoveGlobal("BD0120","safana",[934.1718])
		ApplySpellRES("bdresurr","safana")
		SmallWait(1)
		ApplySpellRES("bdrejuve","safana")
		ActionOverride("safana",ChangeAIScript("bdsafana",OVERRIDE))
		ActionOverride("safana",SetDialog("bdsafana"))
END

IF
	Global("SOD_fromimport","global",1)
	Global("BD_Imoen_Items","GLOBAL",1)
	OR(2)
		Global("bd_party_has_lockpicking","BD0120",0)
		Global("bd_party_has_traps","BD0120",0)
	!BeenInParty("safana")
THEN
	RESPONSE #100
		CutSceneId(Player1)
		CreateCreature("safana7",[934.1718],NE)
END
>>>>>>>>
COPY_EXISTING ~BDINTRO.bcs~ ~override~
	REPLACE_BCS_BLOCK ~BDINTRO_SAFANA_rep.baf~ ~BDINTRO_SAFANA_add.baf~ EVALUATE_BUFFER

	END // FILE_EXISTS_IN_GAME ~BDINTRO.bcs~


// BD0120 is Korlaz Donjon
ACTION_IF (GAME_IS ~eet~ OR GAME_INCLUDES ~SoD~) BEGIN

INCLUDE ~JOining_Party_Select/Campaign_Transition/BD0120.tph~

COPY_EXISTING ~%Undercity_TempleofBhaal%.bcs~ ~override~
		DECOMPILE_AND_PATCH BEGIN
			SPRINT textToReplace ~^[%TAB% ]*SaveGame(\([^)]*\)~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~SetGlobal("JO_JOIN_AREA_TRANSITION","GLOBAL",1)
				SetGlobal("JO_JOIN_BG1_TRANSITION","%Undercity_TempleofBhaal%",1)
	\0~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // Undercity_TempleofBhaal : SaveGame found in %SOURCE_FILESPEC% for JO_JOIN_AREA_TRANSITION
				~
			END
		END

EXTEND_TOP ~BDROPE.bcs~ ~JOining_Party_Select/Campaign_Transition/BD0120_BDROPE.BAF~ EVALUATE_BUFFER

// MoveToCampaign("SoD") script
COPY_EXISTING ~BDSODTRN.bcs~ ~override~
		DECOMPILE_AND_PATCH BEGIN
			SPRINT textToReplace ~^[%TAB% ]*CutSceneId(Player1)~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~\0
		StartCutSceneMode()
		SetGlobal("JO_JOIN_AREA_TRANSITION","GLOBAL",1)~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // BDSODTRN : EndOfBG1 found in %SOURCE_FILESPEC% for JO_JOIN_AREA_TRANSITION
				~
			END
		END

END

	ACTION_IF FILE_EXISTS_IN_GAME ~%NBaldursGate_DucalPalace_L1%.bcs~ THEN BEGIN

<<<<<<<< .../JOining_DucalPalace.baf

IF
	Dead("Sarevok")
	Global("EndOfBG1","GLOBAL",0)
	!Global("JO_JOIN_AREA_TRANSITION","GLOBAL",1)
	Global("JO_JOIN_DucalPalace_TRANSITION","MYAREA",0)
THEN
	RESPONSE #100
		SetGlobal("JO_JOIN_AREA_TRANSITION","GLOBAL",1)
		SetGlobal("JO_JOIN_DucalPalace_TRANSITION","MYAREA",1)
		Continue()
END

>>>>>>>>
EXTEND_BOTTOM ~%NBaldursGate_DucalPalace_L1%.bcs~ ~.../JOining_DucalPalace.baf~ EVALUATE_BUFFER

	END


// Related to "JO_JOIN_TRAVELER_NUM" in all_In.baf
	ACTION_IF FILE_EXISTS_IN_GAME ~BD0120.bcs~ THEN BEGIN
		COPY_EXISTING ~BD0120.bcs~ ~override~
			DECOMPILE_AND_PATCH BEGIN
	// BD0120 situation
			SPRINT textToReplace ~^[%TAB% ]*NumInParty(\([^)]*\))~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~\0 Global("JO_JOIN_TRAVELER_NUM","GLOBAL",0)~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... //  NumInParty found in %SOURCE_FILESPEC%
				~
			END
		END
			BUT_ONLY
	END

