//////////////////////////////////////////////////////
//////////////////////////////////////////////////////
//////////////////////////////////////////////////////

/////////////////////////// Continuous ///////////////////////////

/////////////////////////// Nikita ///////////////////////////

OUTER_SPRINT "BG1_JOINED" "CMTNIKJ"
OUTER_SPRINT "BG1_BCS" "cmtnikit"
OUTER_SPRINT "BG1_BANTER" "BCMTNIK"
OUTER_SPRINT "SoD_BANTER" ""
OUTER_SPRINT "SoD_JOINED" ""
OUTER_SPRINT "SoD_BCS" ""
// OUTER_SPRINT "EET_BANTER" "BCMTNIK"
OUTER_SPRINT "BG1_DREAM" "CMTNIKD"
OUTER_SPRINT "SoD_DREAM" ""
// OUTER_SPRINT "EET_DREAM" "CMNIKITD"
OUTER_SPRINT "BG2_JOINED" "CMNIKITJ"
OUTER_SPRINT "BG2_BCS" "cmnikita"
OUTER_SPRINT "BG2_BANTER" "BCMNIKIT"
OUTER_SPRINT "BG2_DREAM" "CMNIKITD"
ACTION_IF (GAME_IS ~eet~) BEGIN
	OUTER_SPRINT "TOB_JOINED" "CMNIKITJ"
	OUTER_SPRINT "TOB_BANTER" "BCMNIKIT"
	OUTER_SPRINT "TOB_DREAM" "CMNIKITD"
	OUTER_SPRINT "TOB_BCS" "cmnikita"
END ELSE BEGIN
	OUTER_SPRINT "TOB_JOINED" "CMNIK25J"
	OUTER_SPRINT "TOB_BANTER" "BCMNIK25"
	OUTER_SPRINT "TOB_DREAM" "CMNIK25D"
	OUTER_SPRINT "TOB_BCS" "CMNIK25"
END

ACTION_FOR_EACH bcs IN

// Mod Nikita ~cmtnikit~ ~cmnikita~ ~CMNIK25~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/cmnikita_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Continuous.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

			ACTION_IF (NOT ~%BG1_BANTER%~ STRING_EQUAL_CASE ~~ OR NOT ~%SoD_BANTER%~ STRING_EQUAL_CASE ~~ OR NOT ~%BG2_BANTER%~ STRING_EQUAL_CASE ~~ OR NOT ~%TOB_BANTER%~ STRING_EQUAL_CASE ~~) AND (FILE_EXISTS_IN_GAME ~%BG1_BANTER%.dlg~ OR FILE_EXISTS_IN_GAME ~%SoD_BANTER%.dlg~ OR FILE_EXISTS_IN_GAME ~%BG2_BANTER%.dlg~ OR FILE_EXISTS_IN_GAME ~%TOB_BANTER%.dlg~) BEGIN

						ACTION_IF (GAME_IS ~eet~) BEGIN
		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/Banter/Banter_Continuous.baf~ EVALUATE_BUFFER
						END ELSE ACTION_IF (GAME_INCLUDES ~SoD~ AND NOT GAME_IS ~eet~) BEGIN
		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/Banter/Banter_BGSoD.baf~ EVALUATE_BUFFER
						END ELSE ACTION_IF (GAME_IS ~bgee~ AND NOT GAME_INCLUDES ~SoD~) BEGIN
		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/Banter/Banter_BG1.baf~ EVALUATE_BUFFER
						END ELSE ACTION_IF (GAME_IS ~bg2ee~ AND NOT GAME_IS ~eet~) BEGIN
		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/Banter/Banter_BG2.baf~ EVALUATE_BUFFER
						END

			END

			ACTION_IF (NOT ~%BG1_DREAM%~ STRING_EQUAL_CASE ~~ OR NOT ~%SoD_DREAM%~ STRING_EQUAL_CASE ~~ OR NOT ~%BG2_DREAM%~ STRING_EQUAL_CASE ~~ OR NOT ~%TOB_DREAM%~ STRING_EQUAL_CASE ~~) AND (FILE_EXISTS_IN_GAME ~%BG1_DREAM%.bcs~ OR FILE_EXISTS_IN_GAME ~%SoD_DREAM%.bcs~ OR FILE_EXISTS_IN_GAME ~%BG2_DREAM%.bcs~ OR FILE_EXISTS_IN_GAME ~%TOB_DREAM%.bcs~) BEGIN

						ACTION_IF (GAME_IS ~eet~) BEGIN
		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/Dream/Dream_Continuous.baf~ EVALUATE_BUFFER
						END ELSE ACTION_IF (GAME_INCLUDES ~SoD~ AND NOT GAME_IS ~eet~) BEGIN
		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/Dream/Dream_BGSoD.baf~ EVALUATE_BUFFER
						END ELSE ACTION_IF (GAME_IS ~bgee~ AND NOT GAME_INCLUDES ~SoD~) BEGIN
		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/Dream/Dream_BG1.baf~ EVALUATE_BUFFER
						END ELSE ACTION_IF (GAME_IS ~bg2ee~ AND NOT GAME_IS ~eet~) BEGIN
		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/Dream/Dream_BG2.baf~ EVALUATE_BUFFER
						END

			END

	END
END

// Next_Traveler Continuous

