/////////////////////////// Mods BG2 ///////////////////////////

/////////////// Reset

// BG1
OUTER_SPRINT "BG1_JOINED" ""
OUTER_SPRINT "BG1_BCS" ""
OUTER_SPRINT "BG1_BANTER" ""
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
	OUTER_SPRINT "SoD_JOINED" ""
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""
		// BG2
		OUTER_SPRINT "BG2_JOINED" ""
		OUTER_SPRINT "BG2_BCS" ""
		OUTER_SPRINT "BG2_BANTER" ""
		OUTER_SPRINT "BG2_DREAM" ""
			// ToB
			OUTER_SPRINT "TOB_JOINED" ""
			OUTER_SPRINT "TOB_BCS" ""
			OUTER_SPRINT "TOB_BANTER" ""
			OUTER_SPRINT "TOB_DREAM" ""


/////////////////////////// Alora BG2 ///////////////////////////

		// BG2
		OUTER_SPRINT "BG2_JOINED" "CMALORAJ"
		OUTER_SPRINT "BG2_BCS" "cmalora"
		OUTER_SPRINT "BG2_BANTER" "BCMALOR"
		OUTER_SPRINT "BG2_DREAM" "CMALORAD"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "CMALORAJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "CMALO25J"
				END
			OUTER_SPRINT "TOB_BCS" "cmalo25"
			OUTER_SPRINT "TOB_BANTER" "BCMALO25"
			OUTER_SPRINT "TOB_DREAM" "CMALO25D"

ACTION_FOR_EACH bcs IN

// Mod Alora BG2 ~cmalora~ ~cmalo25~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/CMALORA_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

/////////////////////////// Yeslick BG2 ///////////////////////////

		// BG2
		OUTER_SPRINT "BG2_JOINED" "LK#YESJ"
		OUTER_SPRINT "BG2_BCS" "LK#YES"
		OUTER_SPRINT "BG2_BANTER" "BLK#YES"
		OUTER_SPRINT "BG2_DREAM" "LK#YESD"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "LK#YESJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "LK#YE25J"
				END
			OUTER_SPRINT "TOB_BCS" "LK#YES25"
			OUTER_SPRINT "TOB_BANTER" "BLK#YE25"
			OUTER_SPRINT "TOB_DREAM" "LK#YE25D"

ACTION_FOR_EACH bcs IN

// Mod Yeslick BG2 ~LK#YESL~ ~LK#YES25~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/LK#YESLK_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

/////////////////////////// The Undying ///////////////////////////

		// BG2
		OUTER_SPRINT "BG2_JOINED" "CMNINAFJ"
		OUTER_SPRINT "BG2_BCS" "CMNINAF"
		OUTER_SPRINT "BG2_BANTER" "BCMNINAF"
		OUTER_SPRINT "BG2_DREAM" "CMNINAFD"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "CMNINAFJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "CMNIN25J"
				END
			OUTER_SPRINT "TOB_BCS" "CMNINA25"
			OUTER_SPRINT "TOB_BANTER" "BCMNIN25"
			OUTER_SPRINT "TOB_DREAM" "NINA25D"

ACTION_FOR_EACH bcs IN

// Mod Undying ~CMNINAF~ ~CMNINA25~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/cmninaf_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

/////////////////////////// The Undying ///////////////////////////

		// BG2
		OUTER_SPRINT "BG2_JOINED" "CMCALLIJ"
		OUTER_SPRINT "BG2_BCS" "CALLISTO"
		OUTER_SPRINT "BG2_BANTER" "BCMCALLI"
		OUTER_SPRINT "BG2_DREAM" "CMCALLID"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "CMCALLIJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "CMCAL25J"
				END
			OUTER_SPRINT "TOB_BCS" "CALLISTO"
			OUTER_SPRINT "TOB_BANTER" "BCMCAL25"
			OUTER_SPRINT "TOB_DREAM" "CMCAL25D"

ACTION_FOR_EACH bcs IN

// Mod Undying ~CALLISTO~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/callisto_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

/////////////////////////// Summon Bhaalspawn ///////////////////////////

		// BG2
		OUTER_SPRINT "BG2_JOINED" "bhalspwj"
		OUTER_SPRINT "BG2_BCS" "BHAALSPW"
		OUTER_SPRINT "BG2_BANTER" "bbhalspw"
		OUTER_SPRINT "BG2_DREAM" "bhalspwd"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "bhalspwj"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "bhal25j"
				END
			OUTER_SPRINT "TOB_BCS" "bhal25"
			OUTER_SPRINT "TOB_BANTER" "bbhalspw"
			OUTER_SPRINT "TOB_DREAM" "bhal25d"

ACTION_FOR_EACH bcs IN

// Mod Sandra ~BHAALSPW~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/BHAALSPW_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

/////////////////////////// Vampire Tales ///////////////////////////

		// BG2
		OUTER_SPRINT "BG2_JOINED" "CMGMIRIJ"
		OUTER_SPRINT "BG2_BCS" "CMGMIRI"
		OUTER_SPRINT "BG2_BANTER" "BCMGMIRI"
		OUTER_SPRINT "BG2_DREAM" "CMGMIRD"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "CMGMIRIJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "CMGMI25J"
				END
			OUTER_SPRINT "TOB_BCS" "CMGMI25"
			OUTER_SPRINT "TOB_BANTER" "BCMGMI25"
			OUTER_SPRINT "TOB_DREAM" "CMGMI25D"

ACTION_FOR_EACH bcs IN

// Mod Miriam ~CMGMIRI~ ~CMGMI25~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/cmgmiriam_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

/////////////////////////// Kim ///////////////////////////

		// BG2
		OUTER_SPRINT "BG2_JOINED" "KimJ"
		OUTER_SPRINT "BG2_BCS" "Kim"
		OUTER_SPRINT "BG2_BANTER" ""
		OUTER_SPRINT "BG2_DREAM" "KimD"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "KimJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "Kim25J"
				END
			OUTER_SPRINT "TOB_BCS" "Kimd25"
			OUTER_SPRINT "TOB_BANTER" ""
			OUTER_SPRINT "TOB_DREAM" "Kim25D"

ACTION_FOR_EACH bcs IN

// Mod Kim ~Kim~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Kim_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

/////////////////////////// Severian ///////////////////////////

		// BG2
		OUTER_SPRINT "BG2_JOINED" "#SeverJ"
		OUTER_SPRINT "BG2_BCS" "#Sever"
		OUTER_SPRINT "BG2_BANTER" "#SBSever"
		OUTER_SPRINT "BG2_DREAM" "#SeverD"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "#SeverJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "#Sev25J"
				END
			OUTER_SPRINT "TOB_BCS" "#SevD25"
			OUTER_SPRINT "TOB_BANTER" "#SBSev25"
			OUTER_SPRINT "TOB_DREAM" "#Sev25D"


ACTION_FOR_EACH bcs IN

// Mod Severian ~#Sever~ ~#SevD25~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/#Severian_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

/////////////////////////// Frennedan ///////////////////////////

		// BG2
		OUTER_SPRINT "BG2_JOINED" ""
		OUTER_SPRINT "BG2_BCS" ""
		OUTER_SPRINT "BG2_BANTER" ""
		OUTER_SPRINT "BG2_DREAM" ""
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" ""
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" ""
				END
			OUTER_SPRINT "TOB_BCS" ""
			OUTER_SPRINT "TOB_BANTER" ""
			OUTER_SPRINT "TOB_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Frennedan ~fren~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Frennedan_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

/////////////////////////// Branwen BG2 ///////////////////////////

		// BG2
		OUTER_SPRINT "BG2_JOINED" "O#BranJ"
		OUTER_SPRINT "BG2_BCS" "O#BranS"
		OUTER_SPRINT "BG2_BANTER" "O#BBran"
		OUTER_SPRINT "BG2_DREAM" "O#BranD"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "O#BranJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "O#BrA25J"
				END
			OUTER_SPRINT "TOB_BCS" "O#Bra25S"
			OUTER_SPRINT "TOB_BANTER" "O#BBra25"
			OUTER_SPRINT "TOB_DREAM" "O#Bra25D"

ACTION_FOR_EACH bcs IN

// Mod Branwen_BG2 ~O#BranS~ ~O#Bra25S~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/O#Bran_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

/////////////////////////// Tiax BG2 ///////////////////////////

		// BG2
		OUTER_SPRINT "BG2_JOINED" "O#TiaxJ"
		OUTER_SPRINT "BG2_BCS" "O#TiaxS"
		OUTER_SPRINT "BG2_BANTER" "BO#Tiax"
		OUTER_SPRINT "BG2_DREAM" "O#TiaxD"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "O#TiaxJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "O#Tia25J"
				END
			OUTER_SPRINT "TOB_BCS" "O#Tia25S"
			OUTER_SPRINT "TOB_BANTER" "BO#Tia25"
			OUTER_SPRINT "TOB_DREAM" "O#Tia25D"

ACTION_FOR_EACH bcs IN

// Mod Tiax_BG2 ~O#TiaxS~ ~O#Tia25S~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/O#Tiax_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

/////////////////////////// Xan BG2 ///////////////////////////

		// BG2
		OUTER_SPRINT "BG2_JOINED" "O#XANJ"
		OUTER_SPRINT "BG2_BCS" "O#XanS"
		OUTER_SPRINT "BG2_BANTER" "BO#XAN"
		OUTER_SPRINT "BG2_DREAM" "O#XAND"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "O#XANJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "O#XAN25J"
				END
			OUTER_SPRINT "TOB_BCS" "O#Xan25S"
			OUTER_SPRINT "TOB_BANTER" "BO#XAN25"
			OUTER_SPRINT "TOB_DREAM" "O#XAN25D"

ACTION_FOR_EACH bcs IN

// Mod Xan_BG2 ~O#XanS~ ~O#Xan25S~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/O#XAN_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

/////////////////////////// Coran BG2 ///////////////////////////

		// BG2
		OUTER_SPRINT "BG2_JOINED" "O#CoranJ"
		OUTER_SPRINT "BG2_BCS" "O#CORANS"
		OUTER_SPRINT "BG2_BANTER" "BO#Coran"
		OUTER_SPRINT "BG2_DREAM" "O#CoranD"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "O#CoranJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "O#Cor25J"
				END
			OUTER_SPRINT "TOB_BCS" "O#COR25S"
			OUTER_SPRINT "TOB_BANTER" "BO#Cor25"
			OUTER_SPRINT "TOB_DREAM" "O#Cor25D"

ACTION_FOR_EACH bcs IN

// Mod Xan_BG2 ~O#CORANS~ ~O#COR25S~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/O#Coran_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

/////////////////////////// Auren Aseph ///////////////////////////

		// BG2
		OUTER_SPRINT "BG2_JOINED" "K#AurenJ"
		OUTER_SPRINT "BG2_BCS" "K#Auren"
		OUTER_SPRINT "BG2_BANTER" "K#AurenB"
		OUTER_SPRINT "BG2_DREAM" "K#AurenD"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "K#AurenJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "K#Aur25J"
				END
			OUTER_SPRINT "TOB_BCS" "K#Aure25"
			OUTER_SPRINT "TOB_BANTER" "K#Aur25B"
			OUTER_SPRINT "TOB_DREAM" "K#Aur25D"

ACTION_FOR_EACH bcs IN

// Mod Auren ~K#Auren~ ~K#Aure25~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/K#AUREN_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

/////////////////////////// Isra BG2 ///////////////////////////

		// BG2
		OUTER_SPRINT "BG2_JOINED" "rh#isrj"
		OUTER_SPRINT "BG2_BCS" "rh#isr"
		OUTER_SPRINT "BG2_BANTER" "BRH#isr"
		OUTER_SPRINT "BG2_DREAM" "rh#isrd"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "rh#isrj"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "rh#is25j"
				END
			OUTER_SPRINT "TOB_BCS" "rh#is25"
			OUTER_SPRINT "TOB_BANTER" "BRH#is25"
			OUTER_SPRINT "TOB_DREAM" "rh#is25d"

ACTION_FOR_EACH bcs IN

// Mod Isra_BG2 ~rh#isr~ ~rh#is25~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/rh#Isra2_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

/////////////////////////// Nephele ///////////////////////////

		// BG2
		OUTER_SPRINT "BG2_JOINED" "LK#NEPJ"
		OUTER_SPRINT "BG2_BCS" "LK#NEPH"
		OUTER_SPRINT "BG2_BANTER" "BLK#NEP"
		OUTER_SPRINT "BG2_DREAM" "LK#NEPD"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "LK#NEPJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "LK#NE25J"
				END
			OUTER_SPRINT "TOB_BCS" "LK#NE25"
			OUTER_SPRINT "TOB_BANTER" "BLK#NE25"
			OUTER_SPRINT "TOB_DREAM" "LK#NE25D"

ACTION_FOR_EACH bcs IN

// Mod Nephele_Samios ~lk#neph~ ~lk#ne25~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Nephele_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

/////////////////////////// Sheena ///////////////////////////

		// BG2
		OUTER_SPRINT "BG2_JOINED" "SHEENAJ"
		OUTER_SPRINT "BG2_BCS" "K#Sheena"
		OUTER_SPRINT "BG2_BANTER" "BSHEENA"
		OUTER_SPRINT "BG2_DREAM" "SHEENAD"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "SHEENAJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "SHEENA25J" // (9 letters to correct in Sheenna mod)
				END
			OUTER_SPRINT "TOB_BCS" "SHEENA25"
			OUTER_SPRINT "TOB_BANTER" "BSHEENA25" // (9 letters to correct in Sheenna mod)
			OUTER_SPRINT "TOB_DREAM" "SHEENA25D" // (9 letters to correct in Sheenna mod)

ACTION_FOR_EACH bcs IN

// Mod Sheena ~K#Sheena~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/K#SHEENA_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

/////////////////////////// Kiara / Zaiya ///////////////////////////

		// BG2
		OUTER_SPRINT "BG2_JOINED" "KIARAJ"
		OUTER_SPRINT "BG2_BCS" "KIARA"
		OUTER_SPRINT "BG2_BANTER" "BKIARA"
		OUTER_SPRINT "BG2_DREAM" "KIARAD"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "KIARAJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "KIAR25J"
				END
			OUTER_SPRINT "TOB_BCS" "KIAR25"
			OUTER_SPRINT "TOB_BANTER" "BKIAR25"
			OUTER_SPRINT "TOB_DREAM" "KIAR25D"

ACTION_FOR_EACH bcs IN

// Mod Kiara ~kiara~ ~kiar25~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Kiara_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

		// BG2
		OUTER_SPRINT "BG2_JOINED" "ZAIYAJ"
		OUTER_SPRINT "BG2_BCS" "ZAIYA"
		OUTER_SPRINT "BG2_BANTER" "BZAIYA"
		OUTER_SPRINT "BG2_DREAM" "ZAIYAD"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "ZAIYAJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "ZAI25J"
				END
			OUTER_SPRINT "TOB_BCS" "ZAI25"
			OUTER_SPRINT "TOB_BANTER" "BZAI25"
			OUTER_SPRINT "TOB_DREAM" "ZAI25D"

ACTION_FOR_EACH bcs IN

// Mod Zaiya ~Zaiya~ ~zai25~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Zaiya_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

/////////////////////////// The Beaurin Legacy ///////////////////////////

		// BG2
		OUTER_SPRINT "BG2_JOINED" "QI#MIJ"
		OUTER_SPRINT "BG2_BCS" "QI#MIS"
		OUTER_SPRINT "BG2_BANTER" "QI#MiB"
		OUTER_SPRINT "BG2_DREAM" "QI#MiD"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "QI#MIJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "QI#M25J"
				END
			OUTER_SPRINT "TOB_BCS" "QI#M25S"
			OUTER_SPRINT "TOB_BANTER" "QI#M25B"
			OUTER_SPRINT "TOB_DREAM" "QI#M25D"

ACTION_FOR_EACH bcs IN

// Mod Minyae ~QI#MIS~ ~QI#M25S~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/QI#MI_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

		// BG2
		OUTER_SPRINT "BG2_JOINED" "QI#ELAJ"
		OUTER_SPRINT "BG2_BCS" "QI#ELAS"
		OUTER_SPRINT "BG2_BANTER" "QI#ELAB"
		OUTER_SPRINT "BG2_DREAM" "QI#ELAD"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "QI#ELAJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "QI#E25J"
				END
			OUTER_SPRINT "TOB_BCS" "QI#E25S"
			OUTER_SPRINT "TOB_BANTER" "QI#E25B"
			OUTER_SPRINT "TOB_DREAM" "QI#E25D"

ACTION_FOR_EACH bcs IN

// Mod Elaryn ~QI#ElaS~ ~QI#E25S~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/QI#ELA_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

/////////////////////////// Tyris Flare ///////////////////////////

		// BG2
		OUTER_SPRINT "BG2_JOINED" "G#TYRISJ"
		OUTER_SPRINT "BG2_BCS" "G#TYRIS"
		OUTER_SPRINT "BG2_BANTER" "BG#TYRIS"
		OUTER_SPRINT "BG2_DREAM" "G#TYRISD"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "G#TYRISJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "G#TRS25J"
				END
			OUTER_SPRINT "TOB_BCS" "G#TYRS25"
			OUTER_SPRINT "TOB_BANTER" "BG#TRS25"
			OUTER_SPRINT "TOB_DREAM" "G#TRS25D"

ACTION_FOR_EACH bcs IN

// Mod Tyris ~g#tyris~ ~g#tyrs25~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/g#Tyris_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

/////////////////////////// Region of Terror ///////////////////////////

		// BG2
		OUTER_SPRINT "BG2_JOINED" "Wulfg2J"
		OUTER_SPRINT "BG2_BCS" "WULFG2"
		OUTER_SPRINT "BG2_BANTER" "BWulfg2"
		OUTER_SPRINT "BG2_DREAM" ""
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "Wulfg2J"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" ""
				END
			OUTER_SPRINT "TOB_BCS" ""
			OUTER_SPRINT "TOB_BANTER" ""
			OUTER_SPRINT "TOB_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Wulfgar_Terror ~WULFG2~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Wulfg2_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

		// BG2
		OUTER_SPRINT "BG2_JOINED" "Reg2J"
		OUTER_SPRINT "BG2_BCS" "REG2"
		OUTER_SPRINT "BG2_BANTER" "BReg2"
		OUTER_SPRINT "BG2_DREAM" ""
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "Reg2J"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" ""
				END
			OUTER_SPRINT "TOB_BCS" ""
			OUTER_SPRINT "TOB_BANTER" ""
			OUTER_SPRINT "TOB_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Regis_Terror ~REG2~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Reg2_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

		// BG2
		OUTER_SPRINT "BG2_JOINED" "Driz2J"
		OUTER_SPRINT "BG2_BCS" "DRIZ21"
		OUTER_SPRINT "BG2_BANTER" "BDriz2"
		OUTER_SPRINT "BG2_DREAM" ""
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "Driz2J"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" ""
				END
			OUTER_SPRINT "TOB_BCS" ""
			OUTER_SPRINT "TOB_BANTER" ""
			OUTER_SPRINT "TOB_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Drizzt_Terror ~DRIZ21~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Driz2_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

		// BG2
		OUTER_SPRINT "BG2_JOINED" "Brue2J"
		OUTER_SPRINT "BG2_BCS" "Brue2"
		OUTER_SPRINT "BG2_BANTER" "BBrue2"
		OUTER_SPRINT "BG2_DREAM" ""
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "Brue2J"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" ""
				END
			OUTER_SPRINT "TOB_BCS" ""
			OUTER_SPRINT "TOB_BANTER" ""
			OUTER_SPRINT "TOB_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Bruenor_Terror ~Brue2~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Brue2_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

		// BG2
		OUTER_SPRINT "BG2_JOINED" "Catt2J"
		OUTER_SPRINT "BG2_BCS" "Catt2"
		OUTER_SPRINT "BG2_BANTER" "BCatt2"
		OUTER_SPRINT "BG2_DREAM" ""
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "Catt2J"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" ""
				END
			OUTER_SPRINT "TOB_BCS" ""
			OUTER_SPRINT "TOB_BANTER" ""
			OUTER_SPRINT "TOB_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Catti-Brie_Terror ~Catt2~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Catt2_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

		// BG2
		OUTER_SPRINT "BG2_JOINED" "Enter2J" // Missing (created at installation)
		OUTER_SPRINT "BG2_BCS" "ENTER2"
		OUTER_SPRINT "BG2_BANTER" "BEnter2"
		OUTER_SPRINT "BG2_DREAM" ""
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "Enter2J"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" ""
				END
			OUTER_SPRINT "TOB_BCS" ""
			OUTER_SPRINT "TOB_BANTER" ""
			OUTER_SPRINT "TOB_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Artemis_Entreri_Terror ~ENTER2~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Enter2_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

ACTION_IF FILE_EXISTS_IN_GAME ~Jarlax2.cre~ BEGIN
		COPY_EXISTING ~Jarlax2.CRE~ ~override/Jarlax2.CRE~
		WRITE_ASCII SCRIPT_OVERRIDE ~Jarlax2~ (8)
	END

COPY ~JOining_Party_Select/Baf/JO_JOIN/EMPTY.baf~ ~override/Jarlax2.bcs~

		// BG2
		OUTER_SPRINT "BG2_JOINED" "Jarlax2J" // Missing (created at installation)
		OUTER_SPRINT "BG2_BCS" "Jarlax2"
		OUTER_SPRINT "BG2_BANTER" "BJarlax2"
		OUTER_SPRINT "BG2_DREAM" ""
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "Jarlax2J"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" ""
				END
			OUTER_SPRINT "TOB_BCS" ""
			OUTER_SPRINT "TOB_BANTER" ""
			OUTER_SPRINT "TOB_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Jarlaxle_Terror ~Jarlax2~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Jarlax2_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

ACTION_IF FILE_EXISTS_IN_GAME ~Tapio.cre~ BEGIN
		COPY_EXISTING ~Tapio.CRE~ ~override/Tapio.CRE~
		WRITE_ASCII SCRIPT_OVERRIDE ~Tapio~ (8)
	END

COPY ~JOining_Party_Select/Baf/JO_JOIN/EMPTY.baf~ ~override/Tapio.bcs~

		// BG2
		OUTER_SPRINT "BG2_JOINED" "TapioJ"
		OUTER_SPRINT "BG2_BCS" "Tapio"
		OUTER_SPRINT "BG2_BANTER" "BTapio"
		OUTER_SPRINT "BG2_DREAM" ""
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "TapioJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" ""
				END
			OUTER_SPRINT "TOB_BCS" ""
			OUTER_SPRINT "TOB_BANTER" ""
			OUTER_SPRINT "TOB_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Tapio_Perkiomaki_Terror ~Tapio~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Tapio_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

		// BG2
		OUTER_SPRINT "BG2_JOINED" "RandallJ"
		OUTER_SPRINT "BG2_BCS" "RANDALL"
		OUTER_SPRINT "BG2_BANTER" "BRandall"
		OUTER_SPRINT "BG2_DREAM" ""
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "RandallJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" ""
				END
			OUTER_SPRINT "TOB_BCS" ""
			OUTER_SPRINT "TOB_BANTER" ""
			OUTER_SPRINT "TOB_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Randall_Terror ~RANDALL~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Randall_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

		// BG2
		OUTER_SPRINT "BG2_JOINED" "Alissa1J"
		OUTER_SPRINT "BG2_BCS" "ALISSA1"
		OUTER_SPRINT "BG2_BANTER" "BAlissa1"
		OUTER_SPRINT "BG2_DREAM" ""
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "Alissa1J"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" ""
				END
			OUTER_SPRINT "TOB_BCS" ""
			OUTER_SPRINT "TOB_BANTER" ""
			OUTER_SPRINT "TOB_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Alissa_Terror ~ALISSA1~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/ALISSA1_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

ACTION_IF FILE_EXISTS_IN_GAME ~Mordrg1.cre~ BEGIN
		COPY_EXISTING ~Mordrg1.CRE~ ~override/Mordrg1.CRE~
		WRITE_ASCII SCRIPT_OVERRIDE ~Mordrg~ (8)
	END
ACTION_IF FILE_EXISTS_IN_GAME ~Mordrg2.cre~ BEGIN
		COPY_EXISTING ~Mordrg2.CRE~ ~override/Mordrg2.CRE~
		WRITE_ASCII SCRIPT_OVERRIDE ~Mordrg~ (8)
	END
ACTION_IF FILE_EXISTS_IN_GAME ~Mordrg3.cre~ BEGIN
		COPY_EXISTING ~Mordrg3.CRE~ ~override/Mordrg3.CRE~
		WRITE_ASCII SCRIPT_OVERRIDE ~Mordrg~ (8)
	END
ACTION_IF FILE_EXISTS_IN_GAME ~Mordrg4.cre~ BEGIN
		COPY_EXISTING ~Mordrg4.CRE~ ~override/Mordrg4.CRE~
		WRITE_ASCII SCRIPT_OVERRIDE ~Mordrg~ (8)
	END

COPY ~JOining_Party_Select/Baf/JO_JOIN/EMPTY.baf~ ~override/Mordrg.bcs~

		// BG2
		OUTER_SPRINT "BG2_JOINED" "MordrgJ" // Missing (created at installation)
		OUTER_SPRINT "BG2_BCS" "Mordrg"
		OUTER_SPRINT "BG2_BANTER" "BMordrg"
		OUTER_SPRINT "BG2_DREAM" ""
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "MordrgJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" ""
				END
			OUTER_SPRINT "TOB_BCS" ""
			OUTER_SPRINT "TOB_BANTER" ""
			OUTER_SPRINT "TOB_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Mordragon_Terror ~Mordrg~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Mordrg_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

/////////////////////////// Shadow over Soubar ///////////////////////////

		// BG2
		OUTER_SPRINT "BG2_JOINED" "SELENCEJ"
		OUTER_SPRINT "BG2_BCS" "SELENCE"
		OUTER_SPRINT "BG2_BANTER" ""
		OUTER_SPRINT "BG2_DREAM" ""
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "SELENCEJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" ""
				END
			OUTER_SPRINT "TOB_BCS" ""
			OUTER_SPRINT "TOB_BANTER" ""
			OUTER_SPRINT "TOB_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Selence_Hillstar_Soubar ~SELENCE~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/SELENCE_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

		// BG2
		OUTER_SPRINT "BG2_JOINED" "CHARLOTJ"
		OUTER_SPRINT "BG2_BCS" "CHARLOT0"
		OUTER_SPRINT "BG2_BANTER" ""
		OUTER_SPRINT "BG2_DREAM" ""
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "CHARLOTJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" ""
				END
			OUTER_SPRINT "TOB_BCS" ""
			OUTER_SPRINT "TOB_BANTER" ""
			OUTER_SPRINT "TOB_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Charlotte_Soubar ~CHARLOT0~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/CHARLOTT_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

ACTION_IF FILE_EXISTS_IN_GAME ~BOLIVR09.cre~ BEGIN
		COPY_EXISTING ~BOLIVR09.CRE~ ~override/BOLIVR09.CRE~
		WRITE_ASCII SCRIPT_OVERRIDE ~BOLIVAR1~ (8)
	END
ACTION_IF FILE_EXISTS_IN_GAME ~BOLIVR15.cre~ BEGIN
		COPY_EXISTING ~BOLIVR15.CRE~ ~override/BOLIVR15.CRE~
		WRITE_ASCII SCRIPT_OVERRIDE ~BOLIVAR1~ (8)
	END
ACTION_IF FILE_EXISTS_IN_GAME ~BOLIVR09.cre~ BEGIN
		COPY_EXISTING ~BOLIVR20.CRE~ ~override/BOLIVR20.CRE~
		WRITE_ASCII SCRIPT_OVERRIDE ~BOLIVAR1~ (8)
	END

COPY ~JOining_Party_Select/Baf/JO_JOIN/EMPTY.baf~ ~override/BOLIVAR1.bcs~

		// BG2
		OUTER_SPRINT "BG2_JOINED" "BOLIVARJ"
		OUTER_SPRINT "BG2_BCS" "BOLIVAR1"
		OUTER_SPRINT "BG2_BANTER" ""
		OUTER_SPRINT "BG2_DREAM" ""
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "BOLIVARJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" ""
				END
			OUTER_SPRINT "TOB_BCS" ""
			OUTER_SPRINT "TOB_BANTER" ""
			OUTER_SPRINT "TOB_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Bolivar_Soubar ~BOLIVAR1~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/BOLIVAR_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

		// BG2
		OUTER_SPRINT "BG2_JOINED" "TOMASTOJ"
		OUTER_SPRINT "BG2_BCS" "TOMASTOM"
		OUTER_SPRINT "BG2_BANTER" ""
		OUTER_SPRINT "BG2_DREAM" ""
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "TOMASTOJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" ""
				END
			OUTER_SPRINT "TOB_BCS" ""
			OUTER_SPRINT "TOB_BANTER" ""
			OUTER_SPRINT "TOB_DREAM" ""

ACTION_FOR_EACH bcs IN

// Mod Tomas_Tomalson_Soubar ~TOMASTOM~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/TOMASTM_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

// Ajantis_BG2

		// BG2
		OUTER_SPRINT "BG2_JOINED" "C#AjanJ"
		OUTER_SPRINT "BG2_BCS" "C#Ajan"
		OUTER_SPRINT "BG2_BANTER" "C#AjanB"
		OUTER_SPRINT "BG2_DREAM" "C#AjanD"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "C#AjanJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "C#Aja25J"
				END
			OUTER_SPRINT "TOB_BCS" "C#Ajan25"
			OUTER_SPRINT "TOB_BANTER" "C#Aja25B"
			OUTER_SPRINT "TOB_DREAM" "C#Aja25D"

ACTION_FOR_EACH bcs IN

// Mod Ajantis_BG2 ~C#Ajan~ ~C#Ajan25~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/C#Ajantis_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

// Kivan and Deheriana

		// BG2
		OUTER_SPRINT "BG2_JOINED" "P#KIVJ"
		OUTER_SPRINT "BG2_BCS" "P#KIV01"
		OUTER_SPRINT "BG2_BANTER" "BP#KIV"
		OUTER_SPRINT "BG2_DREAM" "P#KIVD"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "P#KIVJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "P#KI25J"
				END
			OUTER_SPRINT "TOB_BCS" "P#KI25"
			OUTER_SPRINT "TOB_BANTER" "BP#KIV25"
			OUTER_SPRINT "TOB_DREAM" "P#KI25D"

ACTION_FOR_EACH bcs IN

// Mod Kivan_BG2 ~P#KIV01~ ~P#KI25~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/P#KIVAN_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

		// BG2
		OUTER_SPRINT "BG2_JOINED" "P#DEHJ"
		OUTER_SPRINT "BG2_BCS" "P#DEH01"
		OUTER_SPRINT "BG2_BANTER" "BP#DEH"
		OUTER_SPRINT "BG2_DREAM" "P#DEHD"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "P#DEHJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "P#DE25J"
				END
			OUTER_SPRINT "TOB_BCS" "P#DE25"
			OUTER_SPRINT "TOB_BANTER" "BP#DEH25"
			OUTER_SPRINT "TOB_DREAM" "P#DE25D"

ACTION_FOR_EACH bcs IN

// Mod Deheriana ~P#DEH01~ ~P#DE25~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/P#DEHER_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

// Yvette

		// BG2
		OUTER_SPRINT "BG2_JOINED" "YxYveJ"
		OUTER_SPRINT "BG2_BCS" "YxYve"
		OUTER_SPRINT "BG2_BANTER" "YxYveB"
		OUTER_SPRINT "BG2_DREAM" "YxYveD"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "YxYveJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "YXYV25J"
				END
			OUTER_SPRINT "TOB_BCS" "YxYv25"
			OUTER_SPRINT "TOB_BANTER" "YxYv25B"
			OUTER_SPRINT "TOB_DREAM" "YxYv25D"

ACTION_FOR_EACH bcs IN

// Mod Yvette ~YxYve~ ~YxYv25~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/YxYve_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

// The Luxley Family

		// BG2
		OUTER_SPRINT "BG2_JOINED" "FHLSEBJ"
		OUTER_SPRINT "BG2_BCS" "fhlseb"
		OUTER_SPRINT "BG2_BANTER" "BFHLSEB"
		OUTER_SPRINT "BG2_DREAM" "FHLSEBD"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "FHLSEBJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "FHLS25J"
				END
			OUTER_SPRINT "TOB_BCS" "FHLS25"
			OUTER_SPRINT "TOB_BANTER" "BFHSEB25"
			OUTER_SPRINT "TOB_DREAM" "FHLS25D"

ACTION_FOR_EACH bcs IN

// Mod Sebastian ~fhlseb~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/fhlseb_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

		// BG2
		OUTER_SPRINT "BG2_JOINED" "FHLANDJ"
		OUTER_SPRINT "BG2_BCS" "FHLAND"
		OUTER_SPRINT "BG2_BANTER" "BFHLAND"
		OUTER_SPRINT "BG2_DREAM" "FHLANDD"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "FHLANDJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "FHLA25J"
				END
			OUTER_SPRINT "TOB_BCS" ""
			OUTER_SPRINT "TOB_BANTER" "BFHLAND"
			OUTER_SPRINT "TOB_DREAM" "FHLA25D"

ACTION_FOR_EACH bcs IN

// Mod Andrei ~FHLAND~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/FHLAND_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

//  Beyond the Law

		// BG2
		OUTER_SPRINT "BG2_JOINED" "z#kiyoJ"
		OUTER_SPRINT "BG2_BCS" "z#kiyone"
		OUTER_SPRINT "BG2_BANTER" "z#kiyoB"
		OUTER_SPRINT "BG2_DREAM" "z#kiyoD"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "z#kiyoJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" ""
				END
			OUTER_SPRINT "TOB_BCS" "z#kiyone"
			OUTER_SPRINT "TOB_BANTER" "z#ky25B"
			OUTER_SPRINT "TOB_DREAM" "z#ky25D"

ACTION_FOR_EACH bcs IN

// Mod Kiyone ~z#kiyone~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Kiyone_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

		// BG2
		OUTER_SPRINT "BG2_JOINED" "z#kovaJ"
		OUTER_SPRINT "BG2_BCS" "z#kova"
		OUTER_SPRINT "BG2_BANTER" "z#kovaB"
		OUTER_SPRINT "BG2_DREAM" "z#kovaD"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "z#kovaJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" ""
				END
			OUTER_SPRINT "TOB_BCS" "z#kova"
			OUTER_SPRINT "TOB_BANTER" "z#kv25B"
			OUTER_SPRINT "TOB_DREAM" "z#kv25D"

ACTION_FOR_EACH bcs IN

// Mod Kova ~z#kova~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Kova_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

// Petsy

		// BG2
		OUTER_SPRINT "BG2_JOINED" "L3PetsyJ"
		OUTER_SPRINT "BG2_BCS" "L3PETSY"
		OUTER_SPRINT "BG2_BANTER" "L3PetsyB"
		OUTER_SPRINT "BG2_DREAM" "L3PetsyD"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "L3PetsyJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "L3Pet25"
				END
			OUTER_SPRINT "TOB_BCS" "L3Pet25"
			OUTER_SPRINT "TOB_BANTER" "L3Pet25B"
			OUTER_SPRINT "TOB_DREAM" "L3Pet25D"

ACTION_FOR_EACH bcs IN

// Mod Petsy ~L3PETSY~ ~L3Pet25~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/L3PETSY_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

// Kale BG2

		// BG2
		OUTER_SPRINT "BG2_JOINED" "X3KalJ"
		OUTER_SPRINT "BG2_BCS" "X3Kal"
		OUTER_SPRINT "BG2_BANTER" "BX3Kal"
		OUTER_SPRINT "BG2_DREAM" "X3KalD"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "X3KalJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "X3Kal25J"
				END
			OUTER_SPRINT "TOB_BCS" "X3Kal25"
			OUTER_SPRINT "TOB_BANTER" "BX3Kal25"
			OUTER_SPRINT "TOB_DREAM" "X3Kal25D"

ACTION_FOR_EACH bcs IN

// Mod Kale_BG2 ~X3Kal~ ~X3Kal25~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/X3Kal_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

// Walahnan BG2

		// BG2
		OUTER_SPRINT "BG2_JOINED" "L#2WHJ"
		OUTER_SPRINT "BG2_BCS" "L#2WH"
		OUTER_SPRINT "BG2_BANTER" "L#2WHB"
		OUTER_SPRINT "BG2_DREAM" "L#2WHD"
			// ToB
				ACTION_IF (GAME_IS ~eet~) BEGIN
			OUTER_SPRINT "TOB_JOINED" "L#2WHJ"
				END ELSE BEGIN
			OUTER_SPRINT "TOB_JOINED" "L#2WH25J"
				END
			OUTER_SPRINT "TOB_BCS" "L#2WH25"
			OUTER_SPRINT "TOB_BANTER" "L#2WH25B"
			OUTER_SPRINT "TOB_DREAM" "L#2WH25D"

ACTION_FOR_EACH bcs IN

// Mod Walahnan_BG2 ~L#2WH~ ~L#2WH25~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/L#2WALAH_All_In.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Mod_BG2.tpa~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

// Next_Traveler BG2
