/////////////////////////// Original ///////////////////////////

/////////////// Reset

// BG1
OUTER_SPRINT "BG1_JOINED" ""
OUTER_SPRINT "BG1_BCS" ""
OUTER_SPRINT "BG1_BANTER" ""
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
	OUTER_SPRINT "SoD_JOINED" ""
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""
		// BG2
		OUTER_SPRINT "BG2_JOINED" ""
		OUTER_SPRINT "BG2_BCS" ""
		OUTER_SPRINT "BG2_BANTER" ""
		OUTER_SPRINT "BG2_DREAM" ""
			// ToB
			OUTER_SPRINT "TOB_JOINED" ""
			OUTER_SPRINT "TOB_BCS" ""
			OUTER_SPRINT "TOB_BANTER" ""
			OUTER_SPRINT "TOB_DREAM" ""

/////////////////////////// Continuous ///////////////////////////

 OUTER_SET JOining_Imoen = 0
 OUTER_SET JOining_Edwin = 0
 OUTER_SET JOining_Jaheira = 0
 OUTER_SET JOining_Minsc = 0
 OUTER_SET JOining_Viconia = 0
 OUTER_SET JOining_Dorn = 0
 OUTER_SET JOining_Neera = 0
 OUTER_SET JOining_Rasaad = 0

// Imoen

 OUTER_SET JOining_Imoen = 1

ACTION_FOR_EACH bcs IN

/////////////////////////// Continuous ///////////////////////////

// Original Imoen ~%IMOEN_BCS%~ ~BDIMOENS~ ~IMOE25~ ~Imoen~ // BDIMOENS is for Imoen4Ever // ~TTIMOEN~
// Original Imoen // EET_END ~IMOEN_~
// Original Imoen // EET_ODD ~IMOEN2~

BEGIN

// BG1
OUTER_SPRINT "BG1_BANTER" "BIMOEN"
	ACTION_IF (GAME_IS ~eet~) BEGIN
OUTER_SPRINT "BG1_DREAM" "IMOEND_"
 	END ELSE BEGIN
OUTER_SPRINT "BG1_DREAM" "IMOEND"
	END
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDIMOENB"
	OUTER_SPRINT "SoD_DREAM" "BDIMOEND"
		// BG2
		OUTER_SPRINT "BG2_BANTER" "BIMOEN2"
		OUTER_SPRINT "BG2_DREAM" "IMOEN2D"
			// ToB
			OUTER_SPRINT "TOB_BANTER" "BIMOEN25"
			OUTER_SPRINT "TOB_DREAM" "IMOEN2D"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/%IMOEN_DV%_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_Continuous.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

ACTION_IF (NOT ~%bcs%~ STRING_EQUAL_CASE ~IMOEN~) BEGIN // IMOEN10 Irenicus donjon

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_Continuous.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_Continuous.tph~

END

	END
END

 OUTER_SET JOining_Imoen = 0

// Edwin

 OUTER_SET JOining_Edwin = 1

ACTION_FOR_EACH bcs IN

// Original Edwin ~%EDWIN_BCS%~ ~EDWI25~ ~BDEDWIN~
// Original Edwin // EET_END ~EDWIN_~
// Original Edwin // EET_ODD ~EDWIN~

BEGIN

// BG1
	ACTION_IF (GAME_IS ~eet~) BEGIN
OUTER_SPRINT "BG1_BANTER" "BEDWIN_"
OUTER_SPRINT "BG1_DREAM" "EDWIND_"
 	END ELSE BEGIN
OUTER_SPRINT "BG1_BANTER" "BEDWIN"
OUTER_SPRINT "BG1_DREAM" "EDWIND"
	END
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDEDWINB"
	OUTER_SPRINT "SoD_DREAM" "BDEDWIND"
		// BG2
		OUTER_SPRINT "BG2_BANTER" "BEDWIN"
		OUTER_SPRINT "BG2_DREAM" "EDWIND"
			// ToB
			OUTER_SPRINT "TOB_BANTER" "BEDWIN25"
			OUTER_SPRINT "TOB_DREAM" "EDWIND"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Edwin_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_Continuous.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_Continuous.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_Continuous.tph~

	END
END

 OUTER_SET JOining_Edwin = 0

// Jaheira

 OUTER_SET JOining_Jaheira = 1

ACTION_FOR_EACH bcs IN

// Original Jaheira ~%JAHEIRA_BCS%~ ~JAHE25~ ~BDJAHEIR~ // ~TTJAHEIR~
// Original Jaheira // EET_END ~JAHEIRA_~
// Original Jaheira // EET_ODD ~JAHEIRA~

BEGIN

// BG1
OUTER_SPRINT "BG1_BANTER" "BJAHEI"
OUTER_SPRINT "BG1_DREAM" "JAHEID"
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDJAHEIB"
	OUTER_SPRINT "SoD_DREAM" "BDJAHEID"
		// BG2
		OUTER_SPRINT "BG2_DREAM" "JAHEIRAD"
		OUTER_SPRINT "BG2_BANTER" "BJAHEIR"
			// ToB
			OUTER_SPRINT "TOB_BANTER" "BJAHEI25"
			OUTER_SPRINT "TOB_DREAM" "JAHEI25D"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Jaheira_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_Continuous.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_Continuous.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_Continuous.tph~

	END
END

 OUTER_SET JOining_Jaheira = 0

// Minsc

 OUTER_SET JOining_Minsc = 1

ACTION_FOR_EACH bcs IN

// Original Minsc ~%MINSC_BCS%~ ~MINS25~ ~BDMINSC~ // ~TTMINSC~
// Original Minsc // EET_END ~MINSC_~
// Original Minsc // EET_ODD ~MINSC~

BEGIN

// BG1
	ACTION_IF (GAME_IS ~eet~) BEGIN
OUTER_SPRINT "BG1_BANTER" "BMINSC_"
OUTER_SPRINT "BG1_DREAM" "MINSCD_"
 	END ELSE BEGIN
OUTER_SPRINT "BG1_BANTER" "BMINSC"
OUTER_SPRINT "BG1_DREAM" "MINSCD"
	END
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDMINSCB"
	OUTER_SPRINT "SoD_DREAM" "BDMINSCD"
		// BG2
		OUTER_SPRINT "BG2_BANTER" "BMINSC"
		OUTER_SPRINT "BG2_DREAM" "MINSCD"
			// ToB
			OUTER_SPRINT "TOB_BANTER" "BMINSC25"
			OUTER_SPRINT "TOB_DREAM" "MINSCD"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Minsc_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_Continuous.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_Continuous.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_Continuous.tph~

	END
END

 OUTER_SET JOining_Minsc = 0

// Viconia

 OUTER_SET JOining_Viconia = 1

ACTION_FOR_EACH bcs IN

// Original Viconia ~%VICONIA_BCS%~ ~VICO25~ ~BDVICONI~
// Original Viconia // EET_END ~VICONIA_~
// Original Viconia // EET_ODD ~VICONIA~

BEGIN

// BG1
OUTER_SPRINT "BG1_BANTER" "BVICON"
	ACTION_IF (GAME_IS ~eet~) BEGIN
OUTER_SPRINT "BG1_DREAM" "VICOND_"
 	END ELSE BEGIN
OUTER_SPRINT "BG1_DREAM" "VICOND"
	END
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDVICONB"
	OUTER_SPRINT "SoD_DREAM" "BDVICOND"
		// BG2
		OUTER_SPRINT "BG2_BANTER" "BVICONI"
		OUTER_SPRINT "BG2_DREAM" "VICOND"
			// ToB
			OUTER_SPRINT "TOB_BANTER" "BVICON25"
			OUTER_SPRINT "TOB_DREAM" "VICON25D"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Viconia_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_Continuous.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_Continuous.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_Continuous.tph~

	END
END

 OUTER_SET JOining_Viconia = 0

// Dorn

 OUTER_SET JOining_Dorn = 1

ACTION_FOR_EACH bcs IN

// Original Dorn ~%DORN_BCS%~ ~DORN25~ ~BDDORN~
// Original Dorn // EET_END ~DORN_~
// Original Dorn // EET_ODD ~DORN~

BEGIN

// BG1
	ACTION_IF (GAME_IS ~eet~) BEGIN
OUTER_SPRINT "BG1_BANTER" "BDORN_"
OUTER_SPRINT "BG1_DREAM" "DORND_"
 	END ELSE BEGIN
OUTER_SPRINT "BG1_BANTER" "BDORN"
OUTER_SPRINT "BG1_DREAM" "DORND"
	END
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDDORNB"
	OUTER_SPRINT "SoD_DREAM" "BDDORND"
		// BG2
		OUTER_SPRINT "BG2_BANTER" "BDORN"
		OUTER_SPRINT "BG2_DREAM" "DORND"
			// ToB
			OUTER_SPRINT "TOB_BANTER" "BDORN25"
			OUTER_SPRINT "TOB_DREAM" "DORN25D"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Dorn_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_Continuous.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_Continuous.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_Continuous.tph~

	END
END

 OUTER_SET JOining_Dorn = 0

// Neera

 OUTER_SET JOining_Neera = 1

ACTION_FOR_EACH bcs IN

// Original Neera ~%NEERA_BCS%~ ~NEER25~ ~BDNEERA~
// Original Neera // EET_END ~NEERA_~
// Original Neera // EET_ODD ~NEERA~

BEGIN

// BG1
	ACTION_IF (GAME_IS ~eet~) BEGIN
OUTER_SPRINT "BG1_BANTER" "BNEERA_"
OUTER_SPRINT "BG1_DREAM" "NEERAD_"
 	END ELSE BEGIN
OUTER_SPRINT "BG1_BANTER" "BNEERA"
OUTER_SPRINT "BG1_DREAM" "NEERAD"
	END
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDNEERAB"
	OUTER_SPRINT "SoD_DREAM" "BDNEERAD"
		// BG2
		OUTER_SPRINT "BG2_BANTER" "BNEERA"
		OUTER_SPRINT "BG2_DREAM" "NEERAD"
			// ToB
			OUTER_SPRINT "TOB_BANTER" "BNEERA25"
			OUTER_SPRINT "TOB_DREAM" "NEERA25D"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Neera_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_Continuous.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_Continuous.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_Continuous.tph~

	END
END

 OUTER_SET JOining_Neera = 0

// Rasaad

 OUTER_SET JOining_Rasaad = 1

ACTION_FOR_EACH bcs IN

// Original Rasaad ~%RASAAD_BCS%~ ~RASA25~ ~BDRASAAD~
// Original Rasaad // EET_END ~RASAAD_~
// Original Rasaad // EET_ODD ~RASAAD~

BEGIN

// BG1
	ACTION_IF (GAME_IS ~eet~) BEGIN
OUTER_SPRINT "BG1_BANTER" "BRASAAD_"
OUTER_SPRINT "BG1_DREAM" "RASAADD_"
 	END ELSE BEGIN
OUTER_SPRINT "BG1_BANTER" "BRASAAD"
OUTER_SPRINT "BG1_DREAM" "RASAADD"
	END
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDRASAAB"
	OUTER_SPRINT "SoD_DREAM" "BDRASAAD"
		// BG2
		OUTER_SPRINT "BG2_BANTER" "BRASAAD"
		OUTER_SPRINT "BG2_DREAM" "RASAADD"
			// ToB
			OUTER_SPRINT "TOB_BANTER" "BRASAA25"
			OUTER_SPRINT "TOB_DREAM" "RASAA25D"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Rasaad_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_Continuous.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_Continuous.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_Continuous.tph~

	END
END

 OUTER_SET JOining_Rasaad = 0


//////////////////////////////////////////////////////
//////////////////////////////////////////////////////
//////////////////////////////////////////////////////

/////////////////////////// bg1 ///////////////////////////

 OUTER_SET JOining_Ajantis = 0
 OUTER_SET JOining_Alora = 0
 OUTER_SET JOining_Branwen = 0
 OUTER_SET JOining_Coran = 0
 OUTER_SET JOining_Dynaheir = 0
 OUTER_SET JOining_Eldoth = 0
 OUTER_SET JOining_Faldorn = 0
 OUTER_SET JOining_Garrick = 0
 OUTER_SET JOining_Kagain = 0
 OUTER_SET JOining_Khalid = 0
 OUTER_SET JOining_Kivan = 0
 OUTER_SET JOining_Montaron = 0
 OUTER_SET JOining_Quayle = 0
 OUTER_SET JOining_Safana = 0
 OUTER_SET JOining_Sharteel = 0
 OUTER_SET JOining_Skie = 0
 OUTER_SET JOining_Tiax = 0
 OUTER_SET JOining_Xan = 0
 OUTER_SET JOining_Xzar = 0
 OUTER_SET JOining_Yeslick = 0
 OUTER_SET JOining_Baeloth = 0

/////////////////////////// bg1 ///////////////////////////

// Ajantis

 OUTER_SET JOining_Ajantis = 1

ACTION_FOR_EACH bcs IN

// Original Ajantis ~%AJANTIS_BCS%~ ~BDAJANTI~ // BDAJANTI is for Ajantis_BG1_Expansion // Class script ~BDAJANTC~

BEGIN

// BG1
OUTER_SPRINT "BG1_BANTER" "BAJANT"
OUTER_SPRINT "BG1_DREAM" "AJANTD"
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDAJANTB"
	OUTER_SPRINT "SoD_DREAM" ""

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Ajantis_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

 OUTER_SET JOining_Ajantis = 0

// Alora

 OUTER_SET JOining_Alora = 1

ACTION_FOR_EACH bcs IN

// Original Alora ~%ALORA_BCS%~ // Class script ~BDALORAC~

BEGIN

// BG1
OUTER_SPRINT "BG1_BANTER" "BALORA"
OUTER_SPRINT "BG1_DREAM" "ALORAD"
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDALORAB"
	OUTER_SPRINT "SoD_DREAM" ""

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Alora_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

 OUTER_SET JOining_Alora = 0

// Branwen

 OUTER_SET JOining_Branwen = 1

ACTION_FOR_EACH bcs IN

// Original Branwen ~%BRANWEN_BCS%~ // Class script ~BDBRANWC~ // ~TTBRAN~
// Original Branwen // EET_END ~BRANWEN_~
// Original Branwen // EET_ODD ~BRANWEN~

BEGIN

// BG1
OUTER_SPRINT "BG1_BANTER" "BBRANW"
OUTER_SPRINT "BG1_DREAM" "BRANWD"
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDBRANWB"
	OUTER_SPRINT "SoD_DREAM" ""

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Branwen_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

 OUTER_SET JOining_Branwen = 0

// Coran

 OUTER_SET JOining_Coran = 1

ACTION_FOR_EACH bcs IN

// Original Coran ~%CORAN_BCS%~ // Class script ~BDCORANC~ // ~BDCORAN~

BEGIN

// BG1
OUTER_SPRINT "BG1_BANTER" "BCORAN"
OUTER_SPRINT "BG1_DREAM" "CORAND"
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDCORANB"
	OUTER_SPRINT "SoD_DREAM" ""

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Coran_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

 OUTER_SET JOining_Coran = 0

// Dynaheir

 OUTER_SET JOining_Dynaheir = 1

ACTION_FOR_EACH bcs IN

// Original Dynaheir ~%DYNAHEIR_BCS%~ ~BDDYNAHE~ // Class script ~BDDYNAC~

BEGIN

// BG1
OUTER_SPRINT "BG1_BANTER" "BDYNAH"
OUTER_SPRINT "BG1_DREAM" "DYNAHD"
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDDYNAHB"
	OUTER_SPRINT "SoD_DREAM" "BDDYNAHD"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Dynaheir_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

 OUTER_SET JOining_Dynaheir = 0

// Eldoth

 OUTER_SET JOining_Eldoth = 1

ACTION_FOR_EACH bcs IN

// Original Eldoth ~%ELDOTH_BCS%~ ~BDELDOTH~ // Class script ~BDELDOTC~

BEGIN

// BG1
OUTER_SPRINT "BG1_BANTER" "BELDOT"
OUTER_SPRINT "BG1_DREAM" "ELDOTD"
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDELDOTB"
	OUTER_SPRINT "SoD_DREAM" ""

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Eldoth_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

 OUTER_SET JOining_Eldoth = 0

// Faldorn

 OUTER_SET JOining_Faldorn = 1

ACTION_FOR_EACH bcs IN

// Original Faldorn ~%FALDORN_BCS%~ // Class script ~BDFALDOC~
// Original Faldorn // EET_END ~FALDORN_~
// Original Faldorn // EET_ODD ~FALDORN~

BEGIN

// BG1
OUTER_SPRINT "BG1_BANTER" "BFALDO"
OUTER_SPRINT "BG1_DREAM" "FALDOD"
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDFALDOB"
	OUTER_SPRINT "SoD_DREAM" "FALDOD"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Faldorn_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

 OUTER_SET JOining_Faldorn = 0

// Garrick

 OUTER_SET JOining_Garrick = 1

ACTION_FOR_EACH bcs IN

// Original Garrick ~%GARRICK_BCS%~ // Class script ~BDGARRCC~ // ~BDGARRIC~
// Original Garrick // EET_END ~GARRICK_~
// Original Garrick // EET_ODD ~GARRICK~

BEGIN

// BG1
OUTER_SPRINT "BG1_BANTER" "BGARRI"
OUTER_SPRINT "BG1_DREAM" "GARRID"
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDGARRIB"
	OUTER_SPRINT "SoD_DREAM" ""

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Garrick_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

 OUTER_SET JOining_Garrick = 0

// Kagain

 OUTER_SET JOining_Kagain = 1

ACTION_FOR_EACH bcs IN

// Original Kagain ~%KAGAIN_BCS%~ // Class script ~BDKAGAIC~

BEGIN

// BG1
OUTER_SPRINT "BG1_BANTER" "BKAGAI"
OUTER_SPRINT "BG1_DREAM" "KAGAID"
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDKAGAIB"
	OUTER_SPRINT "SoD_DREAM" ""

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Kagain_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

 OUTER_SET JOining_Kagain = 0

// Khalid

 OUTER_SET JOining_Khalid = 1

ACTION_FOR_EACH bcs IN

// Original Khalid ~%KHALID_BCS%~ ~BDKHALID~ // Class script ~BDKHALIC~

BEGIN

// BG1
OUTER_SPRINT "BG1_BANTER" "BKHALI"
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDKHALIB"
	OUTER_SPRINT "SoD_DREAM" ""

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Khalid_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

 OUTER_SET JOining_Khalid = 0

// Kivan

 OUTER_SET JOining_Kivan = 1

ACTION_FOR_EACH bcs IN

// Original Kivan ~%KIVAN_BCS%~ // Class script ~BDKIVANC~

BEGIN

// BG1
OUTER_SPRINT "BG1_BANTER" "BKIVAN"
OUTER_SPRINT "BG1_DREAM" "KIVAND"
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDKIVANB"
	OUTER_SPRINT "SoD_DREAM" ""

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Kivan_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

 OUTER_SET JOining_Kivan = 0

// Montaron

 OUTER_SET JOining_Montaron = 1

ACTION_FOR_EACH bcs IN

// Original Montaron ~%MONTARON_BCS%~ // Class script ~BDMONTAC~

BEGIN

// BG1
OUTER_SPRINT "BG1_BANTER" "MONTAD"
OUTER_SPRINT "BG1_DREAM" "AJANTD"
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDMONTAB"
	OUTER_SPRINT "SoD_DREAM" ""

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Montaron_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

 OUTER_SET JOining_Montaron = 0

// Quayle

 OUTER_SET JOining_Quayle = 1

ACTION_FOR_EACH bcs IN

// Original Quayle ~%QUAYLE_BCS%~ // Class script ~BDQUALEC~

BEGIN

// BG1
OUTER_SPRINT "BG1_BANTER" "BQUAYL"
OUTER_SPRINT "BG1_DREAM" "QUAYLD"
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDQUAYLB"
	OUTER_SPRINT "SoD_DREAM" ""

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Quayle_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

 OUTER_SET JOining_Quayle = 0

// Safana

 OUTER_SET JOining_Safana = 1

ACTION_FOR_EACH bcs IN

// Original Safana ~%SAFANA_BCS%~ ~BDSAFANA~

BEGIN

// BG1
OUTER_SPRINT "BG1_BANTER" "BSAFAN"
OUTER_SPRINT "BG1_DREAM" "SAFAND"
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDSAFANB"
	OUTER_SPRINT "SoD_DREAM" "BDSAFAND"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Safana_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

 OUTER_SET JOining_Safana = 0

// Sharteel

 OUTER_SET JOining_Sharteel = 1

ACTION_FOR_EACH bcs IN

// Original Sharteel ~%SHARTEEL_BCS%~ ~k9shar~ // Class script ~BDSHARTC~

BEGIN

// BG1
OUTER_SPRINT "BG1_BANTER" "BSHART"
OUTER_SPRINT "BG1_DREAM" "SHARTD"
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDSHARTB"
	OUTER_SPRINT "SoD_DREAM" "SHARTD"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Sharteel_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

 OUTER_SET JOining_Sharteel = 0

// Skie

 OUTER_SET JOining_Skie = 1

ACTION_FOR_EACH bcs IN

// Original Skie ~%SKIE_BCS%~ // Class script ~BDSKIEC~ // ~BDSKIE~
// Original Skie // EET_END ~SKIE_~
// Original Skie // EET_ODD ~SKIE~

BEGIN

// BG1
OUTER_SPRINT "BG1_BANTER" "BSKIE"
OUTER_SPRINT "BG1_DREAM" "SKIED"
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDSKIEB"
	OUTER_SPRINT "SoD_DREAM" ""

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Skie_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

 OUTER_SET JOining_Skie = 0

// Tiax

 OUTER_SET JOining_Tiax = 1

ACTION_FOR_EACH bcs IN

// Original Tiax ~%TIAX_BCS%~ // Class script ~BDTIAXC~ // ~BDTIAX~

BEGIN

// BG1
OUTER_SPRINT "BG1_BANTER" "BTIAX"
OUTER_SPRINT "BG1_DREAM" "TIAXD"
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDTIAXB"
	OUTER_SPRINT "SoD_DREAM" ""

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Tiax_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

 OUTER_SET JOining_Tiax = 0

// Xan

 OUTER_SET JOining_Xan = 1

ACTION_FOR_EACH bcs IN

// Original Xan ~%XAN_BCS%~ // Class script ~BDXANC~ // ~ttxan~

BEGIN

// BG1
OUTER_SPRINT "BG1_BANTER" "BXANNN"
OUTER_SPRINT "BG1_DREAM" "XAND"
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDXANB"
	OUTER_SPRINT "SoD_DREAM" ""

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Xan_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

 OUTER_SET JOining_Xan = 0

// Xzar

 OUTER_SET JOining_Xzar = 1

ACTION_FOR_EACH bcs IN

// Original Xzar ~%XZAR_BCS%~ // Class script ~BDXZARC~

BEGIN

// BG1
OUTER_SPRINT "BG1_BANTER" "BXZAR"
OUTER_SPRINT "BG1_DREAM" "XZARD"
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDXZARB"
	OUTER_SPRINT "SoD_DREAM" ""

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Xzar_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

 OUTER_SET JOining_Xzar = 0

// Yeslick

 OUTER_SET JOining_Yeslick = 1

ACTION_FOR_EACH bcs IN

// Original Yeslick ~%YESLICK_BCS%~ // Class script ~BDYESLIC~

BEGIN

// BG1
OUTER_SPRINT "BG1_BANTER" "BYESLI"
OUTER_SPRINT "BG1_DREAM" "YESLID"
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDYESLIB"
	OUTER_SPRINT "SoD_DREAM" ""

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Yeslick_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

 OUTER_SET JOining_Yeslick = 0

// Baeloth

 OUTER_SET JOining_Baeloth = 1

ACTION_FOR_EACH bcs IN

// Original Baeloth ~BAELOTH~ ~BDBAELOT~ // Class script ~BDBAELOC~

BEGIN

// BG1
OUTER_SPRINT "BG1_BANTER" "BDBAELOB"
OUTER_SPRINT "BG1_DREAM" "BAELOTHD"
	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDBAELOB"
	OUTER_SPRINT "SoD_DREAM" "BDBAELOD"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Baeloth_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG1.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG1.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG1.tph~

	END
END

 OUTER_SET JOining_Baeloth = 0


//////////////////////////////////////////////////////
//////////////////////////////////////////////////////
//////////////////////////////////////////////////////

/////////////////////////// SoD ///////////////////////////

 OUTER_SET JOining_Voghiln = 0
 OUTER_SET JOining_Corwin = 0
 OUTER_SET JOining_Mkhiin = 0
 OUTER_SET JOining_Glint = 0

/////////////////////////// SoD ///////////////////////////

// Voghiln

 OUTER_SET JOining_Voghiln = 1

ACTION_FOR_EACH bcs IN

// Original Voghiln ~BDVOGHIL~

BEGIN

	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDVOGHIB"
	OUTER_SPRINT "SoD_DREAM" "BDVOGHID"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Voghiln_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_SoD.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_SoD.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_SoD.tph~

	END
END

 OUTER_SET JOining_Voghiln = 0

// Corwin

 OUTER_SET JOining_Corwin = 1

ACTION_FOR_EACH bcs IN

// Original Corwin ~BDCORWIN~

BEGIN

	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDCORWIB"
	OUTER_SPRINT "SoD_DREAM" "BDCORWID"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Corwin_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_SoD.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_SoD.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_SoD.tph~

	END
END

 OUTER_SET JOining_Corwin = 0

// Mkhiin

 OUTER_SET JOining_Mkhiin = 1

ACTION_FOR_EACH bcs IN

// Original Mkhiin ~BDMKHIIN~

BEGIN

	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDMKHIIB"
	OUTER_SPRINT "SoD_DREAM" "BDMKHIID"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Mkhiin_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_SoD.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_SoD.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_SoD.tph~

	END
END

 OUTER_SET JOining_Mkhiin = 0

// Glint

 OUTER_SET JOining_Glint = 1

ACTION_FOR_EACH bcs IN

// Original Glint ~BDGLINT~

BEGIN

	// SoD
	OUTER_SPRINT "SoD_BANTER" "BDGLINTB"
	OUTER_SPRINT "SoD_DREAM" "BDGLINTD"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Glint_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_SoD.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_SoD.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_SoD.tph~

	END
END

 OUTER_SET JOining_Glint = 0


//////////////////////////////////////////////////////
//////////////////////////////////////////////////////
//////////////////////////////////////////////////////

/////////////////////////// bg2 ///////////////////////////

 OUTER_SET JOining_Aerie = 0
 OUTER_SET JOining_Anomen = 0
 OUTER_SET JOining_Cernd = 0
 OUTER_SET JOining_Haerdalis = 0
 OUTER_SET JOining_Hexxat = 0
 OUTER_SET JOining_Jan = 0
 OUTER_SET JOining_Keldorn = 0
 OUTER_SET JOining_Korgan = 0
 OUTER_SET JOining_Mazzy = 0
 OUTER_SET JOining_Nalia = 0
 OUTER_SET JOining_Sarevok = 0
 OUTER_SET JOining_Valygar = 0
 OUTER_SET JOining_Wilson = 0
 OUTER_SET JOining_Yoshimo = 0

/////////////////////////// bg2 ///////////////////////////

// Aerie

 OUTER_SET JOining_Aerie = 1

ACTION_FOR_EACH bcs IN

// Original Aerie ~AERIE~ ~AERI25~

BEGIN 

		// BG2
		OUTER_SPRINT "BG2_BANTER" "BAERIE"
		OUTER_SPRINT "BG2_DREAM" "AERIED"
			// ToB
			OUTER_SPRINT "TOB_BANTER" "BAERIE25"
			OUTER_SPRINT "TOB_DREAM" "AERIE25D"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Aerie_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG2.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

 OUTER_SET JOining_Aerie = 0

// Anomen

 OUTER_SET JOining_Anomen = 1

ACTION_FOR_EACH bcs IN

// Original Anomen ~ANOMEN~ ~ANOM25~

BEGIN

		// BG2
		OUTER_SPRINT "BG2_BANTER" "BANOMEN"
		OUTER_SPRINT "BG2_DREAM" "ANOMEND"
			// ToB
			OUTER_SPRINT "TOB_BANTER" "BANOME25"
			OUTER_SPRINT "TOB_DREAM" "ANOME25D"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Anomen_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG2.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

 OUTER_SET JOining_Anomen = 0

// Cernd

 OUTER_SET JOining_Cernd = 1


ACTION_FOR_EACH bcs IN

// Original Cernd ~CERND~ ~CERN25~

BEGIN

		// BG2
		OUTER_SPRINT "BG2_BANTER" "BCERND"
		OUTER_SPRINT "BG2_DREAM" "CERNDD"
			// ToB
			OUTER_SPRINT "TOB_BANTER" "BCERND25"
			OUTER_SPRINT "TOB_DREAM" "CERNDD"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Cernd_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG2.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

 OUTER_SET JOining_Cernd = 0

// Haerdalis

 OUTER_SET JOining_Haerdalis  = 1

ACTION_FOR_EACH bcs IN

// Original Haerdalis ~HAERDALI~ ~HAER25~

BEGIN

		// BG2
		OUTER_SPRINT "BG2_BANTER" "BHAERDA"
		OUTER_SPRINT "BG2_DREAM" "HAERDAD"
			// ToB
			OUTER_SPRINT "TOB_BANTER" "BHAERD25"
			OUTER_SPRINT "TOB_DREAM" "HAERDAD"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Haerdalis_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG2.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

 OUTER_SET JOining_Haerdalis = 0

// Hexxat

 OUTER_SET JOining_Hexxat  = 1

ACTION_FOR_EACH bcs IN

// Original Hexxat ~HEXXAT~ ~HEXXA25~

BEGIN

		// BG2
		OUTER_SPRINT "BG2_BANTER" "BHEXXAT"
		OUTER_SPRINT "BG2_DREAM" "HEXXATD"
			// ToB
			OUTER_SPRINT "TOB_BANTER" "BHEXXA25"
			OUTER_SPRINT "TOB_DREAM" "HEXXA25D"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Hexxat_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG2.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

 OUTER_SET JOining_Hexxat = 0

// Jan

 OUTER_SET JOining_Jan  = 1

ACTION_FOR_EACH bcs IN

// Original Jan ~JAN~ ~JAN25~

BEGIN

		// BG2
		OUTER_SPRINT "BG2_BANTER" "BJAN"
		OUTER_SPRINT "BG2_DREAM" "JAND"
			// ToB
			OUTER_SPRINT "TOB_BANTER" "BJAN25"
			OUTER_SPRINT "TOB_DREAM" "JAND"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Jan_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG2.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

 OUTER_SET JOining_Jan = 0

// Keldorn

 OUTER_SET JOining_Keldorn  = 1

ACTION_FOR_EACH bcs IN

// Original Keldorn ~KELDORN~ ~KELD25~

BEGIN

		// BG2
		OUTER_SPRINT "BG2_BANTER" "BKELDOR"
		OUTER_SPRINT "BG2_DREAM" "KELDORD"
			// ToB
			OUTER_SPRINT "TOB_BANTER" "BKELDO25"
			OUTER_SPRINT "TOB_DREAM" "KELDORD"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Keldorn_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG2.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

 OUTER_SET JOining_Keldorn = 0

// Korgan

 OUTER_SET JOining_Korgan  = 1

ACTION_FOR_EACH bcs IN

// Original Korgan ~KORGAN~ ~KORG25~

BEGIN

		// BG2
		OUTER_SPRINT "BG2_BANTER" "BKORGAN"
		OUTER_SPRINT "BG2_DREAM" "KORGAND"
			// ToB
			OUTER_SPRINT "TOB_BANTER" "BKORGA25"
			OUTER_SPRINT "TOB_DREAM" "KORGAND"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Korgan_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG2.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

 OUTER_SET JOining_Korgan = 0

// Mazzy

 OUTER_SET JOining_Mazzy  = 1

ACTION_FOR_EACH bcs IN

// Original Mazzy ~MAZZY~ ~MAZZ25~

BEGIN

		// BG2
		OUTER_SPRINT "BG2_BANTER" "BMAZZY"
		OUTER_SPRINT "BG2_DREAM" "MAZZYD"
			// ToB
			OUTER_SPRINT "TOB_BANTER" "BMAZZY25"
			OUTER_SPRINT "TOB_DREAM" "MAZZYD"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Mazzy_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG2.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

 OUTER_SET JOining_Mazzy = 0

// Nalia

 OUTER_SET JOining_Nalia  = 1

ACTION_FOR_EACH bcs IN

// Original Nalia ~NALIA~ ~NALI25~

BEGIN

		// BG2
		OUTER_SPRINT "BG2_BANTER" "BNALIA"
		OUTER_SPRINT "BG2_DREAM" "NALIAD"
			// ToB
			OUTER_SPRINT "TOB_BANTER" "BNALIA25"
			OUTER_SPRINT "TOB_DREAM" "NALIAD"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Nalia_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG2.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

 OUTER_SET JOining_Nalia = 0

// Sarevok

 OUTER_SET JOining_Sarevok  = 1

ACTION_FOR_EACH bcs IN

// Original Sarevok ~SAREV25~

BEGIN
		// BG2
		OUTER_SPRINT "BG2_BANTER" ""
		OUTER_SPRINT "BG2_DREAM" ""
			// ToB
			OUTER_SPRINT "TOB_BANTER" "BSAREV25"
			OUTER_SPRINT "TOB_DREAM" "SAREV25D"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Sarevok_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG2.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

 OUTER_SET JOining_Sarevok = 0

// Valygar

 OUTER_SET JOining_Valygar  = 1

ACTION_FOR_EACH bcs IN

// Original Valygar ~VALYGAR~ ~VALY25~

BEGIN

		// BG2
		OUTER_SPRINT "BG2_BANTER" "BVALYGA"
		OUTER_SPRINT "BG2_DREAM" "VALYGARD"
			// ToB
			OUTER_SPRINT "TOB_BANTER" "BVALYG25"
			OUTER_SPRINT "TOB_DREAM" "VALYGARD"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Valygar_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG2.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

 OUTER_SET JOining_Valygar = 0

// Wilson

 OUTER_SET JOining_Wilson  = 1

ACTION_FOR_EACH bcs IN

// Original Wilson ~WILSON~

BEGIN

		// BG2
		OUTER_SPRINT "BG2_BANTER" "BWILSON"
		OUTER_SPRINT "BG2_DREAM" "WILSOND"
			// ToB
			OUTER_SPRINT "TOB_BANTER" "BWILSO25"
			OUTER_SPRINT "TOB_DREAM" "WILSOND"

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Wilson_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG2.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

 OUTER_SET JOining_Wilson = 0

// Yoshimo

 OUTER_SET JOining_Yoshimo  = 1

ACTION_FOR_EACH bcs IN

// Original Yoshimo ~YOSHIMO~ ~YOSH25~

BEGIN

		// BG2
		OUTER_SPRINT "BG2_BANTER" "BYOSHIM"
		OUTER_SPRINT "BG2_DREAM" "YOSHD"
			// ToB
			OUTER_SPRINT "TOB_BANTER" ""
			OUTER_SPRINT "TOB_DREAM" ""

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Yoshimo_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Original_BG2.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_BG2.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_BG2.tph~

	END
END

 OUTER_SET JOining_Yoshimo = 0


//////////////////////////////////////////////////////
//////////////////////////////////////////////////////
//////////////////////////////////////////////////////

/////////////////////////// Continuous ///////////////////////////

// Next_Traveler Continuous

