/////////////////////////// Continuous ///////////////////////////

/////////////// Reset

// BG1
OUTER_SPRINT "BG1_JOINED" ""
OUTER_SPRINT "BG1_BCS" ""
OUTER_SPRINT "BG1_BANTER" ""
OUTER_SPRINT "BG1_DREAM" ""
	// SoD
	OUTER_SPRINT "SoD_JOINED" ""
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""
		// BG2
		OUTER_SPRINT "BG2_JOINED" ""
		OUTER_SPRINT "BG2_BCS" ""
		OUTER_SPRINT "BG2_BANTER" ""
		OUTER_SPRINT "BG2_DREAM" ""
			// ToB
			OUTER_SPRINT "TOB_JOINED" ""
			OUTER_SPRINT "TOB_BCS" ""
			OUTER_SPRINT "TOB_BANTER" ""
			OUTER_SPRINT "TOB_DREAM" ""

/////////////////////////// Nikita ///////////////////////////

// BG1
OUTER_SPRINT "BG1_JOINED" "CMTNIKJ"
OUTER_SPRINT "BG1_BCS" "cmtnikit"
OUTER_SPRINT "BG1_BANTER" "BCMTNIK"
OUTER_SPRINT "BG1_DREAM" "CMTNIKD"
	// SoD
	OUTER_SPRINT "SoD_JOINED" ""
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""
		// BG2
		OUTER_SPRINT "BG2_JOINED" "CMNIKITJ"
		OUTER_SPRINT "BG2_BCS" "cmnikita"
		OUTER_SPRINT "BG2_BANTER" "BCMNIKIT"
		OUTER_SPRINT "BG2_DREAM" "CMNIKITD"
			// ToB
			OUTER_SPRINT "TOB_JOINED" "CMNIK25J"
			OUTER_SPRINT "TOB_BCS" "CMNIK25"
			OUTER_SPRINT "TOB_BANTER" "BCMNIK25"
			OUTER_SPRINT "TOB_DREAM" "CMNIK25D"

ACTION_FOR_EACH bcs IN

// EET Nikita ~cmtnikit~ ~cmnikita~ ~CMNIK25~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/cmnikita_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Continuous.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_Continuous.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_Continuous.tph~

	END
END

/////////////////////////// Alora_Continuous ///////////////////////////

// BG1
OUTER_SPRINT "BG1_JOINED" "%ALORA_JOINED%"
OUTER_SPRINT "BG1_BCS" "%ALORA_BCS%"
OUTER_SPRINT "BG1_BANTER" "BALORA"
OUTER_SPRINT "BG1_DREAM" "ALORAD"
	// SoD
	OUTER_SPRINT "SoD_JOINED" "BDALORAJ"
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" "BDALORAB"
	OUTER_SPRINT "SoD_DREAM" ""
		// BG2
		OUTER_SPRINT "BG2_JOINED" "CMALORAJ"
		OUTER_SPRINT "BG2_BCS" "cmalora"
		OUTER_SPRINT "BG2_BANTER" "BCMALOR"
		OUTER_SPRINT "BG2_DREAM" "CMALORAD"
			// ToB
			OUTER_SPRINT "TOB_JOINED" "CMALO25J"
			OUTER_SPRINT "TOB_BCS" "cmalo25"
			OUTER_SPRINT "TOB_BANTER" "BCMALO25"
			OUTER_SPRINT "TOB_DREAM" "CMALO25D"

ACTION_FOR_EACH bcs IN

// EET Alora_Continuous ~%ALORA_BCS%~ ~cmalora~ ~cmalo25~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Alora_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Continuous.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_Continuous.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_Continuous.tph~

	END
END

/////////////////////////// Ajantis_Continuous ///////////////////////////

// BG1
OUTER_SPRINT "BG1_JOINED" "%AJANTIS_JOINED%"
OUTER_SPRINT "BG1_BCS" "%AJANTIS_BCS%"
OUTER_SPRINT "BG1_BANTER" "BAJANT"
OUTER_SPRINT "BG1_DREAM" "AJANTD"
	// SoD
	OUTER_SPRINT "SoD_JOINED" "BDAJANTJ"
	OUTER_SPRINT "SoD_BCS" "BDAJANTI"
	OUTER_SPRINT "SoD_BANTER" "BDAJANTB"
	OUTER_SPRINT "SoD_DREAM" "AJANTD"
		// BG2
		OUTER_SPRINT "BG2_JOINED" "C#AjanJ"
		OUTER_SPRINT "BG2_BCS" "C#Ajan"
		OUTER_SPRINT "BG2_BANTER" "C#AjanB"
		OUTER_SPRINT "BG2_DREAM" "C#AjanD"
			// ToB
			OUTER_SPRINT "TOB_JOINED" "C#Aja25J"
			OUTER_SPRINT "TOB_BCS" "C#Ajan25"
			OUTER_SPRINT "TOB_BANTER" "C#Aja25B"
			OUTER_SPRINT "TOB_DREAM" "C#Aja25D"

ACTION_FOR_EACH bcs IN

// EET Ajantis_Continuous ~%AJANTIS_BCS%~ ~BDAJANTI~ ~C#Ajan~ ~C#Ajan25~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Ajantis_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Continuous.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_Continuous.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_Continuous.tph~

	END
END

/////////////////////////// Kivan_Continuous ///////////////////////////

// BG1
OUTER_SPRINT "BG1_JOINED" "%KIVAN_JOINED%"
OUTER_SPRINT "BG1_BCS" "%KIVAN_BCS%"
OUTER_SPRINT "BG1_BANTER" "BKIVAN"
OUTER_SPRINT "BG1_DREAM" "KIVAND"
	// SoD
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_JOINED" "BDKIVANJ"
	OUTER_SPRINT "SoD_BANTER" "BDKIVANB"
	OUTER_SPRINT "SoD_DREAM" ""
		// BG2
		OUTER_SPRINT "BG2_JOINED" "P#KIVJ"
		OUTER_SPRINT "BG2_BCS" "P#KIV01"
		OUTER_SPRINT "BG2_BANTER" "BP#KIV"
		OUTER_SPRINT "BG2_DREAM" "P#KIVD"
			// ToB
			OUTER_SPRINT "TOB_DREAM" "P#KI25D"
			OUTER_SPRINT "TOB_JOINED" "P#KI25J"
			OUTER_SPRINT "TOB_BANTER" "BP#KIV25"
			OUTER_SPRINT "TOB_BCS" "P#KI25"

ACTION_FOR_EACH bcs IN

// EET Kivan_Continuous ~%KIVAN_BCS%~ ~P#KIV01~ ~P#KI25~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Kivan_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Continuous.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_Continuous.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_Continuous.tph~

	END
END

// Continuous_Walahnan

// BG1
OUTER_SPRINT "BG1_JOINED" "L#WALAHJ"
OUTER_SPRINT "BG1_BCS" "L#WALAH"
OUTER_SPRINT "BG1_BANTER" "L#WALAHB"
OUTER_SPRINT "BG1_DREAM" "L#WALAHD"
	// SoD
	OUTER_SPRINT "SoD_JOINED" "L#SWALAJ"
	OUTER_SPRINT "SoD_BCS" "L#SWALAH"
	OUTER_SPRINT "SoD_BANTER" "L#SWALAD"
	OUTER_SPRINT "SoD_DREAM" "L#SWALAD"
		// BG2
		OUTER_SPRINT "BG2_JOINED" "L#2WHJ"
		OUTER_SPRINT "BG2_BCS" "L#2WH"
		OUTER_SPRINT "BG2_BANTER" "L#2WHB"
		OUTER_SPRINT "BG2_DREAM" "L#2WHD"
			// ToB
			OUTER_SPRINT "TOB_JOINED" "L#2WH25J"
			OUTER_SPRINT "TOB_BCS" "L#2WH25"
			OUTER_SPRINT "TOB_BANTER" "L#2WH25B"
			OUTER_SPRINT "TOB_DREAM" "L#2WH25D"

ACTION_FOR_EACH bcs IN

// EET Walahnan_Continuous ~L#WALAH~ ~L#SWALAH~ ~L#2WH~ ~L#2WH25~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/L#WALAH_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Continuous.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_Continuous.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_Continuous.tph~

	END
END

// Continuous_Coran

// BG1
OUTER_SPRINT "BG1_JOINED" "%CORAN_JOINED%"
OUTER_SPRINT "BG1_BCS" "%CORAN_BCS%"
OUTER_SPRINT "BG1_BANTER" "BCORAN"
OUTER_SPRINT "BG1_DREAM" "CORAND"
	// SoD
	OUTER_SPRINT "SoD_JOINED" "%CORAN_JOINED%"
	OUTER_SPRINT "SoD_BCS" "%CORAN_BCS%"
	OUTER_SPRINT "SoD_BANTER" "BCORAN"
	OUTER_SPRINT "SoD_DREAM" "CORAND"
		// BG2
		OUTER_SPRINT "BG2_JOINED" "O#CoranJ"
		OUTER_SPRINT "BG2_BCS" "O#CORANS"
		OUTER_SPRINT "BG2_BANTER" "BO#Coran"
		OUTER_SPRINT "BG2_DREAM" "O#CoranD"
			// ToB
			OUTER_SPRINT "TOB_JOINED" "O#Cor25J"
			OUTER_SPRINT "TOB_BCS" "O#COR25S"
			OUTER_SPRINT "TOB_BANTER" "BO#Cor25"
			OUTER_SPRINT "TOB_DREAM" "O#Cor25D"

ACTION_FOR_EACH bcs IN

// EET Coran_Continuous ~%CORAN_BCS%~ ~O#CORANS~ ~O#COR25S~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Coran_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Continuous.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_Continuous.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_Continuous.tph~

	END
END

// Continuous_Yeslick
// BG1
OUTER_SPRINT "BG1_JOINED" "%YESLICK_JOINED%"
OUTER_SPRINT "BG1_BCS" "%YESLICK_BCS%"
OUTER_SPRINT "BG1_BANTER" "BYESLI"
OUTER_SPRINT "BG1_DREAM" "YESLID"
	// SoD
	OUTER_SPRINT "SoD_JOINED" "BDYESLIJ"
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""
		// BG2
		OUTER_SPRINT "BG2_JOINED" "LK#YESJ"
		OUTER_SPRINT "BG2_BCS" "LK#YES"
		OUTER_SPRINT "BG2_BANTER" "BLK#YES"
		OUTER_SPRINT "BG2_DREAM" "LK#YESD"
			// ToB
			OUTER_SPRINT "TOB_JOINED" "LK#YE25J"
			OUTER_SPRINT "TOB_BCS" "LK#YES25"
			OUTER_SPRINT "TOB_BANTER" "BLK#YE25"
			OUTER_SPRINT "TOB_DREAM" "LK#YE25D"

ACTION_FOR_EACH bcs IN

// EET Yeslick_Continuous ~%YESLICK_BCS%~ ~~ ~LK#YES~ ~LK#YES25~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Yeslick_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Continuous.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_Continuous.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_Continuous.tph~

	END
END

// Continuous_Xan
// BG1
OUTER_SPRINT "BG1_JOINED" "%XAN_JOINED%"
OUTER_SPRINT "BG1_BCS" "%XAN_BCS%"
OUTER_SPRINT "BG1_BANTER" "BXANNN"
OUTER_SPRINT "BG1_DREAM" "XAND"
	// SoD
	OUTER_SPRINT "SoD_JOINED" "BDXANJ"
	OUTER_SPRINT "SoD_BCS" ""
	OUTER_SPRINT "SoD_BANTER" ""
	OUTER_SPRINT "SoD_DREAM" ""
		// BG2
		OUTER_SPRINT "BG2_JOINED" "O#XANJ"
		OUTER_SPRINT "BG2_BCS" "O#XanS"
		OUTER_SPRINT "BG2_BANTER" "BO#XAN"
		OUTER_SPRINT "BG2_DREAM" "O#XAND"
			// ToB
			OUTER_SPRINT "TOB_JOINED" "O#XAN25J"
			OUTER_SPRINT "TOB_BCS" "O#Xan25S"
			OUTER_SPRINT "TOB_BANTER" "BO#XAN25"
			OUTER_SPRINT "TOB_DREAM" "O#XAN25D"

ACTION_FOR_EACH bcs IN

// EET Xan_Continuous ~%XAN_BCS%~ ~O#XanS~ ~O#Xan25S~

BEGIN

	ACTION_IF FILE_EXISTS_IN_GAME ~%bcs%.bcs~ BEGIN

		INCLUDE ~JOining_Party_Select/Campaign_Transition/DestroySelf.tph~

				EXTEND_TOP ~%bcs%.bcs~ ~JOining_Party_Select/Baf/All_TRAVELER_JOIN.baf~ EVALUATE_BUFFER

		EXTEND_BOTTOM ~%bcs%.bcs~ ~weidu_external/JOining_Party_Select/All_In/Xan_All_In.baf~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN_Continuous.tpa~

		EXTEND_BOTTOM ~%bcs%.bcs~ ~JOining_Party_Select/Baf/JO_JOIN/JO_JOIN.BAF~ EVALUATE_BUFFER

		INCLUDE ~JOining_Party_Select/Baf/Banter/Banter_Continuous.tph~

		INCLUDE ~JOining_Party_Select/Baf/Dream/Dream_Continuous.tph~

	END
END

// Next_Traveler Continuous

