
///////////////////////////////////////////////////////////////////////////////////////////////////////////

ACTION_FOR_EACH Death_var IN

// Original Imoen                ~%IMOEN_DV%~ // ImoenIren // ~Imoen~ // ~ttimoen~     // Imoen
// Original Edwin                ~Edwin~                                            // Edwin
// Original Jaheira              ~Jaheira~                         // ~ttjaheir~    // Jaheira
// Original Minsc                ~Minsc~                           // ~ttminsc~     // Minsc
// Original Viconia              ~Viconia~                                          // Viconia
// Original Dorn                 ~Dorn~                                             // Dorn
// Original Neera                ~Neera~                                            // Neera
// Original Rasaad               ~Rasaad~                                           // Rasaad


/////////////////////////// BG1 ///////////////////////////

// Original Ajantis              ~Ajantis~                                          // Ajantis
// Original Alora                ~Alora~                                            // Alora
// Original Branwen              ~Branwen~                         // ~ttbran~      // Branwen
// Original Coran                ~Coran~                                            // Coran
// Original Dynaheir             ~Dynaheir~                                         // Dynaheir

// Original Eldoth               ~Eldoth~                                           // Eldoth
// Original Faldorn              ~Faldorn~                                          // Faldorn
// Original Garrick              ~Garrick~                                          // Garrick

// Original Kagain               ~Kagain~                                           // Kagain
// Original Khalid               ~Khalid~                                           // Khalid
// Original Kivan                ~Kivan~                                            // Kivan

// Original Montaron             ~Montaron~                                         // Montaron
// Original Quayle               ~Quayle~                                           // Quayle
// Original Safana               ~Safana~                                           // Safana
// Original Sharteel             ~Sharteel~                        // ~Shar-teel~   // Sharteel
// Original Skie                 ~Skie~                                             // Skie
// Original Tiax                 ~Tiax~                                             // Tiax

// Original Xan                  ~Xan~                             // ttxan~        // Xan
// Original Xzar                 ~Xzar~                                             // Xzar
// Original Yeslick              ~Yeslick~                                          // Yeslick

// Original Baeloth              ~Baeloth~                                          // Baeloth


/////////////////////////// SoD ///////////////////////////

// Original Voghiln              ~Voghiln~                                          // Voghiln
// Original Corwin               ~Corwin~                                           // Corwin
// Original Mkhiin               ~Mkhiin~                                           // Mkhiin
// Original Glint                ~Glint~                                            // Glint


/////////////////////////// BG2 ///////////////////////////

// Original Aerie                ~Aerie~                                            // Aerie
// Original Anomen               ~Anomen~                                           // Anomen
// Original Cernd                ~Cernd~                                            // Cernd
// Original Haerdalis            ~Haerdalis~                                        // Haerdalis
// Original Hexxat               ~Hexxat~                                           // Hexxat
// Original Jan                  ~Jan~                                              // Jan
// Original Keldorn              ~Keldorn~                                          // Keldorn
// Original Korgan               ~Korgan~                                           // Korgan
// Original Mazzy                ~Mazzy~                                            // Mazzy
// Original Nalia                ~Nalia~                                            // Nalia
// Original Sarevok              ~Sarevok~                                          // Sarevok
// Original Valygar              ~Valygar~                                          // Valygar
// Original Wilson               ~Wilson~                                           // Wilson
// Original Yoshimo              ~Yoshimo~                                          // Yoshimo


/////////////////////////// Mods BG1 ///////////////////////////

// Ishlilka_The-Wizard-Slayer
// Mod Ishlilka                  ~#Ishy~                                            // Ishlilka

// ChaosKnight-kit
// Mod Jacob                     ~ZYJCOB~                                           // Jacob

// Askaria-Quest
// Mod Askaria                   ~ZYASKA~                                           // Askaria

// Isra BG1
// Mod Isra_BG1                  ~rh#isra~                                          // Isra

// Finch
// Mod Finch                     ~SUFINCH~                                          // Finch

// Drizzt Saga
// Mod Jarlaxle_Saga             ~F_JARLAXE~                                        // Jarlaxle
// Mod Artemis_Enteri_Saga       ~F_ARTEMIS~                                        // Artemis Enteri
// Mod Catti-Brie_Saga           ~F_CATTIBR~                                        // Catti-Brie
// Mod Bruenor_Saga              ~F_BRUENOR~                                        // Bruenor
// Mod Regis_Saga                ~F_REGIS2~                                          // Regis
// Mod Drizzt_Saga               ~F_DRIZZT~                                         // Drizzt
// Mod Wulfgar_Saga              ~F_WULFGAR~                                        // Wulfgar

// Dark Horizons                                                                         
// Mod Thorin                    ~CMTTHOR~                                          // Thorin
// Mod Morwen                     ~CMTMORW~                                         // Morwen

// DSotSC                             
// Mod Bardo                     ~DSBARDO~                                          // Bardo
// Mod Bub_Snikt                 ~DSBUB~                                            // Bub Snikt
// Mod Conchobhair               ~Conchobhair~                                      // Conchobhair
// Mod CuChoinneach              ~CuChoinneach~                                     // CuChoinneach
// Mod Ferthgil_Trollslayer      ~Ferthgil~                                         // Ferthgil Trollslayer
// Mod Jet'laya                  ~JETLAYA~                                          // Jet'laya
// Mod Keiria_Silverstring       ~KEIRIA~                                           // Keiria Silverstring
// Mod Skeezer_Lumpkin_VI        ~SKEEZER~                                          // Skeezer Lumpkin VI
// Mod Thorfinn_Hauskluniff      ~Thorfinn~                                         // Thorfinn Hauskluniff

// NTotSC                                                                           
// Mod Will_Scarlet              ~WILL~                                             // Will Scarlet

// Valerie                            
// Mod Valerie                   ~T2VAL~

// Indira                             
// Mod Indira                    ~J#Indi~

// Bristlelick BG1 / SoD              
// Mod Bristlelick               ~L#BRIST~

// Glam's npc pack                    
// Mod Dave                      ~GV#DAVE~
// Mod Flara                     ~GV#FLAR~
// Mod Littlun                   ~GV#LITT~
// Mod Moidre                    ~GV#MOID~
// Mod Vynd                      ~GV#VYND~

// Kale BG1
// Mod Kale_BG1                  ~X3Kale~

// New Tales of the Sword Coast
// Mod Kasandra                  ~Kasandra~
// Mod Masambe                   ~Masambe~
// Mod Alethra                   ~Alethra~
// Mod Rimardo                   ~Rimardo~
// Mod Talindra                  ~Talindra~
// Mod Theodor                   ~Theodor~
// Mod Ariadne                   ~Ariadne~
// Mod Nathan                    ~Nathan~
// Mod Namiir                    ~Namiir~
// Mod Miranda                   ~Miranda~

// Walahnan BG1 / SoD
// Mod Walahnan_BG1                  ~L#WALAH~

// Aerie in BG:EE
// Mod Aerie_BG1                 ~B2#Aeri~

// Margarita Zelleod
// Mod Margarita                 ~RL#MARG~

// Next_Traveler BG1


/////////////////////////// Mods BG2 ///////////////////////////

// Alora BG2
// Mod Alora BG2                 ~CMALORA~                                          // Alora

// Yeslick BG2                                                                           
// Mod Yeslick BG2               ~LK#YESLK~                                         // Yeslick

// The Undying                                                                           
// Mod Undying                   ~cmninaf~                                          // Ninafer
// Mod Undying                   ~callisto~                                         // Callisto

// Summon Bhaalspawn                                                                     
// Mod Sandra                    ~BHAALSPW~                                         // Sandra

// VampireTales                                                                          
// Mod Miriam                    ~cmgmiriam~                                        // Miriam

// Kim                                                                                   
// Mod Kim                       ~Kim~                                              // Kim

// Severian                                                                              
// Mod Severian                  ~#Severian~                                        // Severian

// Frennedan                                                                             
// Mod Frennedan                 ~Frennedan~                                        // Frennedan

// Branwen BG2                                                                           
// Mod Branwen_BG2               ~O#Bran~                                           // Branwen
// Tiax BG2                                                                              
// Mod Tiax_BG2                  ~O#Tiax~                                           // Tiax
// Xan BG2                                                                               
// Mod Xan_BG2                   ~O#XAN~                                            // Xan
// Coran BG2                                                                             
// Mod Coran_BG2                 ~O#Coran~                                          // Coran
								      
// Auren Aseph                        
// Mod Auren                     ~K#AUREN~                                  // Auren

// Isra BG2                                                                      
// Mod Isra_BG2                  ~rh#Isra2~                                 // Isra

// Nephele                                                                       
// Mod Nephele_Samios            ~Nephele~                                  // Nephele

// Sheena                                                                        
// Mod Sheena                    ~K#SHEENA~                                 // Sheena

// Kiara / Zaiya                                                                 
// Mod Kiara                     ~Kiara~                                    // Kiara
// Mod Zaiya                     ~Zaiya~                                    // Zaiya

// The Beaurin Legacy                                                            
// Mod Minyae                    ~QI#MI~                                    // Minyae
// Mod Elaryn                    ~QI#ELA~                                   // Elaryn

// Tyris Flare                                                                   
// Mod Tyris                     ~g#Tyris~                                  // Tyris

// Region of Terror
// Mod Wulfgar_Terror            ~Wulfg2~                                   // Wulfgar
// Mod Regis_Terror              ~Reg2~                                     // Regis
// Mod Drizzt_Terror             ~Driz2~                                    // Drizz
// Mod Bruenor_Terror            ~Brue2~                                    // Bruenor
// Mod Catti-Brie_Terror         ~Catt2~                                    // Catti-Brie
// Mod Artemis_Entreri_Terror    ~Enter2~                                   // Artemis
// Mod Jarlaxle_Terror           ~Jarlax2~                                  // Jarlaxle
// Mod Tapio_Perkiomaki_Terror   ~Tapio~                                    // Tapio
// Mod Randall_Terror            ~Randall~                                  // Randall
// Mod Alissa_Terror             ~ALISSA1~                                  // Alissa
// Mod Mordragon_Terror          ~Mordrg~                                   // Mordragon

//Shadow over Soubar
// Mod Selence_Hillstar_Soubar   ~SELENCE~                                  // Selence
// Mod Charlotte_Soubar          ~CHARLOTT~                                 // Charlotte
// Mod Bolivar_Soubar            ~BOLIVAR~                                  // Bolivar
// Mod Tomas_Tomalson_Soubar     ~TOMASTM~                                  // Tomas

// ajantisbg2
// Mod Ajantis_BG2               ~C#Ajantis~                                // Ajantis

// Kivan and Deheriana
// Mod Kivan_BG2                 ~P#KIVAN~                                  // Kivan
// Mod Deheriana                 ~P#DEHER~                                  // Deheriana

// Yvette
// Mod Yvette                    ~YxYve~

// The Luxley Family
// Mod Sebastian                ~fhlseb~
// Mod Andrei                   ~FHLAND~

//  Beyond the Law
// Mod Kiyone                   ~Kiyone~
// Mod Kova                     ~Kova~

// Petsy
// Mod Petsy                   ~L3PETSY~

// Kale BG2
// Mod Kale_BG2                ~X3Kal~

// Walahnan BG2
// Mod Walahnan_BG2            ~L#2WALAH~

// Autumns Twilight
// Mod Dusk                    ~P_Dusk~
// Mod Fall                    ~P_Fall~
// Mod Cho'Nuja                ~P_Chon~
// Mod Alendir                 ~P_Alen~

// Lysre, dragonne de poche
// Mod Lysre                   ~CKLysre~

// Tashia
// Mod Tashia                  ~TASHIA~

// Dace Linton
// Mod Dace                    ~T#DACE~

// Next_Traveler BG2


/////////////////////////// Mods Continuous ///////////////////////////

// EET Nikita                  ~cmnikita~                                   // Nikita

// EET Alora_Continuous        ~Alora~                                     // Alora_Continuous

// EET Ajantis_Continuous      ~Ajantis~                                   // Ajantis_Continuous

// EET Kivan_Continuous        ~Kivan~                                     // Kivan_Continuous

// EET Walahnan_Continuous     ~L#WALAH~                                   // Walahnan_Continuous

// EET Coran_Continuous        ~Coran~                                     // Coran_Continuous

// EET Yeslick_Continuous      ~Yeslick~                                   // Yeslick_Continuous

// EET Xan_Continuous          ~Xan~                                       // Xan_Continuous

// EET Branwen_Continuous      ~Branwen~                                   // Branwen_Continuous

// EET Tiax_Continuous         ~Tiax~                                      // Tiax_Continuous

// EET Isra_Continuous         ~rh#isra~                                   // Isra_Continuous

// Ascalon's Breagar
// Mod Breagar                 ~ACBRE~                                     // Breagar_Continuous

// EET Sharteel_Continuous     ~Sharteel~                            // Sharteel_Continuous

// Next_Traveler Continuous

BEGIN

///////////////////////////////////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////////////////////////////////

	COPY ~weidu_external/JOining_Party_Select/JOining_Party_Select_Base_BCS.tph~ ~weidu_external/JOining_Party_Select/JOining_Party_Select_Base_BCS.tph~
			REPLACE_TEXTUALLY CASE_SENSITIVE EXACT_MATCH ~Replace_Death_in_NOT_AllowDead~ ~~~~~Replace_Death_in_NOT_AllowDead

			SPRINT textToReplace ~\(^[%%TAB%% ]*!InPartyAllowDead("%Death_var%")\)~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~TriggerOverride("%Death_var%",Global("JO_Myself_AllowDead","LOCALS",0))~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SF_workaround% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %Death_var% : !InPartyAllowDead found in %SF_workaround%
				~
			END~~~~~
			REPLACE_TEXTUALLY CASE_SENSITIVE EXACT_MATCH ~Replace_Death_in_AllowDead~ ~~~~~Replace_Death_in_AllowDead

			SPRINT textToReplace ~\(^[%%TAB%% ]*InPartyAllowDead("%Death_var%")\)~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~!TriggerOverride("%Death_var%",Global("JO_Myself_AllowDead","LOCALS",0))~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SF_workaround% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %Death_var% : InPartyAllowDead found in %SF_workaround%
				~
			END~~~~~
			REPLACE_TEXTUALLY CASE_SENSITIVE EXACT_MATCH ~Replace_Death_in_NOT_InParty~ ~~~~~Replace_Death_in_NOT_InParty

			SPRINT textToReplace ~\(^[%%TAB%% ]*!InParty("%Death_var%")\)~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~TriggerOverride("%Death_var%",Global("JO_Myself_InParty","LOCALS",0))~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SF_workaround% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %Death_var% : !InParty found in %SF_workaround%
				~
			END~~~~~
			REPLACE_TEXTUALLY CASE_SENSITIVE EXACT_MATCH ~Replace_Death_in_InParty~ ~~~~~Replace_Death_in_InParty

			SPRINT textToReplace ~\(^[%%TAB%% ]*InParty("%Death_var%")\)~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~!TriggerOverride("%Death_var%",Global("JO_Myself_InParty","LOCALS",0))~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SF_workaround% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %Death_var% : InParty found in %SF_workaround%
				~
			END~~~~~
			REPLACE_TEXTUALLY CASE_SENSITIVE EXACT_MATCH ~Replace_Death_in_NOT_Valid~ ~~~~~Replace_Death_in_NOT_Valid

			SPRINT textToReplace ~!I[s|f]ValidForPartyDialog\(ue\)?("%Death_var%")~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~TriggerOverride("%Death_var%",Global("JO_Myself_Valid","LOCALS",0))~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SF_workaround% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %Death_var% : !(...)ValidForParty(...) found in %SF_workaround%
				~
			END~~~~~
			REPLACE_TEXTUALLY CASE_SENSITIVE EXACT_MATCH ~Replace_Death_in_Valid~ ~~~~~Replace_Death_in_Valid

			SPRINT textToReplace ~I[s|f]ValidForPartyDialog\(ue\)?("%Death_var%")~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~!TriggerOverride("%Death_var%",Global("JO_Myself_Valid","LOCALS",0))~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SF_workaround% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %Death_var% : (...)ValidForParty(...) found in %SF_workaround%
				~
			END~~~~~
//////// Activate ///////////
			REPLACE_TEXTUALLY CASE_SENSITIVE EXACT_MATCH ~Replace_Death_in_StartDialog_1~ ~~~~~Replace_Death_in_StartDialog_1

			SPRINT textToReplace ~^[%%TAB%% ]*ActionOverride("%Death_var%",StartDialog\(ue\)?("\([^)]*\)",\([^)]*\)))~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~Activate("%Death_var%")
	%slashzero%~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SF_workaround% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // ActionOverride(%Death_var%) StartDialog() found in %SF_workaround%
				~
			END
			SPRINT textToReplace ~^[%%TAB%% ]*ActionOverride("%Death_var%",StartDialog\([^)]*\)NoSet\([^)]*\)(\([^)]*\)))~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~Activate("%Death_var%")
	%slashzero%~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SF_workaround% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // ActionOverride(%Death_var%) StartDialog() found in %SF_workaround%
				~
			END
			SPRINT textToReplace ~^[%%TAB%% ]*ActionOverride(\([^)]*\),StartDialog\(ue\)?("\([^)]*\)","%Death_var%"))~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~Activate("%Death_var%")
	%slashzero%~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SF_workaround% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // ActionOverride() StartDialog(%Death_var%) found in %SF_workaround%
				~
			END
			SPRINT textToReplace ~^[%%TAB%% ]*ActionOverride(\([^)]*\),StartDialog\([^)]*\)NoSet\([^)]*\)("%Death_var%"))~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~Activate("%Death_var%")
	%slashzero%~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SF_workaround% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // ActionOverride() StartDialog(%Death_var%) found in %SF_workaround%
				~
			END~~~~~
//
			REPLACE_TEXTUALLY CASE_SENSITIVE EXACT_MATCH ~Replace_Death_in_Dialog_2~ ~~~~~Replace_Death_in_Dialog_2

			SPRINT textToReplace ~^[%%TAB%% ]*ActionOverride("%Death_var%",Dialog\([^)]*\)(\([^)]*\)))~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~Activate("%Death_var%")
	%slashzero% ~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SF_workaround% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // ActionOverride(%Death_var%) Dialog() found in %SF_workaround%
				~
			END
			SPRINT textToReplace ~^[%%TAB%% ]*ActionOverride(\([^)]*\),Dialog\([^)]*\)("%Death_var%"))~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~Activate("%Death_var%")
	%slashzero% ~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SF_workaround% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // ActionOverride() Dialog(%Death_var%) found in %SF_workaround%
				~
			END~~~~~
//
			REPLACE_TEXTUALLY CASE_SENSITIVE EXACT_MATCH ~Replace_Death_in_PlayerDialog_3~ ~~~~~Replace_Death_in_PlayerDialog_3

			SPRINT textToReplace ~^[%%TAB%% ]*ActionOverride("%Death_var%",PlayerDialog\([^)]*\)(\([^)]*\)))~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~Activate("%Death_var%")
	%slashzero% ~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SF_workaround% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // ActionOverride(%Death_var%) PlayerDialog() found in %SF_workaround%
				~
			END
			SPRINT textToReplace ~^[%%TAB%% ]*ActionOverride(\([^)]*\),PlayerDialog\([^)]*\)("%Death_var%"))~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~Activate("%Death_var%")
	%slashzero% ~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SF_workaround% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // ActionOverride() PlayerDialog(%Death_var%) found in %SF_workaround%
				~
			END~~~~~
//
			REPLACE_TEXTUALLY CASE_SENSITIVE EXACT_MATCH ~Replace_Death_in_StartDialog_4~ ~~~~~Replace_Death_in_StartDialog_4

			SPRINT textToReplace ~^[%%TAB%% ]*StartDialog\(ue\)?("\([^)]*\)","%Death_var%")~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~Activate("%Death_var%")
	%slashzero% ~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SF_workaround% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // StartDialog(%Death_var%) found in %SF_workaround%
				~
			END
			SPRINT textToReplace ~^[%%TAB%% ]*StartDialogNoSet("%Death_var%")~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~Activate("%Death_var%")
	%slashzero% ~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SF_workaround% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // StartDialog(%Death_var%) found in %SF_workaround%
				~
			END~~~~~
//
			REPLACE_TEXTUALLY CASE_SENSITIVE EXACT_MATCH ~Replace_Death_in_PlayerDialog_5~ ~~~~~Replace_Death_in_PlayerDialog_5

			SPRINT textToReplace ~^[%%TAB%% ]*PlayerDialog\([^)]*\)("%Death_var%")~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~Activate("%Death_var%")
	%slashzero% ~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SF_workaround% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // PlayerDialog(%Death_var%) found in %SF_workaround%
				~
			END~~~~~
//
			REPLACE_TEXTUALLY CASE_SENSITIVE EXACT_MATCH ~Replace_Death_in_Dialog_6~ ~~~~~Replace_Death_in_Dialog_6

			SPRINT textToReplace ~^[%%TAB%% ]*Dialog\([^)]*\)("%Death_var%")~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~Activate("%Death_var%")
	%slashzero% ~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SF_workaround% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // Dialog(%Death_var%) found in %SF_workaround%
				~
			END~~~~~

///////////////////////////////////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////////////////////////////////

	COPY ~weidu_external/JOining_Party_Select/JOining_Party_Select_Base_DLG.tph~ ~weidu_external/JOining_Party_Select/JOining_Party_Select_Base_DLG.tph~
			REPLACE_TEXTUALLY CASE_SENSITIVE EXACT_MATCH ~Replace_Death_in_NOT_AllowDead~ ~~~~~Replace_Death_in_NOT_AllowDead

			SPRINT textToReplace ~\(^[%%TAB%% ]*!InPartyAllowDead("%Death_var%")\)~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~TriggerOverride("%Death_var%",Global("JO_Myself_AllowDead","LOCALS",0))~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SF_workaround% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %Death_var% : !InPartyAllowDead found in %SF_workaround%
				~
			END
			SPRINT textToReplace ~  !InPartyAllowDead("%Death_var%")~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~TriggerOverride("%Death_var%",Global("JO_Myself_AllowDead","LOCALS",0))~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SF_workaround% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... //  %Death_var% : !InPartyAllowDead found in %SF_workaround%
				~
			END~~~~~
			REPLACE_TEXTUALLY CASE_SENSITIVE EXACT_MATCH ~Replace_Death_in_AllowDead~ ~~~~~Replace_Death_in_AllowDead

			SPRINT textToReplace ~\(^[%%TAB%% ]*InPartyAllowDead("%Death_var%")\)~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~!TriggerOverride("%Death_var%",Global("JO_Myself_AllowDead","LOCALS",0))~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SF_workaround% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %Death_var% : InPartyAllowDead found in %SF_workaround%
				~
			END
			SPRINT textToReplace ~  InPartyAllowDead("%Death_var%")~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~!TriggerOverride("%Death_var%",Global("JO_Myself_AllowDead","LOCALS",0))~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SF_workaround% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... //  %Death_var% : InPartyAllowDead found in %SF_workaround%
				~
			END~~~~~
			REPLACE_TEXTUALLY CASE_SENSITIVE EXACT_MATCH ~Replace_Death_in_NOT_InParty~ ~~~~~Replace_Death_in_NOT_InParty

			SPRINT textToReplace ~\(^[%%TAB%% ]*!InParty("%Death_var%")\)~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~TriggerOverride("%Death_var%",Global("JO_Myself_InParty","LOCALS",0))~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SF_workaround% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %Death_var% : !InParty found in %SF_workaround%
				~
			END
			SPRINT textToReplace ~  !InParty("%Death_var%")~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~TriggerOverride("%Death_var%",Global("JO_Myself_InParty","LOCALS",0))~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SF_workaround% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... //  %Death_var% : !InParty found in %SF_workaround%
				~
			END~~~~~
			REPLACE_TEXTUALLY CASE_SENSITIVE EXACT_MATCH ~Replace_Death_in_InParty~ ~~~~~Replace_Death_in_InParty

			SPRINT textToReplace ~\(^[%%TAB%% ]*InParty("%Death_var%")\)~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~!TriggerOverride("%Death_var%",Global("JO_Myself_InParty","LOCALS",0))~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SF_workaround% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %Death_var% : InParty found in %SF_workaround%
				~
			END
			SPRINT textToReplace ~  InParty("%Death_var%")~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~!TriggerOverride("%Death_var%",Global("JO_Myself_InParty","LOCALS",0))~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SF_workaround% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... //  %Death_var% : InParty found in %SF_workaround%
				~
			END~~~~~
			REPLACE_TEXTUALLY CASE_SENSITIVE EXACT_MATCH ~Replace_Death_in_NOT_Valid~ ~~~~~Replace_Death_in_NOT_Valid

			SPRINT textToReplace ~!I[s|f]ValidForPartyDialog\(ue\)?("%Death_var%")~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~TriggerOverride("%Death_var%",Global("JO_Myself_Valid","LOCALS",0))~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SF_workaround% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %Death_var% : !(...)ValidForParty(...) found in %SF_workaround%
				~
			END~~~~~
			REPLACE_TEXTUALLY CASE_SENSITIVE EXACT_MATCH ~Replace_Death_in_Valid~ ~~~~~Replace_Death_in_Valid

			SPRINT textToReplace ~I[s|f]ValidForPartyDialog\(ue\)?("%Death_var%")~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~!TriggerOverride("%Death_var%",Global("JO_Myself_Valid","LOCALS",0))~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SF_workaround% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %Death_var% : (...)ValidForParty(...) found in %SF_workaround%
				~
			END~~~~~

///////////////////////////////////////////////////////////////////////////////////////////////////////////

END


	COPY ~weidu_external/JOining_Party_Select/JOining_Party_Select_Base_BCS.tph~ ~weidu_external/JOining_Party_Select/JOining_Party_Select_Base_BCS.tph~
							REPLACE_TEXTUALLY CASE_SENSITIVE EXACT_MATCH ~SF_workaround~ ~SOURCE_FILESPEC~


	COPY ~weidu_external/JOining_Party_Select/JOining_Party_Select_Base_DLG.tph~ ~weidu_external/JOining_Party_Select/JOining_Party_Select_Base_DLG.tph~
							REPLACE_TEXTUALLY CASE_SENSITIVE EXACT_MATCH ~SF_workaround~ ~SOURCE_FILESPEC~

		INCLUDE ~weidu_external/JOining_Party_Select/JOining_Party_Select_Base_BCS.tph~

		INCLUDE ~weidu_external/JOining_Party_Select/JOining_Party_Select_Base_DLG.tph~
