///////////////////////////////////////////////////////////////////////////////

ACTION_FOR_EACH Death_var IN

~%IMOEN_DV%~ // ImoenIren ~Imoen~ // ~ttimoen~       // Imoen
~Edwin~                                              // Edwin
~Jaheira~                         // ~ttjaheir~      // Jaheira
~Minsc~                           // ~ttminsc~       // Minsc
~Viconia~                                            // Viconia
~Dorn~                                               // Dorn
~Neera~                                              // Neera
~Rasaad~                                             // Rasaad

/////////////////////////// Continuous ///////////////////////////

~cmnikita~                          // Nikita

~Alora~                             // Alora_Continuous

~Ajantis~                           // Ajantis_Continuous

~Kivan~                             // Kivan_Continuous

~L#WALAH~                           // Walahnan_Continuous

~Coran~                             // Coran_Continuous 

~Yeslick~                           // Yeslick_Continuous 

~Xan~                               // Xan_Continuous 

~Branwen~                           // Branwen_Continuous 

~Tiax~                              // Tiax_Continuous 

~rh#isra~                           // Isra_Continuous 

// Next_Traveler Continuous

BEGIN

//							OUTER_SET EVAL ~Continuous_%Death_var%_Select~ = 1

//							OUTER_SET EVAL ~BG1_%Death_var%_Select~ = 0

//							OUTER_SET EVAL ~SoD_%Death_var%_Select~ = 0

//							OUTER_SET EVAL ~BG2_%Death_var%_Select~ = 0

								OUTER_SET EVAL ~%Death_var%_SoD_Content~ = 0

								OUTER_SET EVAL ~%Death_var%_BG2_Content~ = 0

END

//////////////////////////////////////////////////////////////////

ACTION_FOR_EACH Death_var IN

/////////////////////////// bg1 ///////////////////////////

~Ajantis~                             // Ajantis
~Alora~                               // Alora
~Branwen~    // ~ttbran~              // Branwen
~Coran~                               // Coran
~Dynaheir~                            // Dynaheir

~Eldoth~                              // Eldoth
~Faldorn~                             // Faldorn
~Garrick~                             // Garrick

~Kagain~                              // Kagain
~Khalid~                              // Khalid
~Kivan~                               // Kivan

~Montaron~                            // Montaron
~Quayle~                              // Quayle
~Safana~                              // Safana
~Sharteel~    // ~Shar-teel~          // Sharteel
~Skie~                                // Skie
~Tiax~                                // Tiax

~Xan~         // ttxan~               // Xan
~Xzar~                                // Xzar
~Yeslick~                             // Yeslick

~Baeloth~                             // Baeloth

/////////////////////////// Mods BG1 ///////////////////////////

// Ishlilka_The-Wizard-Slayer
~#Ishy~                               // Ishlilka

// ChaosKnight-kit
~ZYJCOB~                              // Jacob

// Askaria-Quest
~ZYASKA~                              // Askaria

// Isra BG1
~rh#isra~                             // Isra

// Finch
~SUFINCH~                             // Finch

// Drizzt Saga
~F_JARLAXE~                           // Jarlaxle
~F_ARTEMIS~                           // Artemis Enteri
~F_CATTIBR~                           // Catti-Brie
~F_BRUENOR~                           // Bruenor
~F_REGIS~                             // Regis
~F_DRIZZT~                            // Drizzt
~F_WULFGAR~                           // Wulfgar

// Dark Horizons
~CMTTHOR~                             // Thorin
~CMTMORW~                             // Morwen

// DSotSC
~DSBARDO~                              // Bardo
~DSBUB~                                // Bub Snikt
~Conchobhair~                          // Conchobhair
~CuChoinneach~                         // CuChoinneach
~Ferthgil~                             // Ferthgil Trollslayer
~JETLAYA~                              // Jet'laya
~KEIRIA~                               // Keiria Silverstring
~SKEEZER~                              // Skeezer Lumpkin VI
~Thorfinn~                             // Thorfinn Hauskluniff

// NTotSC
~WILL~                                 // Will Scarlet

// Valerie
~T2VAL~

// Indira
~J#Indi~

// Bristlelick
~L#BRIST~

// Glam's npc pack
~GV#DAVE~
~GV#FLAR~
~GV#LITT~
~GV#MOID~
~GV#VYND~

// Kale BG1
~X3Kale~

// New Tales of the Sword Coast
~Kasandra~
~Masambe~
~Alethra~
~Rimardo~
~Talindra~
~Theodor~
~Ariadne~
~Nathan~
~Namiir~
~Miranda~

// Walahnan BG1
~L#WALAH~

// Next_Traveler BG1

BEGIN

//							OUTER_SET EVAL ~Continuous_%Death_var%_Select~ = 0

//							OUTER_SET EVAL ~BG1_%Death_var%_Select~ = 1

//							OUTER_SET EVAL ~SoD_%Death_var%_Select~ = 0

//							OUTER_SET EVAL ~BG2_%Death_var%_Select~ = 0

								OUTER_SET EVAL ~%Death_var%_SoD_Content~ = 0

								OUTER_SET EVAL ~%Death_var%_BG2_Content~ = 0

END

//////////////////////////////////////////////////////////////////

ACTION_FOR_EACH Death_var IN

/////////////////////////// SoD ///////////////////////////

~Voghiln~                             // Voghiln
~Corwin~                              // Corwin
~Mkhiin~                              // Mkhiin
~Glint~                               // Glint

// Next_Traveler SoD

BEGIN

//							OUTER_SET EVAL ~Continuous_%Death_var%_Select~ = 0

//							OUTER_SET EVAL ~BG1_%Death_var%_Select~ = 0

//							OUTER_SET EVAL ~SoD_%Death_var%_Select~ = 1

//							OUTER_SET EVAL ~BG2_%Death_var%_Select~ = 0

								OUTER_SET EVAL ~%Death_var%_SoD_Content~ = 0

								OUTER_SET EVAL ~%Death_var%_BG2_Content~ = 0

END

//////////////////////////////////////////////////////////////////

ACTION_FOR_EACH Death_var IN

/////////////////////////// bg2 ///////////////////////////

~Aerie~                               // Aerie
~Anomen~                              // Anomen
~Cernd~                               // Cernd
~Haerdalis~                           // Haerdalis
~Hexxat~                              // Hexxat
~Jan~                                 // Jan
~Keldorn~                             // Keldorn
~Korgan~                              // Korgan
~Mazzy~                               // Mazzy
~Nalia~                               // Nalia
~Sarevok~                             // Sarevok
~Valygar~                             // Valygar
~Wilson~                              // Wilson
~Yoshimo~                             // Yoshimo

/////////////////////////// Mods BG2 ///////////////////////////

// Alora BG2
~CMALORA~                              // Alora

// Yeslick BG2
~LK#YESLK~                             // Yeslick

// The Undying
~cmninaf~                              // Ninafer
~callisto~                             // Callisto

// Summon Bhaalspawn
~BHAALSPW~                             // Sandra

// VampireTales
~cmgmiriam~                            // Miriam

// Kim
~Kim~                                  // Kim

// Severian
~#Severian~                            // Severian

// Frennedan
~Frennedan~                            // Frennedan

// Branwen BG2
~O#Bran~                               // Branwen
// Tiax BG2
~O#Tiax~                               // Tiax
// Xan BG2
~O#XAN~                                // Xan
// Coran BG2
~O#Coran~                              // Coran

// Auren Aseph
~K#AUREN~                              // Auren

// Isra BG2
~rh#Isra2~                             // Isra

// Nephele
~Nephele~                              // Nephele

// Sheena
~K#SHEENA~                             // Sheena

// Kiara / Zaiya
~Kiara~                                // Kiara
~Zaiya~                                // Zaiya

// The Beaurin Legacy
~QI#MI~                                // Minyae
~QI#ELA~                               // Elaryn

// Tyris Flare
~g#Tyris~                              // Tyris

// Region of Terror
~Wulfg2~                              // Wulfgar
~Reg2~                                // Regis
~Driz2~                               // Drizz
~Brue2~                               // Bruenor
~Catt2~                               // Catti-Brie
~Enter2~                              // Artemis
~Jarlax2~                             // Jarlaxle
~Tapio~                               // Tapio
~Randall~                             // Randall
~ALISSA1~                             // Alissa
~Mordrg~                              // Mordragon

//Shadow over Soubar
~SELENCE~                             // Selence
~CHARLOTT~                            // Charlotte
~BOLIVAR~                             // Bolivar
~TOMASTM~                             // Tomas

// ajantisbg2
~C#Ajantis~                            // Ajantis

// Kivan and Deheriana
~P#KIVAN~                              // Kivan
~P#DEHER~                              // Deheriana

// Yvette
~YxYve~

// The Luxley Family
~fhlseb~
~FHLAND~

//  Beyond the Law
~Kiyone~
~Kova~

// Petsy
~L3PETSY~

// Kale BG2
~X3Kal~

// Walahnan_BG2
~L#2WALAH~

// Autumns Twilight
~P_Dusk~                             // Dusk 
~P_Fall~                             // Fall 
~P_Chon~                             // Cho'Nuja 
~P_Alen~                             // Alendir 

// Next_Traveler BG2

BEGIN

//							OUTER_SET EVAL ~Continuous_%Death_var%_Select~ = 0

//							OUTER_SET EVAL ~BG1_%Death_var%_Select~ = 0

//							OUTER_SET EVAL ~SoD_%Death_var%_Select~ = 0

//							OUTER_SET EVAL ~BG2_%Death_var%_Select~ = 1

END

//////////////////////////////////////////////////////////////////
