///////////////////////////////////////////////////////////////////////////////

ACTION_FOR_EACH Death_var IN

// Original Imoen           ~%IMOEN_DV%~ %ImoenIren% // ~ttimoen~    // Imoen
// Original Edwin           ~Edwin~                               // Edwin
// Original Jaheira         ~Jaheira~    // ~ttjaheir~            // Jaheira
// Original Minsc           ~Minsc~      // ~ttminsc~             // Minsc
// Original Viconia         ~Viconia~                             // Viconia
// Original Dorn            ~Dorn~                                // Dorn
// Original Neera           ~Neera~                               // Neera
// Original Rasaad          ~Rasaad~                              // Rasaad

/////////////////////////// Continuous ///////////////////////////

// EET Nikita           ~cmnikita~                            // Nikita

// EET Alora_Continuous           ~Alora~                            // Alora_Continuous

// Next_Traveler Continuous

BEGIN

							OUTER_SET ~Continuous_%Death_var%_Select~ = 1

END

//////////////////////////////////////////////////////////////////

ACTION_FOR_EACH Death_var IN

/////////////////////////// bg1 ///////////////////////////

// Original Ajantis         ~Ajantis~                             // Ajantis
// Original Alora           ~Alora~                               // Alora
// Original Branwen         ~Branwen~    // ~ttbran~              // Branwen
// Original Coran           ~Coran~                               // Coran
// Original Dynaheir        ~Dynaheir~                            // Dynaheir

// Original Eldoth          ~Eldoth~                              // Eldoth
// Original Faldorn         ~Faldorn~                             // Faldorn
// Original Garrick         ~Garrick~                             // Garrick

// Original Kagain          ~Kagain~                              // Kagain
// Original Khalid          ~Khalid~                              // Khalid
// Original Kivan           ~Kivan~                               // Kivan

// Original Montaron        ~Montaron~                            // Montaron
// Original Quayle          ~Quayle~                              // Quayle
// Original Safana          ~Safana~                              // Safana
// Original Sharteel        ~Sharteel~    // ~Shar-teel~          // Sharteel
// Original Skie            ~Skie~                                // Skie
// Original Tiax            ~Tiax~                                // Tiax

// Original Xan             ~Xan~         // ttxan~               // Xan
// Original Xzar            ~Xzar~                                // Xzar
// Original Yeslick         ~Yeslick~                             // Yeslick

// Original Baeloth         ~Baeloth~                             // Baeloth

/////////////////////////// Mods BG1 ///////////////////////////

// Ishlilka_The-Wizard-Slayer
// Mod Ishlilka             ~#Ishy~                               // Ishlilka

// ChaosKnight-kit
// Mod Jacob                ~ZYJCOB~                              // Jacob

// Askaria-Quest
// Mod Askaria              ~ZYASKA~                              // Askaria

// Isra BG1
// Mod Isra_BG1             ~rh#isra~                             // Isra

// Finch
// Mod Finch                ~SUFINCH~                             // Finch

// Drizzt Saga
// Mod Jarlaxle_Saga        ~F_JARLAXE~                           // Jarlaxle
// Mod Artemis_Enteri_Saga  ~F_ARTEMIS~                           // Artemis Enteri
// Mod Catti-Brie_Saga      ~F_CATTIBR~                           // Catti-Brie
// Mod Bruenor_Saga         ~F_BRUENOR~                           // Bruenor
// Mod Regis_Saga           ~F_REGIS~                             // Regis
// Mod Drizzt_Saga          ~F_DRIZZT~                            // Drizzt
// Mod Wulfgar_Saga         ~F_WULFGAR~                           // Wulfgar

// Dark Horizons
// Mod Thorin               ~CMTTHOR~                             // Thorin
// Mod Morwen                ~CMTMORW~                            // Morwen

// DSotSC
// Mod Bardo                ~DSBARDO~                              // Bardo
// Mod Bub_Snikt            ~DSBUB~                                // Bub Snikt
// Mod Conchobhair          ~Conchobhair~                          // Conchobhair
// Mod CuChoinneach         ~CuChoinneach~                         // CuChoinneach
// Mod Ferthgil_Trollslayer ~Ferthgil~                             // Ferthgil Trollslayer
// Mod Jet'laya             ~JETLAYA~                              // Jet'laya
// Mod Keiria_Silverstring  ~KEIRIA~                               // Keiria Silverstring
// Mod Skeezer_Lumpkin_VI   ~SKEEZER~                              // Skeezer Lumpkin VI
// Mod Thorfinn_Hauskluniff ~Thorfinn~                             // Thorfinn Hauskluniff

// NTotSC
// Mod Will_Scarlet         ~WILL~                                 // Will Scarlet

// Valerie
// Mod Valerie ~T2VAL~

// Indira
// Mod Indira ~J#Indi~

// Bristlelick
// Mod Bristlelick ~L#BRIST~

// Glam's npc pack
// Mod Dave ~GV#DAVE~
// Mod Flara ~GV#FLAR~
// Mod Littlun ~GV#LITT~
// Mod Moidre ~GV#MOID~
// Mod Vynd ~GV#VYND~

// Kale BG1
// Mod Kale_BG1 ~X3Kale~

// New Tales of the Sword Coast
// Mod Kasandra ~Kasandra~
// Mod Masambe ~Masambe~
// Mod Alethra ~Alethra~
// Mod Rimardo ~Rimardo~
// Mod Talindra ~Talindra~
// Mod Theodor ~Theodor~
// Mod Ariadne ~Ariadne~
// Mod Nathan ~Nathan~
// Mod Namiir ~Namiir~
// Mod Miranda ~Miranda~

// Next_Traveler BG1

BEGIN

							OUTER_SET ~BG1_%Death_var%_Select~ = 1

END

//////////////////////////////////////////////////////////////////

ACTION_FOR_EACH Death_var IN

/////////////////////////// SoD ///////////////////////////

// Original Voghiln         ~Voghiln~                             // Voghiln
// Original Corwin          ~Corwin~                              // Corwin
// Original Mkhiin          ~Mkhiin~                              // Mkhiin
// Original Glint           ~Glint~                               // Glint

// Next_Traveler SoD

BEGIN

							OUTER_SET ~SoD_%Death_var%_Select~ = 1

END

//////////////////////////////////////////////////////////////////

ACTION_FOR_EACH Death_var IN

/////////////////////////// bg2 ///////////////////////////

// Original Aerie           ~Aerie~                               // Aerie
// Original Anomen          ~Anomen~                              // Anomen
// Original Cernd           ~Cernd~                               // Cernd
// Original Haerdalis       ~Haerdalis~                           // Haerdalis
// Original Hexxat          ~Hexxat~                              // Hexxat
// Original Jan             ~Jan~                                 // Jan
// Original Keldorn         ~Keldorn~                             // Keldorn
// Original Korgan          ~Korgan~                              // Korgan
// Original Mazzy           ~Mazzy~                               // Mazzy
// Original Nalia           ~Nalia~                               // Nalia
// Original Sarevok         ~Sarevok~                             // Sarevok
// Original Valygar         ~Valygar~                             // Valygar
// Original Wilson          ~Wilson~                              // Wilson
// Original Yoshimo         ~Yoshimo~                             // Yoshimo

/////////////////////////// Mods BG2 ///////////////////////////

// Alora BG2
// Mod Alora BG2            ~%CMALORA%~                              // Alora

// Yeslick BG2
// Mod Yeslick BG2          ~LK#YESLK~                             // Yeslick

// The Undying
// Mod Undying              ~cmninaf~                              // Ninafer
// Mod Undying              ~callisto~                             // Callisto

// Summon Bhaalspawn
// Mod Sandra               ~BHAALSPW~                             // Sandra

// VampireTales
// Mod Miriam               ~cmgmiriam~                            // Miriam

// Kim
// Mod Kim                  ~Kim~                                  // Kim

// Severian
// Mod Severian             ~#Severian~                            // Severian

// Frennedan
// Mod Frennedan            ~Frennedan~                            // Frennedan

// Branwen BG2
// Mod Branwen_BG2          ~O#Bran~                               // Branwen
// Tiax BG2
// Mod Tiax_BG2             ~O#Tiax~                               // Tiax
// Xan BG2
// Mod Xan_BG2              ~O#XAN~                                // Xan
// Coran BG2
// Mod Coran_BG2            ~O#Coran~                              // Coran

// Auren Aseph
// Mod Auren                ~K#AUREN~                              // Auren

// Isra BG2
// Mod Isra_BG2             ~rh#Isra2~                             // Isra

// Nephele
// Mod Nephele_Samios       ~Nephele~                              // Nephele

// Sheena
// Mod Sheena               ~K#SHEENA~                             // Sheena

// Kiara / Zaiya
// Mod Kiara                ~Kiara~                                // Kiara
// Mod Zaiya                ~Zaiya~                                // Zaiya

// The Beaurin Legacy
// Mod Minyae               ~QI#MI~                                // Minyae
// Mod Elaryn               ~QI#ELA~                               // Elaryn

// Tyris Flare
// Mod Tyris                ~g#Tyris~                              // Tyris

// Region of Terror
// Mod Wulfgar_Terror            ~Wulfg2~                              // Wulfgar
// Mod Regis_Terror              ~Reg2~                                // Regis
// Mod Drizzt_Terror             ~Driz2~                               // Drizz
// Mod Bruenor_Terror            ~Brue2~                               // Bruenor
// Mod Catti-Brie_Terror         ~Catt2~                               // Catti-Brie
// Mod Artemis_Entreri_Terror    ~Enter2~                              // Artemis
// Mod Jarlaxle_Terror           ~Jarlax2~                             // Jarlaxle
// Mod Tapio_Perkiomaki_Terror   ~Tapio~                               // Tapio
// Mod Randall_Terror            ~Randall~                             // Randall
// Mod Alissa_Terror             ~ALISSA1~                             // Alissa
// Mod Mordragon_Terror          ~Mordrg~                              // Mordragon

//Shadow over Soubar
// Mod Selence_Hillstar_Soubar   ~SELENCE~                             // Selence
// Mod Charlotte_Soubar          ~CHARLOTT~                            // Charlotte
// Mod Bolivar_Soubar            ~BOLIVAR~                             // Bolivar
// Mod Tomas_Tomalson_Soubar     ~TOMASTM~                             // Tomas

// ajantisbg2
// Mod Ajantis_BG2          ~C#Ajantis~                            // Ajantis

// Kivan and Deheriana
// Mod Kivan_BG2            ~P#KIVAN~                              // Kivan
// Mod Deheriana            ~P#DEHER~                              // Deheriana

// Yvette
// Mod Yvette ~YxYve~

// The Luxley Family
// Mod Sebastian ~fhlseb~
// Mod Andrei ~FHLAND~

//  Beyond the Law
// Mod Kiyone ~Kiyone~
// Mod Kova ~Kova~

// Petsy
// Mod Petsy ~L3PETSY~

// Kale BG2
// Mod Kale_BG2 ~X3Kal~

// Next_Traveler BG2

BEGIN

							OUTER_SET ~BG2_%Death_var%_Select~ = 1

END

//////////////////////////////////////////////////////////////////
